### ISSUE TITLE
Object custom field data should return instances for object and multi-object custom fields

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#10052]
### NetBox version

3.2.9

### Feature type

Change to existing functionality

### Proposed functionality

I think it could need a change for the `CustomFieldMixin` to work. Because `get_custom_fields` returns a `dict` where the key is the `object` and not the `field name`.

### Use case

I am trying to build a custom link URL which requires querying custom object attributes. I want to access the `site.slug` on the custom object assigned to ClusterGroup via a plugin model, something like

```
object.get_custom_fields()['field_name'].site.slug
```

**Comment by jeremystretch** [comment]
Unpacking the specific use, it seems the goal here is for `object.cf` to return a properly deserialized version of object and multi-object fields (rather than the PK or list of PKs, respectively). This should be doable, I think, by running `custom_field_data` through `deserialize()` for each field.

This would technically be a breaking change, however I can also see an argument that this is more of bug fix than a feature request.

**Comment by renatoalmeidaoliveira** [comment]
I guess the main problem here is that cf returns the pk and the get_custom_fields returns a dict with the keys equals the object and not the custom field name.
One option could be create a new method that returns a dict with keys equals the field name and the value the object or list of objects, like get_custom_relations that way there're no major changes in the core code.

**Comment by jeremystretch** [comment]
I've tweaked the `cf` attribute so that it now returns deserialized values (i.e. objects instead of their IDs):

```
>>> tenant=Tenant.objects.get(pk=5)
>>> tenant.cf
{'primary_site': <Site: DM-NYC>, 'cust_id': 'DMI01', 'is_active': True}
```
