### ISSUE TITLE
I've added a custom `empty` lookup to address this use case. You can now do e.g. `?dns_name__empty=False` to return all records with non-empty values.

### ISSUE THREAD

**Issue by AndreasMoe** [netbox-community/netbox#10110]
Hi, I am not able to to make this work using API

I've added a custom `empty` lookup to address this use case. You can now do e.g. `?dns_name__empty=False` to return all records with non-empty values.

_Originally posted by @jeremystretch in https://github.com/netbox-community/netbox/issues/6138#issuecomment-872488043_

api/ipam/ip-addresses/?dns_name__empty=False
or
api/ipam/ip-addresses/?limit=0&dns_name__empty=False

please advice

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
