### ISSUE TITLE
Cluster site information missing on some clusters after upgrade

### ISSUE THREAD

**Issue by AndreasMoe** [netbox-community/netbox#10211]
### NetBox version

v3.3.1

### Python version

3.9

### Steps to Reproduce

API import of VM failes after upgrade to version 3.3.1, as some clusters miss the site information
{"cluster":["The selected cluster (DC1FHVCL006 is not assigned to this site (None)."]}
![image](https://user-images.githubusercontent.com/43982077/187429696-42c6a6d9-7944-48d8-b0f7-78ef29ae16ec.png)
not consistant with GUI (see standalone DC2)
![image](https://user-images.githubusercontent.com/43982077/187429908-469a90c4-ea2f-4ba2-bb95-77fd9a798cc3.png)
After altering to setting Site on VM, the case was resolved. But if I dont include the Site information on the VM json, the error above shows and no VM is imported

Some VMs have site information , but most dont have site information

### Expected Behavior

API and GUI should give same information and VM should be imported without site information as long as a cluster is specified

### Observed Behavior

The selected cluster (DC1FHVCL006 is not assigned to this site (None)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
