### ISSUE TITLE
Wrong working Hyperlink

### ISSUE THREAD

**Issue by tomaszcwik1** [netbox-community/netbox#10228]
### NetBox version

v3.3.1

### Python version

3.8

### Steps to Reproduce

after pick existing device from rack menu, hyperlink does not route site to https 
"add device" work fine

### Expected Behavior

open https://netmiko/dcim/devices/65/

existing device:
![image](https://user-images.githubusercontent.com/111953230/187713840-939a270b-7117-44b6-93de-d7bc837f8342.png)

For example "add device"
![image](https://user-images.githubusercontent.com/111953230/187713800-813005b6-aa9a-4b4d-8a5b-a25db6dbde0f.png)
### Observed Behavior

open              netmiko/dcim/devices/65/
(shuld https://netmiko/dcim/devices/65/)

after add https work fine 

### Observed Behavior

open netmiko/dcim/devices/65/

after add https work fine

**Comment by jeremystretch** [comment]
The "add device" link is relative (e.g. `/dcim/devices/add/`), so the browser is simply referencing the current URL to determine the full linked URL. The HTTPS scheme is missing from the device links because your HTTP server is not configured to convey this information to the WSGI worker. Please see [this wiki article](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevation-links-use-wrong-domain) for tips on how to rectify this. (This configuration is also covered in NetBox's [installation documentation](https://docs.netbox.dev/en/stable/installation/5-http-server/#http-server-installation).)
