### ISSUE TITLE
Add tenant and group uniqueness constraint if tenant belongs to a group

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#10374]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

Add `unique_together` for `name` and `group` on the `Tenant` model

### Use case

I have a few end-users that have exact same name but they belong to different companies. We have modelled the companies as tenant groups on NetBox. I'd like to add two different people both named `Tim` to `Company1` and `Company2`. In future, I could have another `Tim` who does not belong to any groups.

In all cases, I would like the validation by the group (if associated) just how contacts work.

We also use the `tenant` in our invoicing so adding a name like `Tim 1` does not work for us as this would be reflected on the bill sent to the customer.

Adding the uniqueness constraint should not break anything existing either since it was not possible to have two `Tims` in the system anyhow.

Previously raised as bug #10373 but closed

### Database changes

Add `unique_together` for `name` and `group` on the `Tenant` model

**Comment by abhi1693** [comment]
@ITJamie I'm not asking to disallow global unique. I'm instead asking to make the tenant scope limited to the group only if it has one. If the tenant does not have a group, then it should work the same way it is working now.

**Comment by kprince28** [comment]
I have a similar issue where I'm trying to import data from our existing CMDB to our new NetBox installation. Today, I ran into the same issue wherein couple of my tenants though belong to different groups with different resources are not being added. I'm using REST APIs for perfomring the calls. I like the idea to limit the scope of the tenant into the group but also keep them unique if do not belong to any group.

If it's not possible, atleast remove the name uniqueness so that I can create my custom validator to implement my business logic.

**Comment by abhi1693** [comment]
@jeremystretch Would the new implementation help in solving this issue in any way? If the core does not implement a solution, will I be able to override the conditional logic?
