### ISSUE TITLE
Wrong dependent objects when deleting contacts

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#10491]
### NetBox version

v.3.3.4

### Python version

3.9

### Steps to Reproduce

1. Open a contact that has assignments, like https://demo.netbox.dev/tenancy/contacts/3/
2. Press delete button
3. Notice the error box  in the lower right corner that says, that the contact depends on itself.

### Expected Behavior

The error box should link/list names of assigned objects.

### Observed Behavior

Instead of assigned objects, the contact itself is listed as many times as number of assignments exist. In this example it is "Dwight Schrute" 2 times while it should be "vm1" and "DM-Scranton".

![grafik](https://user-images.githubusercontent.com/20901110/192701238-3b823d3a-e2a3-451f-b369-9a474a4ead48.png)

**Comment by jeremystretch** [comment]
> Instead of assigned objects, the contact itself is listed as many times as number of assignments exist. In this example it is "Dwight Schrute" 2 times while it should be "vm1" and "DM-Scranton".

That's not quite what's happening. The first object listed is the _assignment_ of this contact to an object (as the primary contact). This is working as intended, because it is the assignment itself which is preventing the deletion of the contact, rather than the object to which it is assigned.

The extend of the bug is that the contact itself is also listed as a blocking object (because it's being inferred from the assignment).
