### ISSUE TITLE
Webhook integration for Reports

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10552]
### NetBox version

v3.3.4

### Feature type

New functionality

### Proposed functionality

It would be nice to be able to call a webhook after a report has finished. This would be achieved by adding `Extras > Reports` to the `Content types` when creating a webhook. 

### Use case

This is very useful when you want to evaluate the results of a report automatically.

**Comment by jeremystretch** [comment]
I don't think this is feasible: Webhooks are designed to track the creation, modification, and deletion of individual database objects as discrete events, and running a report doesn't map to any of these actions. However, it's also unnecessary. Because you have direct Python access within a report, you're free to generate arbitrary HTTP requests as needed using e.g. the `requests` library.

**Comment by kkthxbye-code** [comment]
It would be possible to enable webhooks for the JobResult model, which essentially provides the functionality he is requesting.

I had planned on implementing it here but got sidetracked #8958

**Comment by jeremystretch** [comment]
Ah, yeah that makes more sense. Looking at the history of #8958, I see that I applied the "needs milestone" tag after it was closed for going stale. I'm pretty sure the intent was to keep it open.
