### ISSUE TITLE
Allow custom links to be added to list views

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#10581]
### NetBox version

3.3.5

### Feature type

New functionality

### Proposed functionality

Custom links can currently be added to object views i.e. Circuits -> Circuit or DCIM -> Site

It would be very useful if they could also be added to the corresponding list views i.e. Circuits -> Circuits or DCIM -> Sites

### Use case

Expand on the locations that custom links can be added.  My personal use case is to create custom links to internal documentation on list views.

**Comment by kkthxbye-code** [comment]
Maybe I'm misunderstanding, but you can already add custom links to tables. They should show up when you configure the table and add the column.

**Comment by jasonyates** [comment]
> Maybe I'm misunderstanding, but you can already add custom links to tables. They should show up when you configure the table and add the column.

You can associate a custom link to an object i.e Circuits -> Circuit and it can be added as a column in the table. It also shows up on the top right of the object view e.g.:

<img width="1187" alt="Screenshot 2022-10-06 at 09 53 19" src="https://user-images.githubusercontent.com/242483/194267866-4878dcf4-f026-43db-aa26-201e1d732364.png">

This FR is related to having that same behaviour on the list view i.e. allowing me to associate a custom link to the Circuits -> Circuit list view and having it appear in the top right of the relevant list view e.g. https://demo.netbox.dev/circuits/circuits/

**Comment by jeremystretch** [comment]
Going to close this out as there's been no further conversation around the points above.

**Comment by mwobst** [comment]
Well, right now I was actually looking for exactly this feature. :)

I wanted to use that feature to give our (potiential) users a quick filtering method (by a certain attribute). Yes, you may click on Filter, then search the attribute, select your value or enter the text … and you may bookmark the result view. But still … making things easier could be the edge in discussion "Netbox vs. tedious time consuming custom application.

My opinion: 
If used on an overview context (you could use plural and write "[Overview]" or sth. like this at the Model dropdown menu), replace these two Template fields with simple Textboxes for Link and (relative) URL, with no jinja2 stuff in play at all.

There is another use cases: Sometimes you just want to have some static link at an overview page, because it refers to a certain documentation concerning work steps for whatever (circuits? server installation? Sth. like this).

Just my 3 cents (because of inflation)
