### ISSUE TITLE
link 'assigned' checkbox to device rather than ip

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10580]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

When searching for an IP, the result shows the 'assigned' green checkbox if an IP address is assigned to a device/vm/...
The current link of the green check is to the IP address object.
I like to propose to change that to the device/vm/... the IP is assigned to.

### Use case

When the checkbox is clicked, it is more intuitive to go to the device it is assigned to.
Now it requires 2 additional clicks to go to the device.

**Comment by cpund** [comment]
@jeremystretch I can work on implementing this

**Comment by cpund** [comment]
Got around to digging into the code and familiarizing myself with this portion. I see that there are already two columns (that are just hidden by default) that show both A. the device, and B. the interface. 

I do agree that clicking the checkmark to go to the device would be more intuitive, however is it more intuitive to send the user to the device, or the interface? Or perhaps, a third solution: if the IP is listed as the primary IP of a device, send them to a device, otherwise send them to the interface? Thoughts?

**Comment by PieterL75** [comment]
The checkbox is very slim. The device or interface table makes the table wider.
To be honest, the interface view has less added value than then device view. I don't see a reason to link it to the interface.

Maybe we can link it to the interface tab of the device?

**Comment by jeremystretch** [comment]
IMO linking to the interface is preferable, but I don't have a strong opinion.
