### ISSUE TITLE
Allow custom object fields to reference a user or group

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#10600]
### NetBox version

v3.3.5

### Feature type

Data model extension

### Proposed functionality

Being able to create object type custom fields with Netbox users.

### Use case

Being able to point a specific user which is responsible for a given object, like a device or VM.

**Comment by bistraque** [comment]
That's why _Contacts_ are for: give a specific role to a specific contact for a given object, and for free you get a many-to-many relationship. In case an object does not have a _Contacts_ field, a custom field of that type will do. It also allows for _Contacts_ to exist while not being _Users_ with credentials on Netbox itself (covers different tenancy models).

Arguably, we may question the use case where a _Contact_ is optionally associated with a Netbox _User_ at creation time (e.g. autofill name and associated info). This could be helpful as a "garbage collection" strategy to detect obsolete contact info (via scripting for example if user no longer valid in ldap).

**Comment by jeremystretch** [comment]
I think it's reasonable to allow referencing a NetBox user (or group) as well; we do this today with rack reservations.

**Comment by abhi1693** [comment]
Can I take a shot at this?

**Comment by jeremystretch** [comment]
Assigned to you @abhi1693, thanks!

**Comment by abhi1693** [comment]
For the assigned user/group, should the custom field be hidden from the UI that were not assigned on it?

**Comment by jeremystretch** [comment]
@abhi1693, sorry, I'm not clear on what you're asking. Could you give me an example?

**Comment by abhi1693** [comment]
Lets say I created a custom field and assigned to `bob`. Should the field only be visible to `bob` whether its view or edit on the UI? If so, should this also be tackled on the API side?

**Comment by jeremystretch** [comment]
No, I don't think so. I believe the intent here is merely to be able to associate an arbitrary object with a particular user or group, like we do currently for rack reservations.
