### ISSUE TITLE
Group parent/child devices in tenant view

### ISSUE THREAD

**Issue by 2code4me** [netbox-community/netbox#10652]
### NetBox version

3.3.5

### Feature type

New functionality

### Proposed functionality

Hi, would be possible to add a function (for example adding a checkbox) to group child devices to their parent to count them as a unique device in tenants view?

### Use case

Example:

I'm adding a Netapp E2860 of a customer. 
The device is a storage chassis with 4 bays (well 6 to be honest, as 2 are used for fans).
2 bays used for PSU and 2 bays used for storage controller.
If I deploy 1 E2860 chassis (Parent) and add to it 2 PSU and 2 Controllers (Childs), when I take a look to the customer tenant I see he has 5 Devices.
That, yes, formerly is correct but usually it has to be considered 1 single storage device and only if I want to go deeper in details I can see the controllers and PSU.

Maybe this function could be managed with a flag in child creation, something like "Link this device to its parent for device count" so that in other cases, like a blade chassis with different server, I can leave the flag unselected and each device can be counted as one.

### Database changes

Probably a new flag button is needed. Don't know which modification are needed at database level.

**Comment by 2code4me** [comment]
UP!

**Comment by jeremystretch** [comment]
What you're describing is the intended behavior; you see five devices listed for the customer because five devices in fact exist. I'm not familiar with the particular hardware you mention, but it might be more appropriate for your use case to employ [modules](https://docs.netbox.dev/en/stable/models/dcim/module/) rather than child devices, which do not appear under the devices list.
