### ISSUE TITLE
Add Enable/Disable interface quick action in device view

### ISSUE THREAD

**Issue by etfz** [netbox-community/netbox#10665]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Add a quick action button for toggling active state of an interface near or inside the Edit/Delete menu, and possibly also one below the table for bulk toggling.

### Use case

Enabling or disabling interfaces seems to me like a basic and common task that could be more readily available. The per interface quick action bar is starting to get a bit cluttered, but if placed in the Edit menu I feel like that should not be an issue.

**Comment by chambersh1129** [comment]
I'd like to work on this.  Design wise, I see the yellow Edit/Rename and red Delete/Disconnect button at the bottom of an interface table when looking at a device.  Would a green "Enable" and red "Disable" button suffice?

For the backend I would look to create a new view/url, something similar to the dcim/views/BulkDisconnectView because a generic likely doesn't exist.  Should it prompt the user with an "are you sure" like the bulk disconnect/delete does or jshould it ust enable/disable based on the button pressed then return?

Alternatively, this is already supported in a way.  You can select multiple interfaces, click the "Edit" button at the bottom of the table, and enable/disable the port from there.  It is a few extra clicks, but it is still bulk editing multiple ports so this feature may not be needed.

**Comment by etfz** [comment]
As far as I'm concerned that all sounds good. A confirmation dialog for bulk toggling seems sensible. I am aware of the existing functionality.

I am at least as interested in the functionality of individual interface toggles.
