### ISSUE TITLE
Add connector type to cables

### ISSUE THREAD

**Issue by jehrhardt-bego** [netbox-community/netbox#10717]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

adding a field "connector type" to cables would make it easier to document different types of fiber cables.

I think the most common (at least for us) are
LC/PC
SC/PC
E2000/APC
MPO/A
MPO/B

### Use case

With this field users can correctly document cross connects, patch cables and know the correct cable if it needs to be replaced.

### Database changes

add a field connector type

### External dependencies

none

**Comment by bluikko** [comment]
In #10724 you proposed to add SFP/etc. module types. Wouldn't these two kind go together? Since it is the module that defines the connector type (on the host side).
And therein, IMHO, lies _one_ of the major issues with this proposal - you are only thinking about fiber-optic patch cords. But a "cable" in NetBox is much more than that: it is any cable, whether a fiber or copper patch cord, AC or DC power cable, stack cable, serial cable, ...

You might be able to use custom fields to document what you need. I am afraid that to be taken seriously this proposal will need to be massively more fleshed out.

**Comment by eronlloyd** [comment]
Hello @jehrhardt-bego. You can track the cable connectors via the front/rear port types, and then define the cable type (such as OS2) in that record to properly model the entire cable. It would be nice to populate the optical cable types with the proper ITU codes (could be a custom field for now), but otherwise this should do what you need.

**Comment by apellini** [comment]
But using Front Port and Rear Port has not sense on my point of view. Having the possibility to document the connector on both side could be useful (pheraps in some case mandatory).

I think that Front Port and Rear Port are used for Patch Panel purposes or for documenting ports that are present on device that are vendor specific.
