### ISSUE TITLE
ModuleNotFoundError exception rendering API schema under Python 3.9+

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10712]
### NetBox version

v3.3.5

### Python version

3.9

### Steps to Reproduce

1. Install NetBox using Python 3.9 or later
2. Visit `/api/docs/?format=openapi` to render the raw API schema

### Expected Behavior

The schema should render successfully.

### Observed Behavior

A ModuleNotFoundError exception is raised. This appears to be due to a conflict introduced by `swagger-spec-validator` v3.0.0 under Python 3.9 or later.

**Comment by tijuca** [comment]
The underlying upstream issue in swagger_spec_validator has been fixed by adding the missed required additional package dependency.
https://github.com/Yelp/swagger_spec_validator/commit/1e10f01af0e662b1ea073650f720b54ae95cd9c4

There is now a new version 3.0.3 available which has included that fix. I'm using a local instance of NetBox 3.3.6 which is working fine with a by me patched swagger_spec_validator package.
