### ISSUE TITLE
Add list of racked devices on a Site page

### ISSUE THREAD

**Issue by fatman00** [netbox-community/netbox#10828]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

When looking at the page for sites there is a widget with all the Non-Racked Devices. It would be great if the page also included a widget with all the racked devices as well.

### Use case

When looking at a site page right now it only shows a view of all the non-racked devices. If all devices on the site is racked it is not easy to find them.

**Comment by ZPrimed** [comment]
I think this _may_ be done on purpose, as listing all Racked devices on a Site could be pretty large list. Since NetBox is intended as a DCIM, and most data centers are generally centered around Racks, I believe the intent is that you would click on the "Racks" section of a Site in order to drill into the Devices. I believe Non-Racked devices are explicitly called out explicitly because they _aren't_ in Racks.

If you truly want to see a list of all Devices for a Site, there are other ways to get that information (e.g. filtering from inside the Devices view), instead of trying to show all of those Devices on the Site Overview page. 

Note that the Non-Racked Devices "widget" limits itself to 10 devices, too... so unless you've got a relatively small site, you're probably going to overflow a hypothetical "Racked Devices" widget.

**Comment by jeremystretch** [comment]
There are many types of objects that can be assigned to a site: location, rack, device, VM, etc. Embedding a table for each of these on the site view would be extremely slow and cumbersome. This is why we instead show the count of each object type with a link to the filtered list view for each.
