### ISSUE TITLE
Child Prefix is displayed under wrong parent when using VRFs

### ISSUE THREAD

**Issue by the-rubikscube** [netbox-community/netbox#10842]
### NetBox version

v3.3.7 (docker)

### Python version

3.10

### Steps to Reproduce

1. Create 2 VRFs, e.g. vrf1 and vrf2
2. For each VRF, create a Prefix and a child prefix with the same IP addresses, e.g. 1.1.0.0/16 for parent and 1.1.1.0/24 for child
3. Navigate to the Prefix view. If not already enabled, adjust the settings so depth indicators are shown

### Expected Behavior

In the prefix overview, the child prefixes should be listed under their corresponding parent, taking the VRF assignment into account.

### Observed Behavior

Both child prefixes are shown below the second parent prefix, although the child count on the parents is correct.
![grafik](https://user-images.githubusercontent.com/115145568/199989102-28cc977c-f226-4518-906d-021ec69a320c.png)

**Comment by jeremystretch** [comment]
You're seeing this because you've ordered the list by prefix value (note the arrow next to the "Prefix" heading). You can clear this by clicking the red X in the column header. By default, prefixes are ordered by VRF:

![Screenshot 2022-11-10 at 16-43-07 Prefixes NetBox](https://user-images.githubusercontent.com/13487278/201212016-329855eb-e442-4d8d-b7af-67b19573477e.png)
