### ISSUE TITLE
Allow duplicate ASNs in different RIRs

### ISSUE THREAD

**Issue by zacho112** [netbox-community/netbox#11008]
### NetBox version

v3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

Allow duplicate ASN's if in different RIR's.

Today Netbox fails with `ASN with this ASN already exists.`

### Use case

If you for some reason uses the same private AS numbers across your infrastructure, it would be nice to be able to document them i Netbox. This is not possible today, because you're not allowed to have duplicate ASN's, even if the RIR's is set to Private.

**Comment by jeremystretch** [comment]
While I understand the use case, it seems a bit niche, and the corollary of your proposal is that AS numbers alone can no longer be employed as unique identifiers. My gut says this would do more harm than good.

**Comment by sleepinggenius2** [comment]
We have a number of BGP peerings with our customers where we use the same range of private ASNs at each site for ones that don't have their own. I was trying to utilize the [NetBox BGP Plugin](https://github.com/k01ek/netbox-bgp) to document these and am now getting hit with this limitation. It looks like that plugin used to include its own ASN model that only had to be unique to a site, which would have worked very well for my use case, but it now uses the core ASN model, which has this globally unique constraint. I would love to see something like an "Enforce unique ASN" option added on the RIR, like we already have with the "Enforce unique space" one on a VRF.

**Comment by zacho112** [comment]
> While I understand the use case, it seems a bit niche, and the corollary of your proposal is that AS numbers alone can no longer be employed as unique identifiers. My gut says this would do more harm than good.

This make sense, for non-private AS numbers

**Comment by jeremystretch** [comment]
@zacho112 to be clear, the limitation applies to private ASNs as well. As soon as you have, for example, two ASNs numbered 65001, you can no longer ever just refer to "ASN 65001;" it always needs to be accompanied by some other qualifying attribute (e.g. site or tenant) to uniquely identify the specific object.

I'm not saying that this is an unacceptable burden, just calling it out as a trade-off.

**Comment by sleepinggenius2** [comment]
Looking through our dataset, the combination of ASN and Tenant (may be null/empty) currently appears to be unique, so that should work for my use case as well. I can see where companies that use the same private ASN in multiple places internally within the same tenant could have issues though. It would be nice to have something that would enforce global uniqueness for public ASNs, but allow for applying different restrictions to private ASNs. I'm not sure that hard-coding those values would make sense (maybe a configuration option for a list of excluded ranges that defaults to the RFC-defined ones?), but that would certainly help enforce uniqueness where there has to be uniqueness and allow some flexibility where there doesn't. If we went the exclusion route (there should be an option, like an empty list/tuple or boolean False, that would remove all exclusions, including RFC defaults), then I would propose just leaving it up to the end user to write whatever custom validator they need to enforce their given situation for those excluded values, while the core enforces global uniqueness for the non-excluded values.
