### ISSUE TITLE
Enable change logging for cable terminations

### ISSUE THREAD

**Issue by neuro42** [netbox-community/netbox#11029]
### NetBox version

v3.3.6

### Python version

3.9

### Steps to Reproduce

1. create 2 devices with interfaces (ie: a switch with 50 ports and a server with 4 ports)
2. connect a cable between interfaces on device 1 and device 2
3. edit the cable to change the device 2 end to a different interface
4. look at the changelog generated for the cable port move

### Expected Behavior

The changelog to show that the cable moved from one interface to another

### Observed Behavior

The changelog shows no differences

**Comment by phurrelmann** [comment]
The same happens when a device is deleted that has interfaces connected by cables. One cable endpoint is deleted without any changelog entries. We just had to restore a inadvertently deleted device and finding the affected cables from the wrong deletion wasn't that trivial because of the missing changelog.

**Comment by jeremystretch** [comment]
I'm reclassifying this as a feature request just because we're technically enabling new functionality that was not previously present.

**Comment by jeremystretch** [comment]
This has been implemented in PR #11407.
