### ISSUE TITLE
Add new Role for IP Address

### ISSUE THREAD

**Issue by stovakor** [netbox-community/netbox#11105]
### NetBox version

v3.3.9

### Feature type

Change to existing functionality

### Proposed functionality

Currently there are quite a few 'roles' available to assign to an IP Address. However none of them apply for IP's that are the gateway address for a subnet.

Please add a new **Gateway** role available to assign to IP's.

Existing roles are not able to reflect a Gateway

### Use case

Right now we create an IP address, set the status as active, role to null, and add a description that this IP is the Gateway for a particular subnet.
It would be better to notate this IP's role as a Gateway via the IP role rather than the description.

It would make searching easier, reporting easier, etc.

### Database changes

None

### External dependencies

None

**Comment by apellini** [comment]
In my opinion there are some confusing value but it depends perhaps on flexibility given by the tool.

Because on role you could choice also if it is a FHRP but there is a section regarding also for FHRP.

So it seems redundant. But someone want to indicate that IP is a HSRP but doesn't want to specify HSRP details.

For me FHRP or other is a Type (like protocol) and this is different from role.

If all we agree could we change adding a key type with current choices and in role we could have:

Gateway
Host
VIP

**Comment by stovakor** [comment]
I support also having role be Host. It makes a lot more sense to me, but changing the roles that drastically is likely a breaking change.

**Comment by jeremystretch** [comment]
This proposal has already been raised, discussed, and rejected multiple times. Please search the issues here for relevant conversation.

**Comment by stovakor** [comment]
So I searched and it seems this has been something people have been asking for for 5 years and yet you keep rejecting it over and over again.
If the user base continues to ask for something at what point do you recognize that maybe it's something you should reconsider?
