### ISSUE TITLE
Add cumulated VM Resources to Cluster view

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#11121]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

The cluster view should show a cumulated value for all assigned vm cpu/ram/disk.

### Use case

This is especially helpful for cluster size planning and get a quick overview over all assigned resources.

**Comment by stavr666** [comment]
In order for the developers not to come back to this several times, I would expand the request.
VMs already have base resource values:
![image](https://user-images.githubusercontent.com/84839985/208234693-65b0394b-3b26-47e0-b337-98208f992e3d.png)

It will be logical, that clusters also have same values as "resource pools" (similar to IP ranges/prefixes).
So, cluster view can show both available and assigned resources.


Devices also have CPU and RAM values, but I'd prefer them not be linked, since most of our "clusters" is either cloud resource pools or VMs with containers. So, they have defined resource limits, but have not devices to attach them.
Also, with "site requirement" limitations for clusters still in place, we can't attach devices to our physical clusters (since nodes located on different sites).

**Comment by kkthxbye-code** [comment]
My PR implements the original accepted FR. stavr666's idea would need a new FR as it would require database migrations and API changes to add the new fields, which I don't believe we like to do in patch releases.

**Comment by stavr666** [comment]
> stavr666's idea would need a new FR as it would require database migrations and API change

Sad, but I understand your resource limits.
You're doing great useful tool, keeping in place it's strong general concept 👌

**Comment by abhi1693** [comment]
@kkthxbye-code I saw your PR, but is it possible to ensure that the units use the biggest string, when a value crosses the boundary of TB, it's displayed as 12 TB instead of 12288 GB. It's easier to visualize the summary.

**Comment by jeremystretch** [comment]
> is it possible to ensure that the units use the biggest string, when a value crosses the boundary of TB, it's displayed as 12 TB instead of 12288 GB

@kkthxbye-code maybe we should modify or replicate the `humanize_megabytes()` template filter to work with GB as the base unit to facilitate this?

> It'll also help to get this information on the API as raw values. I'm not sure if that would be considered a new FR.

Any new additions to the REST API would need to be assigned to a future minor release (e.g. v3.5), so you can open a separate FR for the API portion of the work or we can just postpone this FR until v3.5.

**Comment by jeremystretch** [comment]
Figured we can tackle this when we take a closer look at modeling disks for VMs in the future.

**Comment by fixed77** [comment]
I writed Export Template for Virtual Machines. It calculate all used resources of cluster.
```
{% for cluster, items in queryset|groupby("cluster.name")|sort %}
================ HW: {{ cluster|center(30) }} ===============|CPUs| RAM(Mb) |Disk(Gb)

    {% for vm in items %}{{ vm.name|center(60) }}   {{ vm.vcpus|center(5) }}   {{ vm.memory|center(5) }}     {{ vm.disk|center(4) }}
    {% endfor %}
-------------------------------------------------------------------------------------------
Summary (all VMs):                                                 {{ items | sum(attribute='vcpus')|center(5) }}   {{ items | sum(attribute='memory')|center(6) }}    {{ items | sum(attribute='disk')|center(4) }}
Summary (active VMs only):                                         {{ items | selectattr("status", "eq", "active") | sum(attribute='vcpus')|center(5) }}   {{ items | selectattr("status", "eq", "active") | sum(attribute='memory')|center(6) }}    {{ items | selectattr("status", "eq", "active") | sum(attribute='disk')|center(4) }}


{% endfor %}
```

![image](https://user-images.githubusercontent.com/8656458/209767860-7975c865-54c5-48f5-b9e2-4659f00f723f.png)
