### ISSUE TITLE
The word "Tags" is displayed as the German word "Schlagwörter"

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#11240]
### NetBox version

v3.4.1

### Python version

3.9

### Steps to Reproduce

- Navigate to "Devices"
- Click "Configure Table"
- Search for "Tags" => You will see "Schlagwörter" instead

![grafik](https://user-images.githubusercontent.com/20901110/208408419-8d0f1c5f-a942-41fe-94d8-e94606cb7a54.png)

### Expected Behavior

The English term should be displayed.

### Observed Behavior

The German term is displayed.

I couldn't find that Word in the source code but in the venv at venv/lib/python3.9/site-packages/taggit/locale/de/LC_MESSAGES/django.po

Might be an upstream bug in taggit.

**Comment by peteeckel** [comment]
Let me guess: Your system language is set to "German"?

Mine is set to "English" and I see "Tags" as "Tags", not "Schlagwörter". The likely explanation is that django-taggit is localised, while NetBox isn't (yet). There is, however, some code for the localisation of date and time strings, so the language setting from your browser might get passed on to Django and thus to django-taggit.

**Comment by dreng** [comment]
> Let me guess: Your system language is set to "German"?

Obviously, yes. I tested with different Browsers on different Systems (Windows, Android) and different Databases, all with the same result but all systems are German. The thing is, I've never run into that issue so far. Today is the first day I noticed the German word and I swear it hasn't been there before.

That said, it seems to be not a direct NetBox (code) issue, but it is an issue while using NetBox on German systems.

**Comment by kkthxbye-code** [comment]
No need to speculate, it's caused by the fix to this issue: https://github.com/netbox-community/netbox/issues/11189

https://github.com/netbox-community/netbox/commit/2738da2d3985498f5ce1b4aab771f85f9edf2e85

Which was included in 3.4.1. As the Localization middleware was activated, the language is set according to the Accept-Language HTTP header. `USE_I18N` has a default value of True, so because we don't set it, the change activate the translation system.

We should probably disable `USE_I18N`. I posted some related worries about the new localization/translation settings here:

https://github.com/netbox-community/netbox/issues/11189#issuecomment-1356326763

@jeremystretch and/or @arthanson - will have to chime in.

**Comment by jeremystretch** [comment]
This has been resolved for now by disabling translation support (see #11271).
