### ISSUE TITLE
Superuser is not an admin

### ISSUE THREAD

**Issue by jschewebbn** [netbox-community/netbox#11283]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

In 3.1.7 users marked as superuser could use the Admin interface, even if not explicitly listed as staff. In 3.4.1 I found that I needed to make these users staff as well as superusers to edit the Admin interface. 

### Expected Behavior

I expect that superusers would be able to use the admin interface.

### Observed Behavior

Superusers are not able to use the admin interface.

**Comment by kkthxbye-code** [comment]
> In 3.1.7 users marked as superuser could use the Admin interface, even if not explicitly listed as staff.

I cannot replicate this.

> I found that I needed to make these users staff as well as superusers to edit the Admin interface.

That is intended, it's in the documentation here: https://docs.netbox.dev/en/stable/administration/authentication/overview/#local-authentication

> Local user accounts and groups can be created in NetBox under the "Authentication and Authorization" section of the administrative user interface. This interface is available only to users with the "staff" permission enabled.

> I expect that superusers would be able to use the admin interface.

That would be a feature request, but it's very unlikely to happen, both because I think it works fine as is and secondly because it's how django.contrib.admin works:

https://docs.djangoproject.com/en/4.1/ref/contrib/admin/
https://docs.djangoproject.com/en/4.1/ref/contrib/auth/#django.contrib.auth.models.User.is_staff

You could create a feature request to django and ask them to change it

> By default, logging in to the admin requires that the user has the is_staff attribute set to True.

**Comment by jschewebbn** [comment]
OK, thanks for explaining it.
