### ISSUE TITLE
Copy all description fields from the device / module type when creating new instance

### ISSUE THREAD

**Issue by Petrapana** [netbox-community/netbox#11317]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

Hi, I'd found really useful if all the description fields would copy from the device/module type while creating a new device instance / new module instance. Currently all the description fields are left blank and manual propagation of all the description fields has to be done.

### Use case

I am adding the description for some ports, where they are physically located, or what is the speed of specific module. This information is later visible only on the template and not directly on the module instance itself => You have to manually navigate to different place and cannot see this info directly from the device.

**Comment by jeremystretch** [comment]
NetBox intentionally does not do this because it would result in the unnecessary duplication of information. What is true regarding the characteristics of a device type (or module type) must be true for all instances of it, so replicating that information - and especially allowing it to be modified per instance - makes no sense.

Instead, the description fields on device components should contain any information relevant to that specific instance. For example, the description of an interface _template_ might describe its physical location on the device, whereas the description on an interface might note some fault or temporary configuration pertinent to that particular interface and irrelevant to the same interface on some other instance of the device type.

This approach ensures that users can leverage both contexts of description in an efficient, consistent manner. Hope that helps!
