### ISSUE TITLE
Bulk Import Circuit and Terminations

### ISSUE THREAD

**Issue by aslater3** [netbox-community/netbox#11469]
### NetBox version

3.4.2

### Python version

3.8

### Steps to Reproduce

Click Circuits
Click bulk import
The fields for termination_a/z dont appear on the CSV / Field Options on that page
Can't find any documentation around the JSON import functionality for terminations.

### Expected Behavior

{
       "cid": "ID-TEST",
       "provider": "Lumen",
       "type": "DIA",
       "commit_rate": 200000,
       "status":"decommissioned",
       "description": "Testing Import",
        "termination_a": {
                    "site": {
                    "name": "Test Site",
                    "slug": "test-bed"
                },
       "termination_z": {
                    "provider_network": {
                        "id": 1}
}
}
}

Should import circuit with relevant terminations?

### Observed Behavior

Imports the circuit but no terminations are added.

**Comment by aslater3** [comment]
But to confirm, this should work? We are just lacking the documentation?

**Comment by jeremystretch** [comment]
Correct; this was added in NetBox v3.4.0 under #815. You can specify a list of terminations under the `terminations` attribute on each circuit.

**Comment by pehan-dotcom** [comment]
Hello, upgraded netbox from 3.3.5 -> 3.4.5 to get functionality of bulk circuit import with terminations. However, attribute is not show in Field Options: Circuits > Circuits > Import > Circuit Bulk Import > Upload file. When I try to use csv file:

cid,provider,type,status,commit_rate,terminations
3141,testprovider,L2VPN,active,30000,testsite

I get an error:
<class 'AttributeError'>
'str' object has no attribute 'update'

Am I missing something? Thanks.

**Comment by candlerb** [comment]
@pehan-dotcom: As far as I know, this only works with JSON/YAML import (or if it did work for CSV, the "terminations" column would have to be structured data)

@aslater3: After some experimentation, I believe the following should work for you:

```
[

{
"cid": "ID-TEST",
"provider": "Lumen",
"type": "DIA",
"commit_rate": 200000,
"status":"decommissioned",
"description": "Testing Import",
"terminations": [{
  "term_side": "A",
  "site": "Test Site"
}, {
  "term_side": "Z",
  "provider_network": "Blah"
}]
}

]
```

where "Blah" is the _name_ of the provider network with id 1; using `{"id": 1}` doesn't work here.

Note that currently if there is any error in the termination definitions, no error message is displayed and Netbox just returns to the import page - see #12402.

> Imports the circuit but no terminations are added.

That's because "termination_a" and "termination_z" are ignored, presumably as invalid attributes.  (This is different to the REST API, which still *does* return "termination_a" and "termination_z")
