### ISSUE TITLE
Using AzureAD authentication I cannot get the group members for the user that authenticates

### ISSUE THREAD

**Issue by enribla** [netbox-community/netbox#11508]
### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

1. I authenticate using AzureAD with my user
2. I get authenticated
3. I check the user groups in admin with a superuser account
4. I don't see any group even if the user has several groups in AzureAD
5. I check in the user id_token in User social auths (inside the meny PYTHON SOCIAL AUTH) and I verify that I get the group id

### Expected Behavior

The expected behaviour would be to see the member groups related to the user that is authenticated using AzureAD

### Observed Behavior

No groups appeared related to the user.

My configurations related with authentication is:

REMOTE_AUTH_BACKEND = 'social_core.backends.azuread.AzureADOAuth2'

SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

**Comment by candlerb** [comment]
I tried to do it for Keycloak, and it broke things badly. Here's a potted history in case it helps.

In https://github.com/python-social-auth/social-core/pull/668, in an attempt to be helpful I also picked up the "groups" claim and returned it in the user structure from all OIDC responses:

```
    def get_user_details(self, response):
        username_key = self.setting('USERNAME_KEY', default=self.USERNAME_KEY)
        return {
            'username': response.get(username_key),
            'email': response.get('email'),
            'fullname': response.get('name'),
            'first_name': response.get('given_name'),
            'last_name': response.get('family_name'),
            'groups': response.get('groups'),    # <<<<<<<<< returns a list of strings
        }
```

But it turns out that if you do this, Django barfs, and this change had to be rolled back: see https://github.com/python-social-auth/social-core/issues/690 / https://github.com/python-social-auth/social-core/pull/692

The actual error from Django is:

```
Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
```

If you can work out where that's coming from, you may be able to fix this issue.

**Comment by jeremystretch** [comment]
Thanks @candlerb, that's very helpful. I suspected that this sort of change would be necessary so it's nice to have that confirmed.

> If you can work out where that's coming from, you may be able to fix this issue.

I assume that the dictionary of attributes returned by the backend is being applied to the user instance blindly. `groups` would cause an issue because it's a reverse manager (rather than a normal attribute). So I'm not sure how it's working (_if_ it's working) for other backends as you pointed out [here](https://github.com/python-social-auth/social-core/issues/690#issuecomment-1168627022).

**Comment by CTV-2023** [comment]
Hi, just in case that helps, the workaround I found was not using AzureAD but SAML against AzureAD and store groups in SOCIAL_AUTH_SAML_EXTRA_DATA to use them with a custom pipeline. Might be considered as "dirty" (and the code far from perfect)
https://www.reddit.com/r/Netbox/comments/104ouqz/netbox_saml_with_azure_ad_authorization/

**Comment by jeremystretch** [comment]
There's now a feature request to implement this ability natively within `python-social-auth`: https://github.com/python-social-auth/social-core/issues/794

**Comment by BBezaire** [comment]
Hi All,

I noticed PR #13373 was reverted.
Can we reopen this issue, or has discussion moved elsewhere?
