### ISSUE TITLE
IP Range search not working as expected

### ISSUE THREAD

**Issue by zacho112** [netbox-community/netbox#11601]
### NetBox version

v3.4.3

### Python version

3.11

### Steps to Reproduce

1. Log into https://demo.netbox.dev
2. [Go to IP-Ranges](https://demo.netbox.dev/ipam/ip-ranges/)
3. Search for one of the IP ranges, eg. `192.168.1.50`, or simply `192`

### Expected Behavior

All IP ranges with a matching substring of the search shows, kinda like `?q=` works on `ip_addresses`. (It's the same for the API and pynetbox)

### Observed Behavior

No results found.
Search in GUI and `?q=`  does not show any results at all.
`?contains=` seems to work when searching for an IP (with /cidr), and URL encodes the `/`. `192.168.1.66/22` does not work, but `192.168.1.66%2f22` works. But I can't get contains to work via pynetbox.

**Comment by dsobon** [comment]
@zacho112 - do you mean "Quick search" instead of "Search"?
Or do you mean that "192.168.1.66" does not work in "Search"?

Quick search of "192" shows 0 results. 
| --- |
| <img width="663" alt="image" src="https://user-images.githubusercontent.com/1142651/215170342-a4f6c72e-01ac-4ea8-93f9-e0bdde9d9101.png"> |

Quick search of "Future" shows 4 results.
| --- |
| <img width="906" alt="image" src="https://user-images.githubusercontent.com/1142651/215171190-0017de06-261f-49cb-8f25-360ef51aa401.png"> |

"Search" of "192" shows 9 results
| --- |
| <img width="877" alt="image" src="https://user-images.githubusercontent.com/1142651/215171381-e29bef2b-0daa-4e35-82c1-d3f17fa43514.png">
 |

**Comment by zacho112** [comment]
Yes, my bad, quick search it is. Searching for part of ip in the range.
