### ISSUE TITLE
Different buttons in a list when a user is part of more than one group

### ISSUE THREAD

**Issue by papounaise** [netbox-community/netbox#11812]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

In a list, is it possible to have both "can view" and "can change" buttons when a user is a member of several groups and has different permissions depending on the constraints? At the moment, the buttons are all identical but some point to an error page when the user does not have the rights for the selected object.

### Use case

In a list, the user would have for each line the button corresponding to his rights.
![Screen Shot 2023-02-23 at 12 38 36](https://user-images.githubusercontent.com/32987896/220987456-aef4854e-acc8-48c4-b461-015537fdbcdd.png)

**Comment by rmanyari** [comment]
I was able to reproduce this as following:

* Create a dummy user, that's not member of any group
* Create two devices called 1userver and 2userver
* Create two permissions (see screenshot below for details) and assign it to the dummy user.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/1471029/221955000-30040e07-32c5-438e-9add-24f0c9d33370.png">

* Expected behavior: When opening the devices view, only the `1userver` row should have the edit button (yellow pencil).
* Actual behavior: Both rows have the edit button, furthermore, when clicking on the edit button on `2userver`, the UI sends you to an error page (see below).

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/1471029/221955455-c6033e5d-fefe-4eb1-8b29-7c30b6136142.png">

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1471029/221955573-e5590eb3-e00e-49ec-8c78-58336fafe284.png">

I can start poking around, see if we can simply condition the available options based on the permissions.

**Comment by jeremystretch** [comment]
It seems that additional work on the permissions backend is likely needed to facilitate this in a manner that doesn't induce a hue performance penalty.
