### ISSUE TITLE
Hosted OpenAPI documentation

### ISSUE THREAD

**Issue by bcftv** [netbox-community/netbox#11911]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

The OpenAPI documentation on our personal instance is not accessible externally for ingestion into other services like https://github.com/APIs-guru/openapi-directory which is used to allow easy API integration with ServiceNow.

In [Open API Directory Issue 876](https://github.com/APIs-guru/openapi-directory/issues/876) I provided a link to the [API definition on the demo instance](https://netbox.wikimedia.org/api/docs/?format=openapi) which is publicly accessible. 

But this is very slow to respond and times-out when they try to retrieve it.

Is it possible to host the current release API documentation directly in GitHub?

### Use case

The OpenAPI documentation on our personal instance is not accessible externally for ingestion into other services like https://github.com/APIs-guru/openapi-directory which is used to allow easy API integration with ServiceNow.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
The API schema for an individual NetBox deployment will vary depending on its version, what plugins are installed, and (potentially) how it is configured. Thus any centrally published schema will be of limited utility. You can download the schema for your NetBox instance from `/api/docs/?format=openapi` to share with interested parties.

> I provided a link to the [API definition on the demo instance](https://netbox.wikimedia.org/api/docs/?format=openapi) which is publicly accessible.

You appear to have linked to Wikimedia's NetBox deployment. Our public demo instance is at https://demo.netbox.dev.

> But this is very slow to respond and times-out when they try to retrieve it.

The schema is generated upon the first request, and then cached for so that it is immediately available for successive requests.
