### ISSUE TITLE
Missing (sub)parent location of device in the cable trace

### ISSUE THREAD

**Issue by mbalcaen** [netbox-community/netbox#11999]
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

![Screenshot 2023-03-17 12 30 37](https://user-images.githubusercontent.com/1210283/225894037-749edb80-50c7-4c98-9488-f17f3bd74a4a.png)

### Expected Behavior

I have a device VIC-V2-AP-LK in location "Leraarskamer".
"Leraarskamer" is a sublocation of "Floor 0".
"Floor 0" is a sublocation of the parent "Site Vichte V2".

When I do a cable trace I see only "Site Vichte V2" and "Leraarskamer", no sublocation "Floor 0".

### Observed Behavior

Site Viceh V2 / Leeraarskamer.
I would like to see "Site Vichte V2 / Floor 0 / Leraarskamer".

**Comment by jeremystretch** [comment]
This is expected behavior: Only the location to which the device is directly assigned is listed. Otherwise, the text could easily overflow the allotted space. (Consider a scenario with three or four levels of nested locations.)

You're welcome to submit a feature request proposing this change, but it would need to include a solution for handling deep hierarchies.
