### ISSUE TITLE
POST- created devices do not appear in their rack's location's device count.

### ISSUE THREAD

**Issue by dpotter-intoto** [netbox-community/netbox#12074]
### NetBox version

3.4.6

### Python version

3.9

### Steps to Reproduce

1. Identify a rack that is assigned to a location and which has space to contain a new device
2. Browse to the location and note the number of devices present in that location.
3. Use the REST API to create a new device.  (POST `/api/dcim/devices/`).   Assign the device to the rack, but not to the location.
4. Browse to the location again and note that the number of devices has not changed.
5. Edit the rack, changing something minor like a description or serial number.
6. Browse to the location again and note that the number of devices has now incremented to include the new device

### Expected Behavior

I expected the location to include the device count for the new device (via the device-rack-location relationship)

### Observed Behavior

The location does not include the new device in its device-count.

**Comment by dpotter-intoto** [comment]
Comments:

Possibly this is working as intended?  

If I include the location in the POST where I create the device, it is properly included.
If I edit and update the rack that contains the device, the location is also updated.

**Comment by kkthxbye-code** [comment]
No, it's a bug. When creating a device without the location set, but the rack has a location, the following code sets the location:

https://github.com/netbox-community/netbox/blob/96eb89a469b255a209d80555d487b1cdddd6062f/netbox/dcim/models/devices.py#L658-L663

I've verified in the debugger that this also happens when creating the device via. the API, however the location is not present when the object is finally saved. No idea where the bug actually lies though.

**Comment by kkthxbye-code** [comment]
Seems like modifications to the object in the Device.clean() method are not persisted when saving through the API. I tried setting doing the following in the model clean method:

`self.name = "testbloop123"`

When creating a device through the UI, the device is called testbloop123 regardless of name given. When saving through the API, the device is called whatever is passed in the name field. I also tried with the location model, here the modifications done in clear are also ignored when using the REST API.

@jeremystretch do you know what is going on here? Seems pretty bad as we quite often modify the object in the clean method of models.

**Comment by arthanson** [comment]
I think the issue is here: https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/api/serializers/base.py#L41
DRF doesn't call the model clean, NetBox does put it in here but it copies the data then calls clean, so clean only effects the copy of the data, the returned data (which eventually gets saved is never modified).  Probably need a loop to go through the fields after the full_clean call...
