### ISSUE TITLE
Prevent the deletion of interfaces which have children assigned

### ISSUE THREAD

**Issue by MrPaulAR** [netbox-community/netbox#12135]
### NetBox version

v3.4.7

### Feature type

Change to existing functionality

### Proposed functionality

When a parent interface is removed the child interface remains.  There was some discussion in https://github.com/netbox-community/netbox/issues/9359#issuecomment-1127706103 regarding this but I don't think it was ever implemented or an explicit decision to not add this feature.

Initial state
![image](https://user-images.githubusercontent.com/3765696/229233061-cacae47c-657e-4659-8d27-d6365afaf072.png)

After deleting the parent interface
![image](https://user-images.githubusercontent.com/3765696/229233174-3f2b4ebf-0bfa-4ef3-b4a7-7fdc66b91714.png)

The same is true when deleting a module.  The parent interface is remove but the child persists.

### Use case

I'm sure there are exceptions but I would think the child interfaces should be removed whenever the parent is deleted.

### Database changes

I'm not smart enough for this.

**Comment by jsenecal** [comment]
I propose that we change [dcim/models/device_components.py#L485](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models/device_components.py#L485) to `on_delete=models.CASCADE`

And do the same for other similar cases.

**Comment by BarbarossaTM** [comment]
I like this and I think with a confirmation screen which shows all interfaces to be deleted this would be very handy to have.

**Comment by jeremystretch** [comment]
I have to disagree; this seems very dangerous IMO. If the concern is about leaving orphaned interfaces, I'd suggest changing the `on_delete` behavior to `PROTECT`, which will prevent the deletion of the parent interface until all its children have been removed. This ensures that all delete operations are explicit and intentional, mitigating against the unintentional deletion of related objects.

**Comment by jsenecal** [comment]
> I'd suggest changing the `on_delete` behavior to `PROTECT`

I'm good with either, but I do think that the delete confirmation, which tells which other objects are about to be deleted would suffice UI wise. Is your concern more about API behavior ?

**Comment by kkthxbye-code** [comment]
@jsenecal 

> but I do think that the delete confirmation, which tells which other objects are about to be deleted would suffice UI wise.

I agree. Changing it to cascade in combination with this wonderful PR would be a much better solution.

https://github.com/netbox-community/netbox/pull/14089

If I'm understanding it correctly, the suggested solution would require one to go the the interfaces tab and delete all virtual interfaces before deleting an entire device or removing a module. This seems super tedious. Imagine having to remove an entire rack and you have to go to every single device to remove virtual interfaces.

**Comment by jeremystretch** [comment]
@kkthxbye-code as I note [above](https://github.com/netbox-community/netbox/issues/12135#issuecomment-1535315218), the issue with blindly cascading interface deletions is that it can result in inadvertent deletion of child interfaces, which the user might not even be aware exist. #13690 does not offer sufficient protection against this because it is limited to workflows within the user interface.

> In PR #14091 you can delete a device if it doesn't have any virtual interfaces but not if it has any. Seems inconsitent and confusing. Why are child interfaces more important than parent interfaces when deleting an entire device?

That's great feedback. Could you comment on the PR itself please? I'm sure we can work around it to bypass the issue for device/VM deletions.
