### ISSUE TITLE
Module type dropdown lists device types when creating interfaces.

### ISSUE THREAD

**Issue by kalazzawi** [netbox-community/netbox#12212]
### NetBox version

v3.4.7

### Python version

3.10

### Steps to Reproduce

Creating interfaces for modules (Palo Alto PA-5450 firewall chassis)
1. create network card module bay.
2. Add new interface component.
3. Attempt to assign interface to module bay under the Module type dropdown.

### Expected Behavior

See the list of modules for the device.

### Observed Behavior

See a list of devices which is a repeat of Device type dropdown above.
![netbox-bug-report-1](https://user-images.githubusercontent.com/17362831/230723873-70486fc4-0c02-4246-b928-a004cd0c8359.png)

**Comment by kalazzawi** [comment]
I noticed when porting the data from one netbox version to another that there was a new module table.  The device data was duplicated in the module table.  I have since deleted all of the module table entries.  However, I am not seeing how to relate it to a device (chassis).  In my case, we have module bays with (module) cards in a Palo Alto PA-5450.  Is there a feature planned to assign interfaces to (modules) cards and assign (module) cards to module bays with the device (chassis)?

**Comment by kkthxbye-code** [comment]
Your issue is not replicatable with the steps you provided. It also seems like there's a misunderstanding as to how device types and module types function in netbox.

> I noticed when porting the data from one netbox version to another that there was a new module table. The device data was duplicated in the module table.

This is not something netbox has done, if you yourself have modified the database, that would explain your issues.

I would recommend reading the documentation before beginning to use netbox.

https://docs.netbox.dev/en/stable/features/devices-cabling/
https://docs.netbox.dev/en/stable/features/devices-cabling/#module-types-modules
https://docs.netbox.dev/en/stable/models/dcim/module/
https://docs.netbox.dev/en/stable/models/dcim/moduletype/
https://docs.netbox.dev/en/stable/models/dcim/modulebay/
