### ISSUE TITLE
Import device updates

### ISSUE THREAD

**Issue by kalazzawi** [netbox-community/netbox#12214]
### NetBox version

v3.4.7

### Python version

3.10

### Steps to Reproduce

1. importing csv
2. duplicate entry errors

### Expected Behavior

1. export device as csv
2. modify csv
3. import csv
4. View device list with modifications to existing entries

### Observed Behavior

Duplicate entry errors.  No database updates occurred.  Modifying PostgreSQL directly is the only way to perform mass updates.

**Comment by kkthxbye-code** [comment]
This is in no way a satisfactory bug report. There's barely any info to go on. However, as your expected behavior is not actually expected ([see the FAQ](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-cant-i-pass-exported-data-directly-into-the-import-form)) I'm going to close this.

If you feel like you are actually experiencing a bug, please update the issue to follow the template, that is providing full replication steps.
