### ISSUE TITLE
cable connection - data of source will not be applyed

### ISSUE THREAD

**Issue by Ghost108** [netbox-community/netbox#12304]
### NetBox version

3.4.8 (Docker version of Netbox)

### Steps to Reproduce

1. Create a rack and set the values site and location
2. Create 2 devices for this rack (for example patch panels) and set also the values site, location, rack
3. Create Interfaces for each device (for example 12 ethernet ports)
4. Open one device, go to interfaces and click on the button "connect cable" on a port

Now you get the mask for "Add a new cable" which looks like this:
![Screenshot 2023-04-20 103354](https://user-images.githubusercontent.com/17011498/233308623-4f124f6d-db4d-4ed9-b983-36b75c329b03.png)

As you can see,  "A Side" get only the values "Device" and my selected interfaces.
The values for site, location and rack which I set in the device will not be applyed

"B Side" get the values for site and rack.

### Expected Behavior

apple stored values from device to "A Side"

### Observed Behavior

not all values will be applyed

**Comment by jeremystretch** [comment]
The cable creation form has been greatly simplified for the upcoming v3.5 release, now using a powerful object selector widget rather than an array of dropdown fields (largely to eliminate issues such as this):

![create_cable](https://user-images.githubusercontent.com/13487278/233636017-c737f73d-603f-4156-9bb9-5754efc3d25e.png)

As this release is due next week, I don't think it makes sense to spend any effort trying to improve the current form. Thank you for the report though!
