### ISSUE TITLE
"NetboxNews" widget undocumented, enabled by default and uses http.

### ISSUE THREAD

**Issue by joernheissler** [netbox-community/netbox#12376]
### NetBox version

v3.5.0

### Python version

3.9

### Steps to Reproduce

1. Upgrade to NetBox v3.5.0
2. Point the browser to the NetBox installation.

### Expected Behavior

I expect NetBox to:
* not time out.
* not phone home or open any other network connections without being told so.
* not to use http:// (i.e. without TLS) without being asked to.
* document new features such as those.

### Observed Behavior

https://github.com/netbox-community/netbox/commit/e176c7d906fc64cf3c53b589dbf69e839bcc69e9#diff-4a373adccec4fa4e498a96efc552b86d1ba96a39487796c66d32163e36f25279R84 created a NewsFeed widget that appears to be enabled by default. URL is "http://netbox.dev/rss/".

My firewall DROPs outbound requests, causing a huge delay before the NetBox page opens.

---

Please don't enable this widget by default, or if you do, document this and provide instructions on how to disable it.
And please use HTTPs!
Perhaps the code can be changed to load the feed in the background and showing the user a cached result (or error). A network timeout wouldn't then disrupt the user experience.

**Comment by RevLaw** [comment]
Yep, I got the same issue in the Doker image. I was scratching my head why the login is not working. After removing the Widget, all was fine.

For Docker, it would be nice to toggle it with an environment variable.

**Comment by jeremystretch** [comment]
Complaining about intentional, documented changes is not a valid use of a bug report. The time to provide such feedback was during the month-long open beta evaluation period immediately preceding the v3.5 release, in which you unfortunately opted not to participate.

If you'd like to remove the widget from your dashboard, you can easily do so. You also have the option of modifying the default dashboard configuration as detailed in the documentation.
