### ISSUE TITLE
Copy-to-clipboard functionality for IPs

### ISSUE THREAD

**Issue by giezi** [netbox-community/netbox#12499]
### NetBox version

v3.5.0

### Feature type

New functionality

### Proposed functionality

It would be great if there would be a function that when you hover over the IP addresses with the mouse a copy button appears which copies the IP without subnet mask.

Copy button like:

<img width="35" alt="Screenshot 2023-05-05 at 11 27 40" src="https://user-images.githubusercontent.com/1326203/236423092-9142148a-4605-4c91-a485-0ee2debb25d4.png">

### Use case

I think it would be a relief for most users, at the moment you always have to tediously mark the IP and then copy it to connect to a system e.g. via SSH.

### Database changes

-

### External dependencies

-

**Comment by v0tti** [comment]
Copying the IP without the subnet mask seems a bit counter intuitive because it is displayed with a mask in most places of the UI.

But I agree that copying should be improved. I always mark the IP to copy it but sometimes I often to accidentally select a leading tabulator which makes pasting it a pain.

**Comment by jeremystretch** [comment]
We have a copy-to-clipboard button in place elsewhere around the UI (the API tokens list, for instance) that should be suitable for this.

**Comment by abhi1693** [comment]
I can take this up, but which places in the UI is this being intended to be applied?

**Comment by PieterL75** [comment]
I have a plugin that creates a small hamburger to all the links, being able to copy the text out of it (and do much more)
![image](https://github.com/netbox-community/netbox/assets/74899468/9b989c51-3d23-4bb8-be62-dfc53dc99196)
![image](https://github.com/netbox-community/netbox/assets/74899468/fd3efef3-0a59-4c5f-982d-2f261cc656fa)
It opens a lot of flexibility and quick navigations.
The burger is there on all 'links' and not only ip addresses. Would be great if this can become part of the core netbox

**Comment by jeremystretch** [comment]
@abhi1693 I think the intent here is just to display a copy-to-clipboard button wherever an IP address is displayed within the UI, maybe excluding tables.

**Comment by abhi1693** [comment]
@jeremystretch The OP has requested to copy the IP without the mask. If I'm to generalize the copy button, that may complicate things because I have a feeling this code will have to be some sort of hack in the TS script to drop the mask. I would rather leave this on the user to remove the mask after they paste, but just wanted to confirm with you as well.

**Comment by jeremystretch** [comment]
IMO it makes sense to copy the mask as well. I don't see any reason to exclude it.

**Comment by giezi** [comment]
I think the plugin of @PieterL75 should be included as standard in the Netbox - it solves all our problems :)
