### ISSUE TITLE
Custom Scripts added outside of GUI doesn't show up

### ISSUE THREAD

**Issue by K4pper** [netbox-community/netbox#12614]
### NetBox version

v3.5.1

### Python version

3.10

### Steps to Reproduce

1. add custom script to the path **/opt/netbox/netbox/scripts**
2. Log in to Netbox and click **Customization** -> **Scripts**

### Expected Behavior

When adding a custom script to **/opt/netbox/netbox/scripts** it should show up in the Netbox GUI.

### Observed Behavior

When logging in to Netbox and clicking into the Scripts section it says **no scripts found** instead of listing the custom scripts that were installed outside of the GUI.

**Comment by jeremystretch** [comment]
This behavior is intentional. If you would like to propose a change, please do so using the [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) template. However, please note that the ideal time to provide such feedback was during the month-long beta period preceding the v3.5 release, and any substantial changes are unlikely to be considered for immediate implementation at this time.

**Comment by K4pper** [comment]
@jeremystretch Sorry about that, I didn't realize that it was intentional since i didn't spot that change in the patch notes.

I will write a change request about it instead.
