### ISSUE TITLE
Expose more objects in the configuration rendering feature

### ISSUE THREAD

**Issue by MajesticFalcon** [netbox-community/netbox#12814]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

Configuration rendering should expose the route-targets so more advanced configurations can be generated.

### Use case

Unless I am missing something, currently, the implementation of configuration rendering seems to only provide access to the "device" object. Technically, you can loop through the device.interfaces.all() and create a new array of L2vpn terminations, however, I don't believe you can get the route-targets using this method.

### Database changes

None.

### External dependencies

None.

**Comment by jeremystretch** [comment]
Expanded more generally, I think the underlying proposal here is to make NetBox models available directly as context variables when rendering a template. This would enable the template author to do e.g.

```
{% for rt in RouteTarget.objects.all() %}
```

This was a consideration raised during the initial work on the config rendering feature and ultimately punted simply because we weren't sure if it made sense at the time. I don't think there's anything necessarily precluding us from adding this, but would like to leave this open for discussion for a while.

We may also want to consider namespacing the models in some fashion, so that generic models like `Device` and `Site` don't conflict with user-provided context variables. (It may also be necessary to avoid naming collisions among core and plugin models.)

**Comment by MajesticFalcon** [comment]
Sounds good. In the meantime, is there a different method I could to get the RT info usable inside the configuration rendering? The configuration snippet you provided would be great, but I suspect/hope there is a round-a-bout way to get the same information through the device object?

**Comment by MajesticFalcon** [comment]
> Expanded more generally, I think the underlying proposal here is to make NetBox models available directly as context variables when rendering a template. This would enable the template author to do e.g.
> 
> ```
> {% for rt in RouteTarget.objects.all() %}
> ```
> 
> This was a consideration raised during the initial work on the config rendering feature and ultimately punted simply because we weren't sure if it made sense at the time. I don't think there's anything necessarily precluding us from adding this, but would like to leave this open for discussion for a while.
> 
> We may also want to consider namespacing the models in some fashion, so that generic models like `Device` and `Site` don't conflict with user-provided context variables. (It may also be necessary to avoid naming collisions among core and plugin models.)

Sounds good. In the meantime, is there a different method I could to get the RT info usable inside the configuration rendering? The configuration snippet you provided would be great, but I suspect/hope there is a round-a-bout way to get the same information through the device object?

**Comment by DanSheps** [comment]
I am assuming this is for L2VPNs?

Two ways:

* Iterate interfaces, iterate vlans, iterate l2vpn terminations, iterate route targets
* Iterate interfaces, iterate l2vpn terminations, iterate route target

This is because l2vpns can be attached to both a single interface or a vlan.  There is no direct way from devices itself, unfortunately.

**Comment by MajesticFalcon** [comment]
@DanSheps, thank you! I just saw your Slack message as well. Apologies for the duplicate work.

**Comment by ITJamie** [comment]
maybe it would be worth passing in a dummy object which had references to all the classes. eg a "netbox" object or similar, that way it would guarantee no confusion when it comes to the existing device object.
context render would look something like: 
```
{% for rt in netbox.RouteTarget.objects.all() %}
```

**Comment by DanSheps** [comment]
I like that idea, and honestly I thought of roughly the same.

**Comment by ITJamie** [comment]
Maybe "netbox.plugins.classname" work for plugins. It could act as a safety wrapper too incase a context was using a pluginclass that got removed and safely error out/log? (Its actually kind of important that we make sure that works, otherwise some important config could be missing in a deployment config...)

**Comment by do9xe** [comment]
> Expanded more generally, I think the underlying proposal here is to make NetBox models available directly as context variables when rendering a template. This would enable the template author to do e.g.
> 
> ```
> {% for rt in RouteTarget.objects.all() %}
> ```
> 
> This was a consideration raised during the initial work on the config rendering feature and ultimately punted simply because we weren't sure if it made sense at the time. I don't think there's anything necessarily precluding us from adding this, but would like to leave this open for discussion for a while.

I was also just looking into how I could get all the VLANs for a device. In my case I'd like to loop through all the VLANs that match the device and create them in the configuration. If you use dynamic VLAN assignment through 802.1X most devices need the VLANs created before they can be dynamically assigned to a port. Also they don't show in the running-config of the device.

**Comment by jeremystretch** [comment]
IMO it would make sense to expose the models with their native names (e.g. `ConsolePort` rather than `console_port`) in the template context.

**Comment by jeremystretch** [comment]
Thinking about this further, we probably want to incorporate the application name space in the context, to avoid potential future naming conflicts. For example, suppose a plugin introduces its own Site model, which would conflict with the native model.

We could namespace the models to avoid this, e.g. `dcim.Site` instead of `Site`. It breaks from convention a bit but does so to provide a minimally inconvenient solution for potential naming conflicts.

**Comment by abhi1693** [comment]
Would you want a flat structure like `dcim.Site`, `dcim.Rack` or a grouped structure like `{dcim: {Site: ..., Rack: ...}...}`?

**Comment by DanSheps** [comment]
I am for the namespacing.  Seems like a good plan, yes it does deviate but I think it will prevent future isssues.

**Comment by jeremystretch** [comment]
@abhi1693 I think it would need to be nested, in order to access e.g. `dcim.Site.objects.all()` within a Jinja2 template.

**Comment by abhi1693** [comment]
I have added the app namespace to the context data
![image](https://github.com/netbox-community/netbox/assets/5083532/cab76fa5-ffff-4847-ac76-aa89fbf8f26d)

**Comment by Omega-Networks** [comment]
Please consider including the ipam models as well:

ipam.Vlans.objects.all()
ipam.VlanGroups.objects.all()
etc

**Traceback:**
```

Traceback (most recent call last):
  File "/opt/netbox/netbox/dcim/views.py", line 2066, in get_extra_context
    rendered_config = config_template.render(context=context_data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/extras/models/configs.py", line 280, in render
    output = template.render(**_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/netbox/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 37, in top-level template code
  File "/opt/netbox/venv/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'Vlans'
```

**Comment by DanSheps** [comment]
The model is `ipam.VLAN` not `ipam.Vlans`
