### ISSUE TITLE
Add a hide (x) button to the update prompt box

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [netbox-community/netbox#12861]
### NetBox version

docker 2.6.1

### Feature type

New functionality

### Proposed functionality

![2023-06-12_01-19-29_Home  NetBox - Cent Browser](https://github.com/netbox-community/netbox/assets/63704404/1cd0008e-86ae-4133-a6e5-aadbc4654746)

A simple close button like the ones on the widgets

### Use case

As of now, there is no way to get rid of this update prompt, while you can close, add, and rearrange your dashboard. So it'll be really nice if there was a close button for that prompt box, especially for us Netbox Docker users who are always some versions behind the official release.

**Comment by kkthxbye-code** [comment]
I've edited the title, please try to keep it descriptive and not in the form of a question.

> docker 2.6.1

Please specify the netbox version, not the netbox-docker version. It's noted in the footer of your netbox instance.

> As of now, there is no way to get rid of this update prompt

It only shows for admins and it can be disabled by setting [RELEASE_CHECK_URL](https://docs.netbox.dev/en/stable/configuration/miscellaneous/#release_check_url) to None.

Can you please expand on the exact functionality you want? Like what happens when you hide it? Is it hidden for only your user or all users, is it hidden forever or until the next update?

**Comment by frnksmdlkedjnfr** [comment]
Currently I'm running e8f65173609d (v3.5.2).

A more detailed description would be:
1. Add a × button on the top-right corner (dismiss, for this time, but the prompt will show up next time you login)
2. Add a 'Skip this Version' button on the bottom-right corner (ignore this version, but will prompt update for the next version)
3. Add a 'Never Check Update' button on the bottom-right corner (it would be nice if we also had a correspondent 'Check for Updates' check box in the admins' profile page, so we could easily turn this on again)

**Comment by jeremystretch** [comment]
As @kkthxbye-code points out, this can be disabled in the configuration. Adding per-user tracking simply to track state for the notification would not be worthwhile.
