### ISSUE TITLE
Not allowed to create /128 unnumbered or loopback IPv6 address

### ISSUE THREAD

**Issue by Nemavio** [netbox-community/netbox#12921]
### NetBox version

v3.5.3

### Python version

3.11

### Steps to Reproduce

1. Click on "Add" on "IP Addresses"
2. Enter an IPv6 address like 2a0e:FFFF:43::1/128
3. (optional : Assign an interface for this IP)
![image](https://github.com/netbox-community/netbox/assets/4148215/5adb1723-60e8-442b-b758-c1238e5c7d0c)

### Expected Behavior

Like IPv4 address, we can have /128 IPv6 unnumbered IP Address or just classic IPv6 loopback address on router, VM, server... it should not fail.

### Observed Behavior

Got an error : " 2a0e:ffff:43::1/128 is a broadcast address, which may not be assigned to an interface."

**Comment by abhi1693** [comment]
I'm able to create the address without any issue

![image](https://github.com/netbox-community/netbox/assets/5083532/2ea35ca0-f2de-407b-97d0-972127de3fa8)

And, the interface assignment issue was fixed in https://github.com/decoupca/netbox/commit/34f5363a2ef79b817fbfbc8a2e9b42bf414d755e which is yet to be released.

This issue has already been addressed in https://github.com/netbox-community/netbox/issues/12812.

Unless, I'm understanding the issue wrong, I'm going to close this out as duplicate. Feel free to ping me if your issue is different.
