### ISSUE TITLE
Add primary key to global search

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#12936]
### NetBox version

3.5.3

### Feature type

Data model extension

### Proposed functionality

Add the primary key as an additional indexed field to be searched.

### Use case

With the ability to move cables, we are currently using the primary key to track cables.  However, the primary key is currently not searchable.

### Database changes

Add the primary key for each model as a search field

### External dependencies

None

**Comment by martinum4** [comment]
This might also close https://github.com/netbox-community/netbox/issues/12705 if implemented for *all* searches

**Comment by DanSheps** [comment]
I knew I saw it somewhere, thanks for that @martinum4

**Comment by kkthxbye-code** [comment]
Do you mean add the pk to the filtersets or to the global search? Because I don't think it makes sense for the global search.

**Comment by DanSheps** [comment]
To the global search (and filterset too IMO,, I can see both).

**Comment by jeremystretch** [comment]
So searching for e.g. 123 would return all objects with that primary key? I can't imagine that being useful.

**Comment by DanSheps** [comment]
I guess the shorter PK's would cause a problem, especially is searching for an addrerss or similar with the same number sequence.  For example, my PK's for devices are in the 5 digits.  My cables are almost 6 digits now.

Not sure how feasible it is, but perhaps only make it use it as a search key when there is no label/name associated with the item?

**Comment by DanSheps** [comment]
I think like @kkthxbye-code mentioined, #12705 would actually be fixed at the filterset level

**Comment by kkthxbye-code** [comment]
> We could do like I said, put in the label/name or if both are none where it shows the PK then we add that to the search it would be added if it were a label (for example, displaying a cable with PK 343334 it is shown in the UI as "#343334"), so we could add that to the search index as the label.

I really just think that if you choose to not have a label for a cable, or choose not to have a name for a device, it's because it's not inherently searchable and that it is not needed to search for it.

Let's say you stumble upon a cable in the datacenter and you want to see where it goes, wouldn't you search for the label that's on the cable? How do you get the primary key in that case? If there really is no label, wouldn't you follow it to one end and look up what it is connected to instead?

Same with a device, if it doesn't have a name, wouldn't you find it by going to the rack in netbox and looking at the position?

I guess I just don't understand the use case properly, could you explain more about what the actual workflow is here?

**Comment by jsenecal** [comment]
If that helps with the cable primary key use case, I created a little plugin to help with that:
https://github.com/jsenecal/netbox-cable-labels

**Comment by jeremystretch** [comment]
I'm going to close this out as it doesn't seem we've found any real justification for its implementation.
