### ISSUE TITLE
Add support for Molex Power Connectors

### ISSUE THREAD

**Issue by engageant** [netbox-community/netbox#12984]
### NetBox version

v3.5.4

### Feature type

Data model extension

### Proposed functionality

Add **Molex Micro-Fit 2x2** to power port inlet type.

### Use case

Various devices utilize various Molex connectors for power input. For example, Cradlepoint E300 and IBR900-1200M routers and the Cisco 891 router all use a [2x2 Molex Micro-Fit connector](https://www.molex.com/en-us/products/part-detail/2147552042).

### Database changes

None required.

### External dependencies

None.

**Comment by jeremystretch** [comment]
Are these devices connecting directly to a power source via these connectors? Typically Molex connectors are used to connect an external power supply, which itself houses the device's actual power port.

**Comment by DanSheps** [comment]
They are External.  I have used 881's before, it is a stupid connector but it is valid.

**Comment by engageant** [comment]
The Cradlepoints specifically can be [hardwired to a vehicle ](https://cradlepoint.com/product/accessories/gpio-power-cable-rail-safe-2x2-20awg/); the cable in this case just carries direct power and a couple GPIO lines.

**Comment by DanSheps** [comment]
Going to make this available for implementation as it does appear to be able to support direct connection to a DC power source.

Should likely add additional types for other devices (for example, Nexus 9k is typically a Molex Mini-FIT)

**Comment by arcticash** [comment]
Can this feature be reviewed again for implementation, looks like there is already a solution under #13014 

The use case I have is although typically you are right these devices will use an included external power supply to convert from 240vAC -> 48vDC, there is also a use case i have in certain environments such as industrial controls cabinets where they will be connected directly to a 48v power source, using the Molex headers. Not a showstopper but it would be good to model the connector accurately if only for my own sanity, rather than just using the "other" connector type 😄

**Comment by DanSheps** [comment]
Unfortunately no one has volunteered for this.  The linked PR was opened before this issue was considered.

**Comment by arcticash** [comment]
I'd be happy to work on a new PR to implement this, if implementing the new connector types is the way forward

**Comment by abhi1693** [comment]
@arcticash All yours!

**Comment by arcticash** [comment]
Is anyone able to trigger the workflow on the pull request, just noticed that it's still pending :)
