### ISSUE TITLE
Clone a device including the same installed modules

### ISSUE THREAD

**Issue by lucatortiglione** [netbox-community/netbox#12993]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

Hi what about to clone a device including the same installed modules ?

### Use case

It's useful when i have 30 devices with the same installed modules, i don't have to add them 1 by 1

### Database changes

I don't know

### External dependencies

I don't know

**Comment by martinum4** [comment]
(Edited Crosspost from my discussion post https://github.com/netbox-community/netbox/discussions/12957#discussioncomment-6263383)

I don't have the correct words for it, but some kind of "collection"/"set"/"superset" for devicetypes that nests them together with modules and inventory items would be nice.

Example-Problem: You order a lot of two different server configurations (but same base model) from one vendor, one contains better PSUs (Tracked in NetBox as Module) and accelerator cards (which you want to track as inventory item since they cost you quite a lot).

You then would create two "sets", one containing the basic server and normal PSUs and some kind of order-identifier and the other contains the base server, a different order-identifier, the better PSUs and your accelerator cards.

Rest of the process when importing a device works just as normal, but instead of selecting the base-server devicetype and populating them afterwards you get to select the new collections instead, after import all the modules and inventory items will be included automatically.

**Comment by abhi1693** [comment]
This does not sound like a good idea as you would also replicate the serial numbers and asset tags. Both these fields will duplicate the data and increase the effort to fix these after the cloning is finished.

**Comment by lucatortiglione** [comment]
> This does not sound like a good idea as you would also replicate the serial numbers and asset tags. Both these fields will duplicate the data and increase the effort to fix these after the cloning is finished.




> This does not sound like a good idea as you would also replicate the serial numbers and asset tags. Both these fields will duplicate the data and increase the effort to fix these after the cloning is finished.


Maybe the programmers can avoid duplicating serial number field :)

**Comment by laimaretto** [comment]
This would definitively a very good feature.

**Comment by marcusyuri** [comment]
I think that it was a wonderfull ideia, and may be implemented using the following steps:

(1) Clone the device, except the serial numbers / asset tags
(2) Clone the inventory itens attached to the device,  except the serial numbers / asset tags
(3) Populate the new device with the same module types that the original device. Note that this will not fetch the serial/asset tags
(4) Clone the inventory itens attached to the original modules, except the serial numbers / asset tags, and assign them to the new created modules.

;)

**Comment by jeremystretch** [comment]
It sounds like there's some interest in the general idea, however this issue does not come close to embodying an actionable feature request, so I'm going to close is out. If anyone would like to spend some time drafting a detailed implementation proposal, you are welcome to present it for consideration in a new issue.
