### ISSUE TITLE
CSV import: add support for alternate separators

### ISSUE THREAD

**Issue by saerdnaer** [netbox-community/netbox#13239]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

- Currently the CSV import only supports `,` as field seperator – it would really help if it would support `;` and `\t` aka `	`, too.

### Use case

* copy&paste tables from spreadsheet software to the import text-area of the web UI, 
* import CSV files create with Numbers, etc.

**Comment by andershagman** [comment]
This would help a lot. `;` is used by Excel in many European countries. If you save in csv format in France or Sweden, Excel will use `;`.

**Comment by abhi1693** [comment]
From your description, I just want to point out that `\t` is used for tsv files. Although they are not so different but I'm not sure if that'll be in scope for the change here

**Comment by pv2b** [comment]
> From your description, I just want to point out that `\t` is used for tsv files. Although they are not so different but I'm not sure if that'll be in scope for the change here

I believe that'll be in the scope of the change here, because one of the quoted use cases:

> copy&paste tables from spreadsheet software to the import text-area of the web UI,

To expand a little on this, when you want to prepare some bulk data for import, it's often convenient to use something like Microsoft Excel to prepare the data. Often these documents are pure "scratch pads" to arrange the data in the right way prior to import. When you copy data out of Excel, and paste it into a text form such as the Netbox bulk import field, the data ends up being tab-separated.

To be able to support this usecase as accepted therefore tab-separated values will need to be included.

It makes perfect sense to implement this as part of the CSV functionality, most libraries such as the [csv library in Python](https://docs.python.org/3/library/csv.html) as well as the [Import-Csv](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-7.3]) and [Export-Csv](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7.3] both support using the tab character as my delimiter.

In fact my current workflow is basically creating tables in Excel, and then using this PowerShell oneliner to convert TSV into CSV:

```powershell
Get-Clipboard | ConvertFrom-Csv -Delimiter "`t" | ConvertTo-Csv -Delimiter "," -NoTypeInformation
```

Again demonstrating that treating TSV as a dialect of CSV is common. :-)

**Comment by abhi1693** [comment]
@pv2b I did already include a tab in the implementation. Could test your use cases with https://github.com/netbox-community/netbox/pull/13563 to make sure this works for you?

**Comment by pv2b** [comment]
> @pv2b I did already include a tab in the implementation. Could test your use cases with #13563 to make sure this works for you?

It works when picking the delimiter manually. However autodetect doesn't seem to work for tab-separated files! It's not a big deal, but it would be nice if tab-seperated files were autodetected.

**Comment by abhi1693** [comment]
It's not possible to add a tab delimiter to the auto-detect due to the limitations of the sniff function. It can only work with a single character delimiter whereas the tab uses 2 characters.

**Comment by pv2b** [comment]
> It's not possible to add a tab delimiter to the auto-detect due to the limitations of the sniff function. It can only work with a single character delimiter whereas the tab uses 2 characters.

Tab is a single character, not two characters

**Comment by abhi1693** [comment]
tab requires `\t` which is considered two characters by the sniff function internals

**Comment by kkthxbye-code** [comment]
> tab requires \t which is considered two characters by the sniff function internals

I'll link my response here again:

https://github.com/netbox-community/netbox/pull/13563#discussion_r1306049317
