### ISSUE TITLE
Increase Tenant and Tenant Group name field lengths

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#13316]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

Increase the length of the `name` field on `Tenant` and `Tenant Group` models.

### Use case

We provide services to municipalities in Sweden and some of these buy shared resources together, example, Municipality A, Municipality B and Municipality C buy a single resource which they share. Our Tenant name ends up being "Municipality A, Municipality B and Municipality C".

Sometimes a shorter name exists and thus solves the issue, but many times such a name doesn't exist and we end up with truncated names.

### Database changes

Increase `max_length` on `name` field on models `Tenant` and `Tenant Group`.

### External dependencies

None

**Comment by hagbarddenstore** [comment]
I can implement the change if accepted.

**Comment by jeremystretch** [comment]
> Our Tenant name ends up being "Municipality A, Municipality B and Municipality C".

This is a textbook example of misusing a relational model, and a great example of why the field length limits exist. You're attempting to use an object intended to represent a _single_ entity to represent multiple entities, rather than creating a discrete object for each. A single field will _never_ be long enough to fit this model. (What if you needed to assign a dozen municipalities? A hundred?)

Tenants in NetBox are meant to represent ownership of rather than dependency on individual resources, which is why only one tenant may be assigned per object. Your use case would be better served by a multi-object custom field, or even a custom plugin to track dependencies among objects.
