### ISSUE TITLE
Maybe add a blurb about escape characters?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [netbox-community/netbox#13390]
### Change Type

Addition

### Area

Configuration

### Proposed Changes

Just spent a few hours researching/reconfiguring/restarting things because I was receiving `Caught LDAPError while authenticating: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839'})` from LDAP debug logs.

Fix ended up being escaping a "\\" in the binding account's password. So, if the password was "Pass123\\", it would actually have to be plugged into the AUTH_LDAP_BIND_PASSWORD field as "Pass123\\**\\**".

Am requesting a note or something to be added in the [LDAP Configuration](https://docs.netbox.dev/en/stable/installation/6-ldap/) page to save others this time.

P.S. Funny enough, had to apply same principle to this post for the slashes to actually show...

**Comment by jeremystretch** [comment]
While I can appreciate your frustration, we must be careful to avoid scope creep in our documentation. We necessarily assume some level of familiarity on the part of the reader with syntax; otherwise, we'd be repeating _quite a lot_ of fundamental concepts across many pages of documentation. This would become not only burdensome to maintain, but to read as well.
