### ISSUE TITLE
api token page - unable to see generated token key after creation (if no key supplied)

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13434]
### NetBox version

v3.6-beta1

### Python version

3.10

### Steps to Reproduce

goto admin > api tokens > add api token
select a user,
do not fill in the key field (key will be autogenerated)
after creation there is no way to see/copy the generated key

### Expected Behavior

the generated key should be visible after creation
also maybe admins should be able to view full keys?

### Observed Behavior

unable to copy / see the generated API key

**Comment by jeremystretch** [comment]
@jsenecal suggested reworking the forms a bit so that the token value is generated when the form is rendered, providing the user an opportunity to record it _prior_ to creating the token in the database. I really like this approach because it obviates the need to introduce any complex logic in the views, which now utilize the generic ObjectEdtiView.

**Comment by ITJamie** [comment]
so the field would be prefilled and new validation to require a value to be supplied (and potentially make sure it has a minimum amount of characters and isn't something silly like "password")?

**Comment by jeremystretch** [comment]
It means the form field will be pre-populated. No changes to validation are needed, other than the field now being marked as required.
