### ISSUE TITLE
Device type sort by alphabetic order

### ISSUE THREAD

**Issue by mikygee** [netbox-community/netbox#13454]
### NetBox version

v3.4.8

### Python version

3.8

### Steps to Reproduce

Hello,

When I edit a device and try to choose the device type they are not sorted in alphabetic order.
The should be sorted.

![image](https://github.com/netbox-community/netbox/assets/2222550/f19a6a46-7f6d-435a-a9f4-d5fb9af51b65)

### Expected Behavior

Sorted in alphabetic order

### Observed Behavior

Not sorted in alphabetic order

**Comment by mikygee** [comment]
I've tried it on the netbox demo website which is running 3.5.7 at the moment and it's the same behavior
![image](https://github.com/netbox-community/netbox/assets/2222550/ab75b956-59c8-45d0-82b5-a8723d0bb1d9)

**Comment by jeremystretch** [comment]
Device types are sorted alphabetically first by manufacturer and then by model. The behavior demonstrated in your second screenshot is expected, because the list is not being filtered by manufacturer.

If you'd like to propose altering this ordering, you're welcome to do so by submitting a feature request, but please note that this would be considered a breaking change as it alters the current behavior in both the UI and REST API.
