### ISSUE TITLE
Cable import dependence by "site

### ISSUE THREAD

**Issue by Bottman99** [netbox-community/netbox#13526]
### NetBox version

v3.5.8

### Feature type

Change to existing functionality

### Proposed functionality

Add a mandatory field "site" for the cable import. 

### Use case

The cable import does not check for the site and is unfortunately not possible in a multisite environment if the names of the end devices are identical in the sites.

### Database changes

A "site" query must be made before the a_ & b_ terminations are queried at the a_&b_ devices.

**Comment by Bottman99** [comment]
@kkthxbye-code
To be honest, I don't know what else to add. 
The excerpt of the error message from you is correct.
Did you see my post before?

Workaround at the moment is to rename all end devices in a "site" and after the cable export do the same again in reverse. This is a very impractical thing to do.

**Comment by jeremystretch** [comment]
@Bottman99 please put some more effort into your proposal above. What _specifically_ are you suggesting be added? A single `site` column wouldn't make sense: What if either end of the cable is in a different site? Presumably you mean to add a site column for each end?

But even that wouldn't be sufficient. What about tenant assignment? NetBox permits duplicate device names per site if each device is assigned to a different tenant. Should the proposal include two columns for tenant assignment as well?

> Add a mandatory field "site" for the cable import.

That would be awfully burdensome for the vast majority of cases where duplicate device names are not a concern. At most, these would be optional fields.

FWIW, you can work around this limitation by specifying the numeric ID for each device instead of its name, by altering the device column name from e.g. `side_a_device` to `side_a_device.id`. This ensures that each device is always uniquely identified.

**Comment by Bottman99** [comment]
@jeremystretch
we have a stand alone system mapped into Netbox, which also has no connection to the outside world, neither to other sites. 
An approximate/simplified copy of this system (therefore the same names, as the project is the same) in the same Netbox represents the reference system in another site. 
The sites are assigned to a different tenant. But the device and rack names etc. are the same. 
If you now want to import cable lists for one of the two sites, an error message is presented, as there is no query as to "which site_a or site_b or which tenant the devices belong to". 

We will never connect the two sites to each other.
Unfortunately, the devices must/should have the same name in both sites for allocation reasons in SAP. 

The idea was to add a relevant field to the import cables which pre-filters by tenant if necessary. If other Netbox users want to connect the site with Tenent_a to another site, this should of course still work. We would then pass 2x the same tenant, others would then specify two different ones for each device in which site_tenant is also assigned.
