### ISSUE TITLE
Device Templates: Description not carried over to device

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#13540]
### NetBox version

v3.5.8

### Python version

3.8

### Steps to Reproduce

Create a Device Template and Add A description 

![Screenshot 2023-08-23 at 15 43 03](https://github.com/netbox-community/netbox/assets/50723251/bee40cb5-643b-413c-a072-1aebcdfbb86a)

### Expected Behavior

Descriptions from the template should be present on the device

![Screenshot 2023-08-23 at 15 43 13](https://github.com/netbox-community/netbox/assets/50723251/5fe78011-c8e9-451e-b019-76f397da2fdd)

### Observed Behavior

The Descriptions never made it to the final device. In this case the lanes are used to build my ZTP config, so this is pretty important info. 

Also, the eth0 already existed on the device, so I don't think that description would have worked, like the rest of the interfaces shown.

**Comment by jeremystretch** [comment]
This behavior is intentional. The description field on an interface template (which belongs to a device type) serves to convey any noteworthy details about the interface in general, whereas the the description of an actual device interface is relevant to that specific instance and will vary from one device to another. It would not make sense to replicate descriptions from the interface templates because it would result in unnecessary duplication of information.

**Comment by bitcollector1** [comment]
I guess it could serve some purpose, outside of my use case, but it just adds confusion IMHO.

**Comment by bitcollector1** [comment]
Also, it would be great to have these "lanes" defined somewhere in NetBox since it's a characteristic of the port and needed for configuration purposes.

**Comment by bitcollector1** [comment]
I went with custom fields for the lanes and it works better than the description, so thanks for nudging me into a better solution :)
