### ISSUE TITLE
2-Post Rack: Everything should consume front / rear

### ISSUE THREAD

**Issue by bradley-rose** [netbox-community/netbox#13555]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

My organization has a number of 2-post racks. These is an option to include in NetBox, but I expected the 2-post designation to immediately consume a front *and* rear rack unit for every device that's installed in it because they're just 2 posts — there's no concept of depth in a 2-post rack. 

Currently, only devices listed as "full-depth" in the device-type classification consume a front and rear slot. I would expect this behaviour on a 4-post rack, but not a 2.

### Use case

2-post racks have no concept of depth, only height units.

**Comment by pv2b** [comment]
Would it not make more sense to not display a rear view at all for 2-post racks? Or perhaps, if you're referring to the "elevations" view, to always display the front of the rack irrespective of the setting? Is it even possible to install something on the rear face of a 2-post rack? In that case that might be a bug.

As for the concept of a 2-post rack not having depth, I disagree. It's common to find 2-posts racks mounted fairly close to a wall, so that larger devices such as servers or 48-port PoE switches cannot fit in those. So, specifying a maximum depth for a 2-post rack to clarify that larger devices will not fit into the rack is a useful feature.

**Comment by bradley-rose** [comment]
Agree, removing the rear view entirely would also satisfy, though it wouldn't allow for a reverse-installed device this way (installing a device with the rear facing forward). As for depth, I haven't seen those types of installations before, but I'm sure they exist so you you have a point.

**Comment by sleepinggenius2** [comment]
I agree that it would be really nice to have devices occupy both the front and rear of a 2-post rack. As those are most of what we have installed, we've ended up having to mark most of our devices as full-depth in order to get around this issue, which has ended up causing some issues in other places.

As for eliminating the rear view entirely, that would be a problem for us, as we have a number of places where equipment is mounted such that the "front" of the device is facing the "rear" of the rack. We've done this to simplify cabling in some scenarios, as well as being able to handle equipment with the incorrect airflow for our hot and cold aisles. It would be confusing to a technician to see the wrong device face showing in the wrong rack elevation.

**Comment by eronlloyd** [comment]
For 2-post racks, you can still have cable management installed on either (or both) sides, necessitating the ability to specify.

**Comment by bradley-rose** [comment]
> For 2-post racks, you can still have cable management installed on either (or both) sides, necessitating the ability to specify.

I only partially agree.

Even still, installing a forward-facing or rear-facing cable management unit would still consume the entire rack unit. You couldn't rack a forward- and rear-facing cable management unit in the same U.

I understand the potential need to specify the direction of its face, but for all intents and purposes, that U is still consumed. I'm not certain that it's even vital to specify the direction of cable management face. I don't currently specify which way they face in my racks; they're just blanks to consume the rack U labeled "1U Cable Management" or "2U Cable Management" classified under a "Rack Furniture" role.

**Comment by eronlloyd** [comment]
I can't think of a hard use case to counter your point, but [many cable managers are single sided](https://www.fs.com/products/29038.html), and because most racks have front and rear mounting holes, it could be possible to use one side for data cable management and the other for power cable management or another edge case. For that reason I'd prefer to maintain the ability to specify direction.

Perhaps an option for "Both" in the Rack Face field could be a compromise?
