### ISSUE TITLE
Add Tenant to Service Model

### ISSUE THREAD

**Issue by bencorrado** [netbox-community/netbox#13668]
### NetBox version

v3.6.0

### Feature type

New functionality

### Proposed functionality

I would like to see the ability to assign Services in Netbox to a tenant.

- Add Tenancy.Tenant to IPAM.Service model.
- Add Tenancy filter option for IPAM.Service in list view.
- Add link and badge for number of services in tenant detail view.

### Use case

When a service is running on a VM or device and the service is owned by a different tenant than owns the VM or device.  

Ideally ownership could be claimed on a Service level to able to track ownership of the services up to the tenant and see all of the services they own listed in the Tenant detail view. 

### Database changes

Unknown

### External dependencies

None

**Comment by pv2b** [comment]
Hi!

You can already acheive this in NetBox without any changes to core NetBox.

> Add Tenancy.Tenant to IPAM.Service model.

You can do this by creating a custom field for Tenant on the service.

> Add Tenancy filter option for IPAM.Service in list view.

Filter options for custom fields are automatically added when you add a custom field.

> Add link and badge for number of services in tenant detail view.

Half of this is easilly doable using a custom link!

Just create a custom link attached to the tenant model with the Link URL set to:

```jinja2
/ipam/services/?cf_Tenant={{ object.id }}
```

(If your custom field isn't named Tenant, change the sample accordingly.)

You won't get a badge showing how many services there are, but that might also be sort of doable because the Link Text is also templated using Jinja2, you might be able to do a query to populate this information, but since that'd take more than about 5 minutes for me to figure out, I'll leave that for you to play with if you find it important. :-)

**Comment by bencorrado** [comment]
> Hi!
> 
> You can already acheive this in NetBox without any changes to core NetBox.
> 
> > Add Tenancy.Tenant to IPAM.Service model.
> 
> You can do this by creating a custom field for Tenant on the service.
> 
> > Add Tenancy filter option for IPAM.Service in list view.
> 
> Filter options for custom fields are automatically added when you add a custom field.
> 
> > Add link and badge for number of services in tenant detail view.
> 
> Half of this is easilly doable using a custom link!
> 
> Just create a custom link attached to the tenant model with the Link URL set to:
> 
> ```
> /ipam/services/?cf_Tenant={{ object.id }}
> ```
> 
> (If your custom field isn't named Tenant, change the sample accordingly.)
> 
> You won't get a badge showing how many services there are, but that might also be sort of doable because the Link Text is also templated using Jinja2, you might be able to do a query to populate this information, but since that'd take more than about 5 minutes for me to figure out, I'll leave that for you to play with if you find it important. :-)

Thanks for the suggestion.  I am currently doing this, it works, but it is certainly not as clean as natively assigning the tenant.
