### ISSUE TITLE
Rack View shows Virtual Chassis name instead of member name

### ISSUE THREAD

**Issue by shepherdjay** [netbox-community/netbox#13725]
### NetBox version

v3.6.1

### Python version

3.8

### Steps to Reproduce

Can be replicated quickly in demo version via these steps.

1. Create a virtual chassis `dmi-sw-vc`
2. Assign two member switches `dmi01-buffalo-sw01` and `dmi01-camden-sw01`
3. Navigate to Racks > DM-Buffalo > Comms closet

For full reproduction create a site, rack, and member devices as a prerequisite to these steps.

### Expected Behavior

Rack view should show the name of the member device

### Observed Behavior

Rack view shows <virtual_chassis>:<member_position>

**Comment by jeremystretch** [comment]
This is functioning as designed: Display of the member's VC and position was an intentional decision when the SVG rendering feature was introduced, as you can see here:

https://github.com/netbox-community/netbox/blob/a8a36c0a8fa39250792abeb493ed3065bf0d9fdc/netbox/dcim/svg/racks.py#L32-L33

As such, it can not be modified without justification. If you'd like to propose changing the displayed text, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) including justification for discussion.
