### ISSUE TITLE
Editing Module's ModuleBay assignment doens't affect module's components

### ISSUE THREAD

**Issue by francesco-noc** [netbox-community/netbox#13819]
### NetBox version

v3.6.1

### Python version

3.11

### Steps to Reproduce

0) Create a Device instance of a DeviceType with more than one equal ModuleBay (e.g. HPE Aruba 2930M-48G-POE+).
1) Create a Module instance of a ModuleType with components whose name include {module} (e.g. Aruba X372 1050W AC Power Supply).
2) Create a second Module instance of a ModuleType with components whose name include {module} (e.g. Aruba X372 1050W AC Power Supply).
3) Delete first Module instance.
4) Edit second Module changing associated ModuleBay from second to first.

### Expected Behavior

The Module's component name changes according to ModuleBay position.

e.g. Power Port name changes from PS 2 to PS 1.

### Observed Behavior

The Module's component name doesn't change according to ModuleBay position.

**Comment by jeremystretch** [comment]
This is expected behavior. Component names are derived automatically only upon creation; there is no logic in NetBox to rename components retroactively, as this could be dangerous. However, you're welcome to submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) if you'd like to write up a proposal.

**Comment by francesco-noc** [comment]
Thanks for the quick reply. I have thought of a real case where the position of a module is changed and therefore the names of the associated interfaces or power ports should change accordingly. Perhaps I only have this case in mind and not others, so why could this be dangerous? What problem could occur? I ask this to consider writing a proposal. Thanks again.
