### ISSUE TITLE
No Scripts Found for non superusers

### ISSUE THREAD

**Issue by enribla** [netbox-community/netbox#13815]
### NetBox version

v3.6.1

### Python version

3.9

### Steps to Reproduce

1. Upload script in the scripts repository
2. Login as Active user (not superuser) with "extras | script and extras | script module" actions set to run, view.
3. Select Customization > Scripts
![image](https://github.com/netbox-community/netbox/assets/53942090/e45e9c4b-1e59-416a-b625-517314706d31)
4. with a superuser we can see the scripts
![image](https://github.com/netbox-community/netbox/assets/53942090/a65e7c15-0ff7-4cd8-8458-fb58a595cae7)

### Expected Behavior

Be able to see the scripts stored on the server

### Observed Behavior

Page reports "No Scripts Found"

This issue was reported in a previous version (v3.5.1) but it seems it was fixed enabling extras script module (see issue #12516)

**Comment by arthanson** [comment]
This is caused because it is checking for core->managedfile view permission, setting this allows the user to view the scripts.  Looks like you currently need all of:
```
Extras > Script
Extras > ScriptModule
Core > ManagedFile
```
Question is - should this be a documentation issue to add this perm, or should it not be checking this perm and consolidated down to less permissions.  Technically it seems like ManagedFile is correct and should be documented, but open for discussion.

**Comment by enribla** [comment]
Thanks Arthason.
For the main public it would be helpfull to document the necessary permissions. It is not very intuitive if you don't deep into the code 
Thanks again!

**Comment by jeremystretch** [comment]
Reclassified this as a documentation change.
