### ISSUE TITLE
Bookmark delete button text change

### ISSUE THREAD

**Issue by HamagenCZE** [netbox-community/netbox#13842]
### NetBox version

v3.6.2

### Feature type

Change to existing functionality

### Proposed functionality

I suggest changing the notification window when the Delete button is pressed in /user/bookmarks/ for the object.

At the moment the text is "Are you sure you want to delete #OBJECT NAME#?: Which evokes the feeling that the entire object will be deleted and not the bookmark itself.

I suggest changing the text to ""Are you sure you want to delete your bookmark for #OBJECT NAME#?"

### Use case

My colleague and I, who manage Netbox, both had the same feeling that the button would delete the entire object instead of the bookmark. We were forced to make a dummy object, bookmark it and then test the button to be sure. This change, I think, will help the clarity of the button.

**Comment by ITJamie** [comment]
Related to https://github.com/netbox-community/netbox/issues/13690

**Comment by abhi1693** [comment]
@ITJamie could you please explain how it's related? I don't see any relation. This FR is simply asking for a delete message update whereas yours is changing how the delete works by showing related objects.

**Comment by ITJamie** [comment]
See the screenshots i added in that fr. It shows exactly what would be deleted including the primay object itself. 

If you were deleting just a bookmark it would say "bookmark - bookmark name" in the list of items that would be deleted

**Comment by HamagenCZE** [comment]
I dont see a relation too. You are talking about normal delate behavior and about object deletion and relative links to that object, my propose was only for changing of text to clarify function of a bin icon in Bookmarks list which is not a object deletion at all

**Comment by ITJamie** [comment]
Sorry for the delay I was on vacation.
The initial version of a branch I made for listing objects that would be deleted included the primary item. 

My view was that the delete modal right now does not give enough details and that this issue is related heavily to the other issue.

I do think it's odd that the `{{ object_type }}` isn't rendering for bookmark objects though...

here is a screenshot of what the output of the delete form would look like with my current dev branch
<img width="571" alt="Screenshot 2023-09-29 at 21 21 02" src="https://github.com/netbox-community/netbox/assets/1613241/1590db50-9bc5-4f5c-b3f6-025f0e265520">

The text etc could be re-worked but I'm of the view that the delete modal needs to present as much information as possible

**Comment by ITJamie** [comment]
I found the reason as to why `{{ object_type }}` doesn't show on the delete page for bookmarks.
The following commit would solve it. https://github.com/netbox-community/netbox/commit/3d9a2526579c6ee88beb957b5de040d66953386f

the htmx render call has the `object_type` variable set but the non-htmx render call does not
