### ISSUE TITLE
Bulk import - file upload flashes and does not import with no visible error

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#13872]
### NetBox version

v3.6.2

### Python version

3.8

### Steps to Reproduce

Given data:
site named import-test
rack named import-rack in site import-test
device role named import-role
manufacturer named import-manufacturer
device-type named import-device with manufacturer of import-manufacturer

CSV data:
```
name,role,serial,description,manufacturer,device_type,airflow,status,site,location,rack,position,face
,import-role,3412341,,import-manufacturer,import-device,front-to-rear,active,import-test,,import-rack,,
,import-role,kljadf123,,import-manufacturer,import-device,front-to-rear,active,import-test,,import-rack,,
```

Devices -> Devices -> Import -> upload file
select file (csv above) or working CSV from [#13871](https://github.com/netbox-community/netbox/issues/13871)
Submit.

### Expected Behavior

Devices to be imported or error display indicating issue.

### Observed Behavior

Neither the working or non-working CSV from other bug do anything except for minor screen flash.

**Comment by abhi1693** [comment]
Why create a duplicate bug of #13871?

**Comment by jeremystretch** [comment]
@ekrichbaum if this is different from #13871, please rewrite it as a standalone bug report.

**Comment by uppsju** [comment]
I have seen similar behaviour.
Netbox version: 3.6.2
Python version: 3.11.2

### Steps to reproduce:
On the Virtualization --> Virtual Machines tab, go to Import, Upload File.
Choose CSV file created in Notepad++ containing the following data
`name,status,role,site,cluster,device,tenant,platform,vcpus,memory
`
`
test-system,active,,europe-west3,,,Test,,2,8192
`
Set Format to Auto-detect or CSV, click on Submit. 

### Expected behaviour
A virtual machine named "test-system" is created, set to status "active", in site "europe-west3", in tenant "Test", with 2 VCPU and 8GB of memory.

### Observed behaviour
The screen briefly flashes, no system is imported.

### Notes
If the contents of the CSV is pasted into the Data box under Direct Import, no errors are displayed and the system is imported.

**Comment by ekrichbaum** [comment]
Sorry.  Wasn't a duplicate.  In the other bug, it occured from using the default paste of CSV data and actually displayed and error (though incorrect as to the issue).  In this one, it is the file upload tab that fails with no visible error, just a screen flash, and no operation.  I just used the same data and and base elements as my test subjects.

**Comment by ekrichbaum** [comment]
confirmed on 3.6.3.  The other bug with location is fixed and unrelated to this upload bug.  Other upload types of features like images do work.
