### ISSUE TITLE
Add location to power feeds

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#13901]
### NetBox version

v3.6.2

### Feature type

Data model extension

### Proposed functionality

I propose to add a field "location" to power feeds.

### Use case

Since power feeds are physical devices in a physical environment, it is a logical consequence to relate them to a location (like devices, power panels, racks etc).

### Database changes

New foreign key field is needed for the power feed model.

**Comment by cpmills1975** [comment]
PowerFeeds can already be located in a rack. I guess it makes sense that a feed could exist outside of a rack, but if in a rack, the location is presumably derivable from that?

If a rack is defined, the location should be unset in order to prevent issues if a rack location is updated. But if no rack is defined, perhaps the feed could reference a location?

**Comment by dreng** [comment]
> PowerFeeds can already be located in a rack. I guess it makes sense that a feed could exist outside of a rack, but if in a rack, the location is presumably derivable from that?
> 
> If a rack is defined, the location should be unset in order to prevent issues if a rack location is updated. But if no rack is defined, perhaps the feed could reference a location?

This is a very common scenario, e.g. with devices. So this is just a copy/paste of an already implemented idea.
