### ISSUE TITLE
Global Search shows IP Addresses in created order, not ascending order.

### ISSUE THREAD

**Issue by jjenjysk** [netbox-community/netbox#13940]
### NetBox version

v3.6.3

### Python version

3.11

### Steps to Reproduce

1. Create IP Address objects in the following order: 10.0.0.20/24, 10.0.0.21/24, 10.0.0.1/24
2. Search for 10.0.0 with global search

### Expected Behavior

All IPs matching show up in ascending order (similar to IP Addresses tab). 

### Observed Behavior

All IPs were shown in created order.

![image](https://github.com/netbox-community/netbox/assets/142209194/2063690c-e066-441d-bed0-20f9b87b1913)

**Comment by PieterL75** [comment]
This is actually the case for all kind of models. I observed the same for the device, sites, ....

**Comment by jeremystretch** [comment]
> All IPs matching show up in ascending order (similar to IP Addresses tab).

While I certainly understand your expectation, IMO it's a bit of a gray area to treat this a bug. Search results are intentionally ordered first by precedence (weight), then by object type, and finally by object ID:

```python
class CachedValue:
    class Meta:
        ordering = ('weight', 'object_type', 'object_id')
```

This is because 1) the ordering of values among matching results does not imply stronger or weaker relevance to the query, and 2) it's likely there are cases where sorting by raw value may result in unexpected ordering (though I can't think of any at the moment). I'd be open to treating this as a feature request if we give the later point a bit more consideration.

**Comment by jeremystretch** [comment]
I've opened FR #14035 to track this proposal.
