### ISSUE TITLE
Removing Module Bays with Children Power Ports breaks Power Ports count

### ISSUE THREAD

**Issue by Breadberry07** [netbox-community/netbox#14081]
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. Create module types for device (for example PWR-MX960-4100-AC with 2 power ports):
![image](https://github.com/netbox-community/netbox/assets/122742913/a3f14cf5-ffd4-4c1f-987a-77893388b62a)
2. In Devices add to chassis device (for example mx960) PEM module:
![image](https://github.com/netbox-community/netbox/assets/122742913/83ff33db-399c-4180-a834-b38d29ca56a4)
3. Check count Power Ports:
![image](https://github.com/netbox-community/netbox/assets/122742913/6c005529-2066-41e0-b529-7e47489494e2)
4. Delete module from device:
![image](https://github.com/netbox-community/netbox/assets/122742913/58478124-b73a-4a7a-b9a2-040b2c36ab4d)

### Expected Behavior

For the Power Ports count to be correct

### Observed Behavior

The port counter has not decreased

**Comment by kkthxbye-code** [comment]
Similarly removing a rearport that is associated with a frontport will not decrement the rearport count. Deleting an inventory item that has children also does not account for the children in the count, so deleting an inventoryitem named `parent_inventoryitem` that has one child inventory item `child_inventoryitem` will decrese the counter by 1 instead of 2.

I assume the counting logic is broken for any and all CASCADE deleted objects.
