### ISSUE TITLE
Allow searching for ASNs with the prefix "AS".

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#14201]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

The current global and the ASN quick search should return results independent of whether a user searches for "AS64496" or "64496".
Currently only the later returns results.

### Use case

This should reduce errors and increase the search hit rate for ASNs.
Many other systems return ASNs as "AS64496" and the user simply copies that and finds no results in NetBox.
NetBox itself even formats the ASN Objects in the global search as "AS64496" instead of "64496".

**Comment by abhi1693** [comment]
I do not think this is possible to implement. The value in question is an interger field vs the object representation (suffixed with `AS`). The search cache adds the actual value rather than the string representation of the object, so a user must search for the value as `64496` only. You could however try to use the `ends with` type instead of `partial match` to workaround this issue.

**Comment by jeremystretch** [comment]
Marking this as blocked by #15413

**Comment by jeremystretch** [comment]
#15413 has been completed for NetBox v4.0.
