### ISSUE TITLE
Can't get information about the OpenAPI (ValueError)

### ISSUE THREAD

**Issue by boykoivan123** [netbox-community/netbox#14296]
### NetBox version

v3.6.5

### Python version

3.11

### Steps to Reproduce

1. Install `pluginsnetbox_bgp: 0.11.0`, `netbox_prometheus_sd: 0.6`, `netbox_topology_views: 3.8.0`
2. Open link `https://<NETBOX_URL>/api/schema/?format=json`

As a result, I can't use dynamic inventory with plugin `netbox.netbox.nb_inventory`

### Expected Behavior

OpenAPI data is expected to be received

```
{
    "openapi": "3.0.3",
    "info": {
        "title": "NetBox REST API",
        "version": "3.6.5 (3.6)",
        "license": {
            "name": "Apache v2 License"
        }
    },
    "paths": {
        "/api/circuits/circuit-terminations/": {
...
```

### Observed Behavior

A ValueError exception was raised

I get this result
```
<class 'ValueError'>

list.remove(x): x not in list

Python version: 3.11.4
NetBox version: 3.6.5
Plugins: 
  netbox_bgp: 0.11.0
  netbox_prometheus_sd: 0.6
  netbox_topology_views: 3.8.0
```

**Comment by jeremystretch** [comment]
I'm afraid we are unable to accept bug reports that rely upon the installation of third party plugins. It is likely that the bug originates in one of these plugin, rather than in NetBox itself. If you are able to reproduce the error using NetBox without any plugins installed, you are welcome to submit a new issue with the steps to reproduce it.
