### ISSUE TITLE
Cannot load IPAM-ASNs page

### ISSUE THREAD

**Issue by uid2021** [netbox-community/netbox#14343]
### NetBox version

v3.6.5

### Python version

3.9

### Steps to Reproduce

1. Configure ASN table to include ASDOT column
2. On the left pane of homepage click 'IPAM'
3. Click 'ASNs'

### Expected Behavior

A page listing configured ASNs

### Observed Behavior

Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'asn_asdot' into field. Choices are: asn, bookmarks, comments, created, custom_field_data, description, id, journal_entries, last_updated, provider_count, providers, rir, rir_id, site_count, sites, tagged_items, tags, tenant, tenant_id

Python version: 3.9.16
NetBox version: 3.6.5
Plugins: None installed

If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by uid2021** [comment]
The problem only happens when I configure ASN table to include ASDOT column.

**Comment by Chiniquy** [comment]
Works fine for me on 3.6.5

**Comment by jeremystretch** [comment]
There's a step missing from the reproduction instructions (thanks @abhi1693):

4. Click the "ASDOT" column header to order by that column, then reload the page.

The issue is that `asn_asdot` is actually an instance property rather than a table column, so we need to set the `order_by` accessor for the column to the raw `asn` value. This will fix the exception that occurs when attempting to sort the table by this column.
