### ISSUE TITLE
Multiple "All Data (CSV)" Exports contain extra lines

### ISSUE THREAD

**Issue by gdprdatasubect** [netbox-community/netbox#14405]
### NetBox version

v3.6.6

### Python version

3.8

### Steps to Reproduce

1. Create at least two devices, one containing a rear port, one containing an interface
2. Connect the rear port to an interface
3. Navigate to dcim/rear-ports/ ; use filters if you want to
4. Export via "Export" -> "All Data (CSV)"
5. Notice that the file contains extra lines where the ">" was probably not handled correctly: 
![image](https://github.com/netbox-community/netbox/assets/101808236/e4828b29-96cc-4cd3-871e-d13bb87c45e9)
(Optional: 6. Be annoyed enough by the bug to write a report)

### Expected Behavior

No extra lines

### Observed Behavior

Lines added

**Comment by jeremystretch** [comment]
To be clear, the exported CSV here is valid; the issue is the errant line breaks present in the `link_peers` column values. We probably need to add a `value()` method to the table column to handle plaintext export in addition to the HTML rendering employed by the UI (which includes a right-angle bracket icon).
