### ISSUE TITLE
Cannot bulk update child devices

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14520]
### Deployment Type

Self-hosted

### NetBox Version

v3.6-2.7.0

### Python Version

3.11

### Steps to Reproduce

1. Create 2 child devices
2. Select them both in the /dcim/devices webpage and click "edit selected"
3. Change any field (e.g. Airflow = "front to rear")

### Expected Behavior

It should update the one field of both devices

### Observed Behavior

The update fails with error: **Child device types cannot be assigned to a rack face. This is an attribute of the parent device.**

**Comment by DanSheps** [comment]
I am unable to reproduce this, here are the steps I have followed:

1. Create Device Type "Blade" as a child
2. Create 2 devices
3. Select devices
4. Edit devices
5. Change airflow
6. Save

This resulted in no error

I also attempted a slightly different method:

1. Create Device Type Chassis with 1 bay
2. Create Device Type Blade
3. Create 2 Chassis device types
4. Create 2 Blade device types
5. Rack Chassis
6. Slot blades into chassis
7. Bulk Edit Blades
8. Save

This also did not return an error.  Please provide reproducable steps so that we can confirm this bug.

**Comment by llamafilm** [comment]
Okay I see you're right.  I can't figure out how to reproduce this, but I do have a few devices in this situation.
I noticed the `/dcim/devices` API shows a rack face assigned to these devices, which should not be possible for a child device.  It probably has something to do with the way I created the devices, modifying the device type a few times along the way.
Anyway, after modifying these devices individually, the rack face has now been removed and now bulk updating works fine.
