### ISSUE TITLE
Add option to limit IP Addresses displayed in interface tables

### ISSUE THREAD

**Issue by JohannesKreuzer** [netbox-community/netbox#14645]
### NetBox version

v3.6.9

### Feature type

Change to existing functionality

### Proposed functionality

Allow to limit the list of IP Addresses to e.g. 10, so interfaces with many assigned IPs won't clog the table.

### Use case

When having e.g. NAT interfaces with 256 assigned IPs on a central firewall on a virtual interface this will clog the table, e.g. making it hard to find the next interface and also the name for the current interface. So an option to limit the viewed addresses would be handy.

Possible look, when limited to 10 addresses:
![image](https://github.com/netbox-community/netbox/assets/1869209/9222d5d3-4900-4605-b606-8112de274dba)

### Database changes

N/A

**Comment by jeremystretch** [comment]
> When having e.g. NAT interfaces with 256 assigned IPs on a central firewall on a virtual interface this will clog the table

This occurs because you're incorrectly modeling IP address assignments. IP addresses belonging to a NAT pool should not be assigned to an interface.

**Comment by JohannesKreuzer** [comment]
So what is you suggestion on how to model the link of the NAT pool to the device performing the NAT?

**Comment by jeffgdotorg** [comment]
Hi there, product manager weighing in here.

I've labeled this FR with `status: needs owner` because we think there's value in the behavior you describe, despite any misgivings about your particular use case.

For what it's worth, I suggest looking into using IP ranges to model your NAT pools. You can find details in [the IPAM docs](https://docs.netbox.dev/en/stable/models/ipam/ipaddress/#network-address-translation-nat).

**Comment by abhi1693** [comment]
Would it make sense to just show the count of IP addresses? If so, I can take onwership of this issue.

**Comment by JohannesKreuzer** [comment]
I personally would display IPs if there are only 1 or 2 assigned and otherwise say e.g. 30 IP addresses assigned.
