### ISSUE TITLE
Setting to toggle network mask visibility for individual IP addresses

### ISSUE THREAD

**Issue by artiomello** [netbox-community/netbox#14654]
### NetBox version

v3.6.9

### Feature type

New functionality

### Proposed functionality

I believe it would be beneficial to expand the global settings with a toggle switch that would show/hide the netmask of individual IPs. 
<img width="318" alt="image" src="https://github.com/netbox-community/netbox/assets/102314521/f37fef3a-87bc-48bf-b0e3-ff99c9e25e60">

The switch would only alter how the individual IPs are represented throughout Netbox. 
And it would also be possible to save the global setting, per user or globally, so that one doesn't have to enable it every single time. 

### Use case

Skimming through #8731, I understood that this is made like so primarily for API calls, which is good. But this approach completely disregards the eyes and brains of people who are using the UI. Especially the ones that are not so well-versed in netmasks (these people do exist). 

I'm not a networks guy, and don't know how widely masks are used for individual IPs, but from my perspective, masks are used mainly to designate subnets/prefixes. Displaying IP/mask for individual addresses can make one think that it's a subnet, when in fact's it isn't.

When I open a prefix, I already see the mask at the very top and there's no reason I can think of to have a mask for every address in the list. It's pretty much the same as putting the device type next to the device name (e.g. server:WSUS01 or firewall:FW01).

Now, I'm not saying to alter the way the API calls are made - I'm simply suggesting to improve the UI so that if the mask can't be (for whatever reason) removed from individual IPs,  it's possible to toggle them on/off by the UI and not by one's imagination.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox, and happy new year!

I'm closing this FR because I think the 80% NetBox user finds the presence of netmasks in this context to be either helpful or, at worst, a slightly annoying bit of information that's easily ignored.

Because I'm a product manager, however, I'm genuinely interested in learning more about your point of view. Which tools do you use that omit masks when listing individual IP addresses? What kinds of tasks occupy you during your workday? If it turns out that you represent an important user persona that we've overlooked, we want to know that. If you would like to open a discussion and tag me in it, we can continue the conversation there.
