### ISSUE TITLE
Table column configuration remembers ordering without saving

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14688]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.9

### Steps to Reproduce

1. Go to Sites
2. Click Configure Table
3. Select Description column and click Move Up
4. Don't click Save but close the configuration dialog using X
5. Click Configure Table

### Expected Behavior

The Selected Columns list is in the same order as shown in the site list.

### Observed Behavior

The Description item in the Selected Columns list is not in the original position (last in the list) but it is above Tenant, even though the column ordering was not saved at any point. Apparently the dialog remembers the ordering even though it is not applied to the actual table.

If the page is reloaded, the Selected Columns list is reset to the correct order again.

**Comment by jeremystretch** [comment]
This is working as intended. Like all UI components, the table configuration form retains state until it is removed from the DOM (e.g. by navigating away from the page). Hiding the modal does not remove the form from the page.

This is a good thing, because it allows the user to temporarily hide the dialog and to recover from an accidental dismissal. Imagine how frustrating it would be to carefully craft a table configuration and then accidentally close the form instead of saving it, and have to start over.
