### ISSUE TITLE
allow merging lists in config context

### ISSUE THREAD

**Issue by szelga** [netbox-community/netbox#14769]
### NetBox version

v3.2.8

### Feature type

Change to existing functionality

### Proposed functionality

allow deep merging not only dictionaries, but also lists. as of now, netbox replaces lists when merging.

### Use case

I'm not saying this feature is universally needed, but there is definitely a use case for this.

I'm using [this script](https://github.com/TheNetworkGuy/netbox-zabbix-sync) to sync Netbox hosts to Zabbix and I want to export Zabbix templates via config context. so, ideally, I'd want, for instance, a source context of the host to be like:

```json
{
    "zabbix": {
        "templates": [
            "ICMP Ping",
            "Linux by Zabbix agent"
        ]
    }
}
```

the local context

```json
{
    "zabbix": {
        "templates": [
            "Linux generic by Zabbix agent",
            "Linux CPU by Zabbix agent"
        ]
    }
}
```

and the rendered context

```json
{
    "zabbix": {
        "templates": [
            "ICMP Ping",
            "Linux by Zabbix agent",
            "Linux generic by Zabbix agent",
            "Linux CPU by Zabbix agent"
        ]
    }
}
```

### Database changes

no database changes needed.

### External dependencies

[deepmerge](https://deepmerge.readthedocs.io/en/latest/) would be useful in this case, though it's not necessarily required.

**Comment by abhi1693** [comment]
How would you propose a list item to be removed?

**Comment by jeffgdotorg** [comment]
Thanks for your proposal to help improve NetBox. We need more information to help us evaluate this request. Please take care of the following:
1. Your report is against a very old version of NetBox. While this functionality has not changed much since, please try in future to open issues against a newer release.
2. This issue shares many aspects with #5698, which is not to suggest that your issue will have the same outcome.
3. We need specific suggestions of a convention for how this proposal would work. You might find it useful to refer to the [Custom Validators](https://docs.netbox.dev/en/stable/customization/custom-validation/) feature for inspiration in the additive use case.
4. As @abhi1693 points out above, we need your thoughts on how _removing_ a list item might work.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
