### ISSUE TITLE
VPN IKE Proposal Multiselect Option

### ISSUE THREAD

**Issue by markh0338** [netbox-community/netbox#14790]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

In some configurations, it is possible to have multiple encryption/authentication/group algorithms selected in a single proposal. Currently, in v3.7.0 only one encryption algorithm or authentication algorithm or DH group can be selected per proposal. It would be nice to be able to select multiple options for each field. 

### Use case

A proposal like this is currently not possible to documented.
crypto ikev2 proposal ike-proposal-1
 encryption aes-cbc-256 aes-cbc-128
 integrity sha512 sha256
 group 21 20 19

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox.

If this issue had arrived during the 3.7.0 beta period, a conversation about allowing multiple values in IKE proposals might have led to us taking up the suggestion. Unfortunately the modeling of proposals is now finalized, and altering it isn't something we currently have the resources to take on.

I'm therefore closing this issue, but I encourage you to start a discussion so that we can get a feel for how many other NetBox users would benefit from this change.

**Comment by mbneteng** [comment]
I agree with @markh0338 this is a limitation with the model.  Utilizing multiple algorithms or DH groups is very common in proposals.  These proposals are typically the most complex ones and having the ability to model them in NB would be very beneficial.

**Comment by jeremystretch** [comment]
@mbneteng this would have been actionable feedback during the monhth-long v3.7 beta period. However, now that v3.7.0 has been released we will not be making any breaking changes to the VPN data model in the near future.
