### ISSUE TITLE
Select All check box in device Types Interfaces fails to check all boxes

### ISSUE THREAD

**Issue by xkilian** [netbox-community/netbox#14945]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.8

### Steps to Reproduce

1. Create a device Template with more than 50 interfaces
2. Go to Device Types
3. Click name of device-type
4. Click on Interfaces
5. Click on per page widget to allow 100 lines to be displayed
6. Click on Check box next to name column

### Expected Behavior

All the checkboxes should be selected.

### Observed Behavior

Only the signle box next to name is selected.

**Comment by xkilian** [comment]
I also noticed that navigating between Interfaces and Console Ports or Power Ports, the All check box next to Name will  start functioning again, but the Number of lines widget setting is not preserved.

**Comment by jeremystretch** [comment]
It looks like the "select all" event handler isn't getting reinitialized after the table is re-rendered via an HTMX request (e.g. changing the ordering or pagination length).

**Comment by jeremystretch** [comment]
There's a bug in how event handlers are added to the dynamic object list. HTMX controls within the table reference the HTMX container as `closest .htmx-container`, but this is obviously relative. When `initHtmx()` attempts to resolves this, it fails. It only works on the regular object list view because the quick search field coincidentally refers to the container by its explicit ID (`#object_list`); the quick search field is not present on the device type components list.
