### ISSUE TITLE
Show peer interfaces in circuit detail view

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#15125]
### NetBox version

v3.7.2

### Feature type

New functionality

### Proposed functionality

When viewing details for a circuit, you will see where the circuit terminations are connected. The way we model things, we'll almost always terminate a circuit in a rear port of a patch panel or similar. It would be handy if we could have a direct link to the interface connected at the end of the path on each end.

For example: In addition to showing "Termination: #123 to Patch Panel 456, 7-8", add a row to this view to show "Termination Interface: router123, 4/5" with links to the appropriate device and interface.

This functionality is already in Netbox, but it's an extra step to have to do a trace of the cable on either end to get the interface.

### Use case

Quickly identifying associated interfaces and devices, given a circuit ID.

### Database changes

None, all the data is already in Netbox since it can already be accessed using a cable trace.

### External dependencies

None.

**Comment by jeffgdotorg** [comment]
Chipping away at this kind of "papercut" UI struggle is something I'd like to see us focus on during the v4.1 development period. Moving along to `needs owner`. If you're interested in working it through to a PR, just say so and someone will assign it to you. Otherwise another person with the requisite skills and spare capacity can pick it up at any time, even before 4.1 work gets into full swing.

**Comment by pv2b** [comment]
Jeff, I assume you're addressing me on this one.

I'm glad that you agree that this is a worthwhile feature. However, I'm afraid I'm going to pass on the opportunity to work on this. My previous experiences of contributing to this project have, because of personality clashes, not been productive or positive for me nor the project.
