### ISSUE TITLE
IP allocation skips ASN

### ISSUE THREAD

**Issue by craigmcfly** [netbox-community/netbox#15171]
### NetBox version

v3.7.1

### Feature type

New functionality

### Proposed functionality

A prefix is assigned by the RIR to an LIR (usually a one to one mapping between LIR and ASN), but the IPAM doesn't allow prefixes to be assigned to be ASNs, nor can you se a list of assigned prefixes from the ASN page ( https://netbox.mydomain.com/ipam/asns/1/ )

It would be nice if prefixes ( https://netbox.mydomain.com/ipam/aggregates/?rir_id=1 ) could be allocated.

### Use case

It would help when working down from the ASN level to see assigned prefixes

**Comment by PieterL75** [comment]
I had the same issue submitted some time ago:
https://github.com/netbox-community/netbox/issues/8782
But linking prefixes to ASN's was not implemented because "there is no direct relationship between a prefix and an ASN in reality". I hope you can convince them that within a LIR the relation is real and very important (RPKI/ROA)
Then there is https://github.com/netbox-community/netbox/issues/9828 that gets more in details on LIR/ROA, but that was set to be a plugin rather than native to the netbox core...

I would still really like to get the ASN linked to a Prefix, as that is pretty basic. The ROA/RPKI part then get into a pluging

**Comment by falz** [comment]
This has come up repeatedly, there are many use cases to assign IP to ASN. In addition to that RPKI issue there are many other tools, such as bgpalerter, who's config file correlates IPs to ASNs. 

We were just looking to use Netbox export templates to build a Bgpalerter config, but it does not seem possible due to this lack of relationship.

**Comment by jeremystretch** [comment]
It seems that several proposed functionalities are being conflated in the conversation above. The issue title reads "IP allocation skips ASN" (?) yet the description references both prefixes and aggregates. @craigmcfly could you please edit your post above (do not make a new reply) to clarify the _specific_ proposal?

**Comment by arthanson** [comment]
@craigmcfly can you please edit the post above to clarify the specific proposal?  Issue is pending closure without additional updates.

**Comment by arthanson** [comment]
Closing as no feedback.
