### ISSUE TITLE
IPAM does not show all available prefixes

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#15562]
### Deployment Type

Self-hosted

### NetBox Version

3.7.4

### Python Version

3.11

### Steps to Reproduce

Create this example set of child prefixes under `10.35.96.0/20`:
<img width="361" alt="Screenshot 2024-03-28 at 9 37 39 AM" src="https://github.com/netbox-community/netbox/assets/53161/26dfc7f7-71ff-4ff4-aaba-c53badefcfb1">

### Expected Behavior

In the example shown, `10.35.102.0/23` has prefix space available, so I would expect it to be displayed here, as it is in the detail view for that prefix.
<img width="317" alt="Screenshot 2024-03-28 at 9 39 38 AM" src="https://github.com/netbox-community/netbox/assets/53161/369b0c81-e338-47e1-9ab7-bb07cf634419">

### Observed Behavior

The available prefix space is not shown.

**Comment by jeremystretch** [comment]
This is the intended behavior. 10.35.103.0/24 is not listed as available space for 10.35.96.0/20 because it is claimed by the 10.35.102.0/23 container. It is listed as available space only _within that container_. If you were to delete the container, 10.35.103.0/24 would be listed as available space directly beneath 10.35.96.0/20.
