### ISSUE TITLE
Sidebar not affected by color theme change

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15615]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Click the bulb in the top right corner to toggle the color mode to light mode

### Expected Behavior

Sidebar swiches to light mode

### Observed Behavior

Sidebar stays dark

The theme is hardcoded to `data-bs-theme="dark"`

`<aside class="navbar navbar-vertical navbar-expand-lg" data-bs-theme="dark">`

**Comment by jeremystretch** [comment]
Yes, this is intentional.

**Comment by candlerb** [comment]
I'm not sure why this is intentional - IMO the combination looks terrible.

![image](https://github.com/netbox-community/netbox/assets/44789/87ef50c3-6ecb-409c-b08c-a7b9cd7eaf34)

I know that dark mode is the trendy view these days, but I'm used to light mode and my eyes prefer it.

Secondary issue: the navigation menu no longer collapses. It's not really an issue on a desktop monitor, but on a laptop it significantly reduces the amount of space available for data display.

**Comment by jeremystretch** [comment]
> IMO the combination looks terrible

We'll have to disagree; I quite like it. You'll note it's also the style preferred in [Tabler's live demo](https://tabler.io/preview).

> Secondary issue: the navigation menu no longer collapses. It's not really an issue on a desktop monitor, but on a laptop it significantly reduces the amount of space available for data display.

I don't see any need for it, but #15614 is open for an owner. We'll see if there's any overlap between people who see value in the functionality and people willing to contribute their time and effort implementing it.

**Comment by candlerb** [comment]
> You'll note it's also the style preferred in [Tabler's live demo](https://tabler.io/preview)

Can you give a specific location? Do you mean "Layout > Vertical" and/or "Layout > Condensed"?  But there are also "Layout > Vertical Transparent" and "Layout Right" which use light mode for navigation, at least when the browser is in light mode. I don't see any indication that one is "preferred" over the other.

Cross-ref: FR https://github.com/tabler/tabler/issues/1803 shows examples of both light mode and collapsible navigation.
