### ISSUE TITLE
Return the slim sidebar menu

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15614]
### NetBox version

v4.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

The new sidebar is wider and there is no possiblity to hide this massive sidebar.
Proposed change: 
Some sticky icon like in the old UI
![image](https://github.com/netbox-community/netbox/assets/41152397/006c4eb4-e05b-4061-820c-dbf72b68e533)
![image](https://github.com/netbox-community/netbox/assets/41152397/384c8cef-e079-4ea2-8f4b-56379f651410)

### Use case

Use the screen more efficiently and prevent/minimize horizontal scrolling in tables.

### Database changes

-

### External dependencies

-

**Comment by julianstolp** [comment]
I have seen the button is in the html code but not displayed for unknown reasons. Is it just me? 

`<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-menu" aria-controls="sidebar-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>`

**Comment by julianstolp** [comment]
I have almost exclusively used the narrow navigation bar to display as many columns as possible. It would be nice if this option were available again.

**Comment by sleepinggenius2** [comment]
I also would like to see the collapsed navigation bar return. The new one is 33px wider than even the fully expanded one before and 241px wider than the collapsed one. When you are displaying a table with a lot of columns, every pixel helps. The worst offender for me is usually the Interfaces table, where I find it difficult to fit all the columns I need even on a 2560px wide screen.

I can tell you from experience with my end users that they have always been thrilled when I show them the ability to collapse the menu and get some valuable screen real estate back. From observation, the menu is almost never used in our environment, so even the collapsed version has been identified as an annoyance. The typical flow I see is users finding what they are looking for through the global search, then navigating around from there through breadcrumbs or other links within the view. In fact, most of my users don't even know where to find things in the menu because of how infrequently they use it.

**Comment by petersonbasso** [comment]
The collapsed navigation menu is very useful, especially for small screens.
Better to keep the option and leave it up to the user to keep it fixed.

**Comment by jeremystretch** [comment]
Opening this for a volunteer to implement it.

**Comment by julianstolp** [comment]
If someone is able to implement this, there is an open FR in the Tabler repository. It would certainly be good to implement this there so that no custom code is necessary in NetBox.

https://github.com/tabler/tabler/issues/1803

**Comment by heroin-moose** [comment]
Please, please, please, please, please, please, please, please, please bring it back.

**Comment by jeremystretch** [comment]
@heroin-moose would you like to take ownership of this issue?

**Comment by heroin-moose** [comment]
@jeremystretch, yeah, why not. Would you prefer it via https://github.com/tabler/tabler/issues/1803?

**Comment by jeremystretch** [comment]
Upstream support would be strongly preferred, but of course that's out of our control. We'd only accept a local implementation if it can be achieved in a clean, maintainable manner with minimal additional code.

**Comment by heroin-moose** [comment]
I'll do my best.

**Comment by bobbwest** [comment]
An interim solution would be to have a toggle that would disable the responsive full side navbar menu, keeping the dropdown navbar menu that is usually activated on narrow viewports.  At least that means people wanting a wide tabular display can achieve that, and still maintain some access to the navbar menu.

**Comment by jeremystretch** [comment]
@heroin-moose are you still planning to work on this, or should we release it for another volunteer?

**Comment by kshelekhin** [comment]
I am planning, but if someones gets there faster why not?

**Comment by heroin-moose** [comment]
I'm slowly getting there, but if someone gets there first I would gladly pass the issue.

**Comment by PaulR282** [comment]
This feature would be highly appreciated because the sidebar uses a lot of space on small displays.

**Comment by jeremystretch** [comment]
I'm going to close this in favor of #16392, which is being actively worked locally by @andrewgormley. Hopefully we'll be able to leverage @heroin-moose's upstream contribution to Tabler at some point in the future.

**Comment by mmip-labs** [comment]
I also need collapsed menu. It was very convenient for us
