### ISSUE TITLE
Configuration Revision not showing data

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#16077]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

1. Create a new Configuration Revision
2. Save
3. View that Configuration Revision (not edit)

### Expected Behavior

All values of the fields are shown

### Observed Behavior

The values are not visible
https://demo.netbox.dev/core/config-revisions/1/
![image](https://github.com/netbox-community/netbox/assets/74899468/fc8e4f9e-8a35-441d-bc9e-65ee4f07f7bd)

**Comment by jeffgdotorg** [comment]
Thank you for reporting a suspected bug in NetBox. I have confirmed that this problem is reproducible on a fresh install of NetBox 4.0.1, so moving it out of triage state.

For future reference, please keep in mind that the demo system is not considered reliable for purposes of bug reporting as its state is ever in flux. Anybody can gain admin access to it and wreak arbitrary havoc, and its database gets reset nightly to offset this hazard.

**Comment by PieterL75** [comment]
@jeffgdotorg , thank you for reviewing. 
I do find the issues on my one lab/qa instances, and i use the demo for ease of providing a link. 
Works most of the time, when people don't break the demo.
