### ISSUE TITLE
Include option to filter prefixes list by assigned VLAN(s)

### ISSUE THREAD

**Issue by xkilian** [netbox-community/netbox#16117]
### NetBox version

v3.7.2

### Feature type

Change to existing functionality

### Proposed functionality

In prefixes, permit VLANs in the filtering view.
![image](https://github.com/netbox-community/netbox/assets/1302719/9a93db30-5395-47ae-bc00-8250fe85e648)

### Use case

Prefixes can be associated with VLANs but it is not possible to filter prefixes based on VLANs in the filtering view.

### Database changes

None

### External dependencies

None

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox, and for spotting the need for this enhancement. I've confirmed it has not been completed between 3.7.2 and 4.0.2.

I'm moving the issue's status to `needs owner`. If you would like to work it through to a PR, please let us know and a maintainer will assign the issue to you. Otherwise, another developer with the requisite skills and capacity can pick it up at any time.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

If yes, should I create a new section for VLAN or include it in "Addressing"?
