### ISSUE TITLE
Time in Change Log without timezone

### ISSUE THREAD

**Issue by fixed77** [netbox-community/netbox#16143]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

1. Set TIME_ZONE in configuration.py
2. Make changes
3. Go to Changelog

### Expected Behavior

Time in Changlelog table and events in localtime

### Observed Behavior

Time in Changlelog table and events in UTC

**Comment by samk-acw** [comment]
This seems to be a regression due to https://github.com/netbox-community/netbox/pull/15737, or a djanjo 5 side effect.

A potential fix is loading the TIME_ZONE preference and doing .astimezone() before any .isoformat() call. This appeared to work when testing for myself but not sure about any other implications

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
