### ISSUE TITLE
A sidebar menu folds when a cursor is no longer hovering over the sidebar

### ISSUE THREAD

**Issue by heroin-moose** [netbox-community/netbox#16140]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.1

### Python Version

3.10

### Steps to Reproduce

See the attached video.

https://github.com/netbox-community/netbox/assets/15263497/409dacf4-6eb9-427c-b413-97d9df16d096

### Expected Behavior

The sidebar should remain static.

### Observed Behavior

The sidebar menu folds/unfolds, depending on cursor coordinates.

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you're seeing with NetBox.

I've tried to reproduce the behavior that your video shows, both on the public demo (which is now running 4.0.2) and on a lab instance running 4.0.1. I tried with current releases of Chromium, DuckDuckGo, and Firefox on macOS. Either the problem is local to your system, or I need more detailed steps to reproduce. Your video doesn't show the steps you took to get to the starting point, which may be relevant.

It's also worth pointing out that our bug report template specifically warns against using the public demo system to report bugs, because that system is always in an unknown state and it gets reset every 24 hours.

**Comment by heroin-moose** [comment]
I think 4.0.2 fixed it, cannot reproduce anymore. Thanks!

**Comment by heroin-moose** [comment]
No, spoke too soon. It works fine on the title page, but going into a "Site" page triggers the issue for me. I'm using firefox 126 on Arch Linux.

**Comment by jeffgdotorg** [comment]
Okay, I poked at the UI quite a bit trying to reproduce this the first time and can't really justify going down a rabbit-hole figuring out exactly how you're able to trigger the problem behavior. Please record a new video that shows the whole browser window, including the URL in the address bar, and starts with a blank new tab, with no jump cut. If you think voiceover narration might help me understand something that doesn't come across as totally obvious, consider adding some.

**Comment by jeremystretch** [comment]
@heroin-moose try disabling any browser plugins you have installed that might be interfering with the Javascript/CSS.

**Comment by heroin-moose** [comment]
Appears to be the problem with old site data cached in browser, removing the cache through firefox's "Manage Site Data" helps.
