### ISSUE TITLE
Allow custom field objects to be limited 

### ISSUE THREAD

**Issue by karolyczovek** [netbox-community/netbox#16169]
### NetBox version

v3.7.8

### Feature type

Data model extension

### Proposed functionality

Is it possible, to set custom fields to honor relations?

For example, I set a custom field related to the site as multi-object with prefixes, then let the custom field honor the global/site-assigned specific prefixes. 

### Use case

Multi-field custom field object I could select from prefixes already assigned to site.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox.

I think your proposal makes sense, but since you've opened it against 3.7.8, I wonder whether the same effect might be possible with no code changes by leveraging improvements to the select controls in NetBox 4.0.

In the screenshot below, you can see that the description of a prefix now shows up in the custom field select control, and that by using type-ahead filtering you can limit the values shown. Assuming your prefixes have descriptions, I think this workflow might meet your need. Please give it a try in a test environment or on the [public demo system[(https://demo.netbox.dev/) and indicate whether you agree.

<img width="784" alt="image" src="https://github.com/netbox-community/netbox/assets/1209268/bc380363-0dae-44cb-9f27-2db448fe225a">

**Comment by karolyczovek** [comment]
Will give it a try, does 4.0 API already work with Ansible?

**Comment by karolyczovek** [comment]
Just run the smoke tests - UI-wise it looks fine but still an extra effort from the enduser - however ansible interaction (lookups and modules) are broken from 4.0

**Comment by jeffgdotorg** [comment]
Top people are working on the remaining 4.0 compatibility issues in the Ansible collection. I understand that may be a barrier to you upgrading your instances, but let's please keep the comments in this issue on topic to avoid confusing future time travelers.

**Comment by karolyczovek** [comment]
Same applies in general - imagine sites with same-like named equipments - for example 16 sites with 20 cameras at each named camera NN, so custom field  "related objects" would be nice to honor site
