### ISSUE TITLE
No search bar on mobile

### ISSUE THREAD

**Issue by ChrisRecioHive** [netbox-community/netbox#16273]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.12

### Steps to Reproduce

1. Open Netbox on a mobile device

### Expected Behavior

Display a search bar either at the top or in the collapsible menu

### Observed Behavior

No search bar

![image](https://github.com/netbox-community/netbox/assets/143728336/cf3459cd-f406-4b8d-a1cd-d82383aee616)

**Comment by amit177** [comment]
The reason it doesn't show up is that the container has the `d-none` class.
It shows up on a larger screen because of the media query setting the display to flex and overriding `d-none`.

Changing `d-lg-flex` to `d-sm-flex` should fix the issue, but would look weird.
Perhaps the better solution might be moving the search bar to the top of the menu when it is expanded.

**Comment by ITJamie** [comment]
related: there's no darkmode / lightmode switch on mobile ether in the top bar.

**Comment by ljarasius** [comment]
I can take this one @jeremystretch

**Comment by pv2b** [comment]
> Is there a workaround for this? Other than tapping the URL bar and adding `/search` I mean.

You could add a Note widget to your dashboard with the following contents:

    # [Search](/search)

This will make a heading-sized link with the word "search" you can click on from the dashboard to get to the search page. Heading-size so that it's a little easier to tap on mobile. Of course it'll also show up from your dashboard on desktop.

This way you can just go to the dashboard and have a search link from there. Not ideal but I think that's the best you can do without any code changes.
