### ISSUE TITLE
Change side navigation theme

### ISSUE THREAD

**Issue by andrewgormley** [netbox-community/netbox#16393]
### NetBox version

v4.1.0-dev

### Feature type

New functionality

### Proposed functionality

When a user changes theme between light and dark mode the side navigation should also change colour. The current app has a 'light' side navigation regardless of whether light or dark mode has been selected.

### Use case

By adding this feature users would have full control over their theme experience. The current dark mode experience forces users to constantly look between a light mode menu and dark mode content area which means their eyes need to adjust between the two contrast types, this is not optimal.

**Comment by jeremystretch** [comment]
@andrewgormley this has already been proposed and declined in #15615. The use of a contrasting color for the sidebar was an intentional choice, and serves to differentiate navigation controls from the page content. It's a rather common approach for dashboard-type applications; here's [an example](https://preview.tabler.io/layout-combo.html) straight from Tabler as a reference.
