### ISSUE TITLE
Upgrade from 3.7.8 to 4.0.3 failed due to missing tables

### ISSUE THREAD

**Issue by kareemshayeb** [netbox-community/netbox#16430]
I am currently in the process of upgrading our Netbox server from version v3.7.8 to the latest release v4.0.3. During the migration phase, I encountered an inconsistency within the database.
Specifically, the extras_customfield_object_types table seems to be missing. Upon further inspection, I confirmed the presence of the following tables related to custom fields:
- public.extras_customfield
- public.extras_customfieldchoiceset
- public.extras_customfield_content_types

**Comment by jeffgdotorg** [comment]
Hi @kareemshayeb, I'm the product manager for NetBox Open Source.

We noticed that this issue does not follow any of the project's [issue templates](https://github.com/netbox-community/netbox/issues/new/choose). We think that's because it was created via a Slack integration. Can you please confirm that guess?

**Comment by kareemshayeb** [comment]
Yes, that's correct. That was using the Slack.

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by kareemshayeb** [comment]
yes, via NetDev Community.

**Comment by jeffgdotorg** [comment]
@kareemshayeb do you recall from which channel and by which command you were able to make this issue?

**Comment by kareemshayeb** [comment]
@jeffgdotorg  Here is [the link](https://netdev-community.slack.com/archives/C01P0FRSXRV/p1717658234803609) to the original question that I've posted. In addition to the menu and option of creating the Github issue.

![issue](https://github.com/netbox-community/netbox/assets/39455431/85287fb8-9dd8-480f-87ed-3e2edc9e1c80)

I already created [a question](https://github.com/netbox-community/netbox/discussions/16441) instead on an issue in the discussions area. Is there the right place for it? I hope to get an answer since this issue is preventing me from upgrading to the new major release.
Thanks.

**Comment by jeffgdotorg** [comment]
Thanks for helping me solve a mystery.

You created the discussion in the right place. I'll see if I can draw some attention to it.
