### ISSUE TITLE
Circuits Column Sorting by Termination/Side Doesn't Properly Sort

### ISSUE THREAD

**Issue by jniec-js** [netbox-community/netbox#16444]
### Deployment Type

Self-hosted

### NetBox Version

v3.7, 1, v4.0.5

### Python Version

3.10

### Steps to Reproduce

1. Navigate to Circuits listing page
2. Click on either Side A or Side Z to sort column alphabetically
3. Observe that the Side A/Side Z columns are not sorted, but instead the provider column gets sorted alphabetically

See: https://demo.netbox.dev/circuits/circuits/?sort=termination_a. 

At the time of creating this issue, I modified the termination_a of Circuit https://demo.netbox.dev/circuits/circuits/1/ to be `DM-Akron`, then attempted to sort Side A alphabetically. 

![Screenshot from 2024-06-07 09-29-02](https://github.com/netbox-community/netbox/assets/141941931/ca34f6ee-27dd-4141-94a4-2e3a9c4fd8f0)

Notice that https://demo.netbox.dev/circuits/circuits/1/ is located in the middle of all the Side A terminations, I expect it to be at the top. 

### Expected Behavior

I expect that the column clicked on (to sort) is the one sorted alphabetically 

### Observed Behavior

The provider column was sorted alphabetically instead of the Side A/Side Z column that was clicked on.

**Comment by jeffgdotorg** [comment]
Hi, thanks for reporting an issue that you're experiencing in NetBox.

For our developers to validate your bug report, they need to be able to reproduce it in the lab, and to do that they need a detailed set of steps to reproduce the problem you're seeing, starting with a freshly installed and empty instance of NetBox. Please update your issue body's **Steps to Reproduce** section so that it assumes an empty starting point and specifies each object that needs to be created to get the system to the point where we can see the problem in action.

One additional note: The demo system is not appropriate for use in bug reports, because anybody can log in as an admin user and totally wreck its contents. That's why we reset it nightly.

**Comment by joshniec** [comment]
I can appreciate asking for detailed production steps - but I think the issue as reported is fairly basic, the Site columns do not sort properly in the circuits.  I expect them to sort alphabetically like all other columns when clicked on. 


Problem Statement: When sorting the side columns on the circuit page they aren't sorted alphabetically. 


Reproduction:
1. Add multiple sites, providers and circuits to netbox. 
2. For the circuits, make sure you create multiple circuits for each of the providers.
3. For each of the circuits created, create circuit terminations on each of the sites created in step 1.
4. Go back to the circuits view to see all your circuits. 
5. Click on Side A column to sort it alphabetically. 
6. Observe that the column is not properly sorted alphabetically (as seen in the screenshot of my original post) 

Expectation:
Objects in column I sort should be sorted alphabetically.
