### ISSUE TITLE
Strings with plural forms

### ISSUE THREAD

**Issue by afranke** [netbox-community/netbox#16659]
### Proposed Changes

In `netbox/dcim/choices.py`, there’s this bit of code:

```
83:        (WIDTH_10IN, _('{n} inches').format(n=10)),
84:        (WIDTH_19IN, _('{n} inches').format(n=19)),
85:        (WIDTH_21IN, _('{n} inches').format(n=21)),
86:        (WIDTH_23IN, _('{n} inches').format(n=23)),
```

That is problematic for translations to some languages, because plural forms don’t necessarily work the same as English where there one and many and that’s it. For instance, in Polish, the word for inches will be declined differently for 21 and for 23, because they end in 1 and 3 respectively and that has an impact. 

Considering it’s exactly four specific values and not just any arbitrary value for n, I would suggest just hardcoding the four strings (`"10 inches"`) as translating these four strings will be the most straightforward across languages, and it’s only four strings.

### Justification

See [plural forms](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) for more details.

I am not suggesting the use of ngettext here because we don’t need a general solution and it would make the code unnecessarily complex here.

**Comment by afranke** [comment]
`"Group {n}"` in `netbox/vpn/choices.py` is in a similar situation and I understand that you are trying to create less work for translators, but this is actually going to create problems instead of solving them. Please just do one string per number. The extra strings will be easy enough to translate with minimal overhead.

**Comment by jeremystretch** [comment]
> Please just do one string per number. The extra strings will be easy enough to translate with minimal overhead.

I'm not sure I agree. At point do you think it becomes unreasonable? Ten unique strings? A hundred? It would be unfair to put that burden on translators if it can be minimized via the use of `ngettext()`.

**Comment by ITJamie** [comment]
This is always a PIA when dealing with translations. The same problem happens when dealing with strings like 1st,2nd,3rd etc as many languages have different rules for this and can impact other parts of the string, not just the "counter" part. 

A few enterprise products i work with handle this by having "primary" and "fallback" versions of the same string (or even fully parsed vs templated versions of the string)

So the translation code first calls the more specific/fully parsed version of the string (eg "10 groups"), if that is not found it then falls back to "{N} groups" lookup, that allows languages which have more complicated phrasing to have specific overrides for handling declension an conjunction rules.

**Comment by afranke** [comment]
> At point do you think it becomes unreasonable? Ten unique strings? A hundred? It would be unfair to put that burden on translators if it can be minimized via the use of `ngettext()`.

Doing nothing clearly isn’t better. I offered two options: hardcode the 24 `Group {n}` strings (really not a big deal, even if you disagree, considering how trivial the strings are) or use `ngettext`. If you actually care about translators, worry less about the burden and worry more about providing workable material.
