### ISSUE TITLE
Prefixes: add 'vlan' to bulk edit

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#16692]
### NetBox version

v4.0.5

### Feature type

Change to existing functionality

### Proposed functionality

When editing a Prefix, you can set the VLAN/Group
When using the Bulk-Edit option, there is no 'VLAN' field to change

My proposal is to update the Bulk Edit form, so that VLANs can be assigned in bulk to prefixes

### Use case

Update the VLAN assignment of multiple prefixes in one go

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox.

I'm moving your feature request along to `needs owner` status. If you would like to work it through to a PR, please say so and one of the maintainers will assign it to you. Otherwise, another developer with the requisite skills and capacity can chime in and pick it up at any time.

**Comment by PieterL75** [comment]
@jeffgdotorg I can submit a PR for this
