### ISSUE TITLE
New interface type SFP (100 Base-FX)

### ISSUE THREAD

**Issue by rcalpha** [netbox-community/netbox#16781]
### NetBox version

v4.0.6

### Feature type

Data model extension

### Proposed functionality

Add 100Mbps SFP interface type (100 Base FX)

### Use case

I'm documenting an active network device that we have: Alcatel 7250 SAS 
Specs: https://www.starmicrowave.com/wp-content/uploads/2018/03/7250SAS_v2.pdf

I tried to create 100Mbps SFP interface but netbox only has SFP (1GE). This device has both 100Mbps and 1GB. It would be useful to differentiate

**Comment by jeffgdotorg** [comment]
Hi, and thanks for your interest in helping improve NetBox.

My understanding of media and connectors is not comprehensive. Before I move your issue out of triage, please confirm that you are in fact using NetBox v4.0.6 as indicated. I ask because issue #11371 already added a 100Base-FX interface type, albeit without the SFP connector type designation.

**Comment by rcalpha** [comment]
Yes, I'm using Netbox v4.0.6. 100Base-FX interface type is one way if the switch was it fixed using SC, FC, ST (or another type) port... however this switch use SFP slot.

**Comment by jeffgdotorg** [comment]
Thanks for the clarification. I'm moving your issue along to `needs owner` status. If you or another developer with the requisite skills and capacity wants to work it through to a PR, please say so and a maintainer will assign the issue to you.

**Comment by RobertH1993** [comment]
Hi i have created an PR for this

**Comment by jeffgdotorg** [comment]
> Hi i have created an PR for this

Issue is assigned, sorry I just spotted your comment.

**Comment by alehaa** [comment]
I volunteer for this PR.
