### ISSUE TITLE
404 error for Create & Add Another (Contact Assignment)

### ISSUE THREAD

**Issue by Azmodeszer** [netbox-community/netbox#16806]
### Deployment Type

Self-hosted

### NetBox Version

4.0.6

### Python Version

3.11

### Steps to Reproduce
1. Create a site
2. Create a contact
3. From the site's _Contacts_ tab, click _Add a contact_
4. Choose the contact
5. Click "Create & Add Another "

### Expected Behavior

Assignment is added and you're redirected to the same form for another.

### Observed Behavior

Object is created, but an error shows up:
```
 /tenancy/contact-assignments/add/
The requested page does not exist
```

Same as #7757?

(Seems to impact contact assignments to all object types, not just sites.)

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you've encountered in NetBox. With a little work I've managed to reproduce the problem in a fresh installation of NetBox v4.0.6 (I updated the issue body to fill in the gaps).
Thanks for your interest in improving NetBox!

I've moved this issue to `needs owner` status. If you're interested in working it through to a PR, please leave a comment to that effect and a maintainer will assign it to you for implementation. Otherwise, another developer with the necessary skills and capacity can pick it up.
