### ISSUE TITLE
Improve display for long-text custom fields

### ISSUE THREAD

**Issue by raphis** [netbox-community/netbox#16830]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.12

### Steps to Reproduce

1. Create a type "Text (long)" custom field for Devices
2. Save a very long text into this field
3. Access the device in the "read-only" view
4. The page gets very long and the user needs to scrol

### Expected Behavior

Use a defined height for the text (long) type of custom field and add a scrollbar as it's shown in the edit-view of an object.
<img width="875" alt="long-text_view" src="https://github.com/netbox-community/netbox/assets/7922644/4e0fb923-9571-40a6-837d-e47ab89f62d2">
<img width="601" alt="long-text_edit" src="https://github.com/netbox-community/netbox/assets/7922644/341769fa-44e8-47eb-84a0-230b18b6bd75">

### Observed Behavior

Page gets very long and user needs to scroll.

Consider this as rather a "room for improvement" than a real bug.

**Comment by jeffgdotorg** [comment]
Hi, and thanks for your interest in helping improve NetBox.

You're right that this issue falls somewhere between a bug and a feature, sometimes I call this kind a "bughancement". I think there's value in your issue, but it really needs to be framed as a feature so that the team can account for it. I'm therefore closing this issue, but I encourage you to create it again using the [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml) template – unfortunately there's no way to convert a GitHub issue from one type to another.

Thanks again, and I'm looking forward to seeing the follow-up FR issue.
