### ISSUE TITLE
Add PPS (COAX) port type

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#16999]
### NetBox version

v4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Update netbox/dcim/choices.py to include a new Coaxial type called PPS.

### Use case

Wikipedia references this page about it http://pos.mgb-tech.com/insightpps/.

Arista and others have devices with PPS interfaces like the 7130 series https://www.arista.com/assets/data/pdf/Datasheets/7135LB-Datasheet.pdf

**Comment by arthanson** [comment]
@ryanmerolle it looks like you have this in your codebase already, so assigning to you.

**Comment by jeremystretch** [comment]
My understanding is that [PPS](https://en.wikipedia.org/wiki/Pulse-per-second_signal) is a type of clocking signal, not a network interface. Is that incorrect?

**Comment by ryanmerolle** [comment]
That’s fair, but the only coax connector in netbox was docsis.  It’s definitely not that connector type.

Cisco, Arista, and several of the time sync appliance makers all have a coax connector they label as pps.  I’m happy to call it coax or any other name.

**Comment by jeremystretch** [comment]
It's not a network interface at all, so adding it as one would not make sense.

**Comment by ryanmerolle** [comment]
Yep but I have a PR ready.  I do not see a PR linked for that issue.

**Comment by bluikko** [comment]
Interesting, very interesting.

**Comment by ryanmerolle** [comment]
@bluikko can you explicitly state what port names need to be added in the linked issue so I can update the or?  Ie add the follow port names:
- port name 1
- Port name 2

**Comment by pobk** [comment]
I note thtat this is a duplicate request of:  #16334

**Comment by pobk** [comment]
The "mostly standard but some manufacturers want to be SPESHUL" standard is SMA for things like GNSS receivers et al. Timing interfaces are a bit of a quirky thing. 1PPS has implementations in RJ-11 RJ-45 SMA and I've seen older kit using standard N-type or F-type connectors too. It seems to be a coaxial thing...

I believe the ITU or IEEE might have said something on it, at some point, but I'm attempting to stay away from that rabbithole of woe and information overload at the moment.

Specifically, in this case, I think I can personally agree that this should not be an "interface" in the context of netbox but instead a front-port.

Also, as I've said elsewhere, just because it's not running IP, doesn't mean it's not a network... PTP networks exist.

**Comment by jeremystretch** [comment]
I'm going to close this for two reasons:

* "PPS" is not any type of physical connector at all. Rather, it is a [signaling specification](https://en.wikipedia.org/wiki/Pulse-per-second_signal).
* PPS is not used to transmit network data, and its termination would not be qualified as a network interface.
* It seems that some form of this has already been proposed in #16334. Please continue any further discussion in that issue.
