### ISSUE TITLE
Introduce a configuration parameter for signifying an offline or air-gapped deployment

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#17051]
### NetBox version

v4.0.8

### Feature type

New functionality

### Proposed functionality

Introduce a new boolean configuration parameter, e.g. `OFFLINE_DEPLOYMENT`, which is false by default. This should be set to true is NetBox is installed on a system without Internet connectivity, which may be the case in certain high-security environments.

### Use case

When this parameter is true, NetBox will omit any built-in external links, such as the footer links to GitHub and Slack. There are likely other instances of external references that may be addressed using this functionality.

### Database changes

None

### External dependencies

None

**Comment by mr1716** [comment]
One thing that would be great to include is that if Netbox is deployed in a way that isn’t connected to the internet, have a configurable setting for Netbox to use to point to the requirements that are already in a local directory. Therefore, instead of trying to download requirements from the internet, it would use that location instead and NOT try to download from the internet.

**Comment by jsenecal** [comment]
> One thing that would be great to include is that if Netbox is deployed in a way that isn’t connected to the internet, have a configurable setting for Netbox to use to point to the requirements that are already in a local directory. Therefore, instead of trying to download requirements from the internet, it would use that location instead and NOT try to download from the internet.

This, to me, is specific to the way one manages their python venv and has nothing to do with NetBox itself.
