### ISSUE TITLE
VLAN group scope selection fails for languages other than English

### ISSUE THREAD

**Issue by alexandre-jr-94** [netbox-community/netbox#17256]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9

### Python Version

3.10

### Steps to Reproduce

1.  try Netbox in Portuguese
2. go to VLAN Groups (Grupos de VLANS)
3. add a new group
4. In the "Scope" area, select "DCIM > Location" (DCIM > localização)

### Expected Behavior

It should show the options to select the region, site, and location.

### Observed Behavior

The options are not displayed, and when trying to save, the following error appears: _It is not possible to set scope_type without scope_id._

**Comment by jeremystretch** [comment]
This happens because [the Javascript responsible](https://github.com/netbox-community/netbox/blob/develop/netbox/project-static/src/forms/scopeSelector.ts) for dynamically updating the form fields depending on the selected scope type assumes English values (which is why "site" and "rack" work but the values with translated names fail). So this isn't Portuguese-specific, but impacts all translations generally.

The ideal solution here would be to ditch the relevant Javascript entirely, by enabling dynamic form rendering on the backend as we do for e.g. data sources.

**Comment by freestyler0815** [comment]
I have the same issue with the german translation. As workarround you can switch the user profile temporarly to english, enter the data in the vlan group settings and switch back to your language.
