### ISSUE TITLE
Add support for Infiniband GUIDs

### ISSUE THREAD

**Issue by ccope** [netbox-community/netbox#17295]
I would like to be able to configure a per-device System GUID, as well as a Node GUID for each port (ex: the [Nvidia Bluefield](https://docs.nvidia.com/networking/display/bf3dpu/finding+the+guid/mac+on+the+board#src-2449222587_safe-id-RmluZGluZ3RoZUdVSUQvTUFDb250aGVCb2FyZC1TdXBlck5JQ3NCb2FyZExhYmVs) card).

> From database point of view, varchar 59 seems fine.
> Relevant RFC:
> http://www.rfcreader.com/#rfc4391_line472
> http://www.rfcreader.com/#rfc4392_line84
> 
> IB Specs
> [IB Specification Vol 2-Release-1.4-2020-04-07.pdf](https://github.com/netbox-community/netbox/files/9453429/IB.Specification.Vol.2-Release-1.4-2020-04-07.pdf)
> 
> [IB Specification Vol 1-Release-1.4-2020-04-07 (3).pdf](https://github.com/netbox-community/netbox/files/9453428/IB.Specification.Vol.1-Release-1.4-2020-04-07.3.pdf)
> 
> _Originally posted by @zeronewb in https://github.com/netbox-community/netbox/issues/9781#issuecomment-1231705535_

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
