### ISSUE TITLE
Removal of an option in a CustomFieldChoice does not update objects with the choiceset and the option selected

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox#17558]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.1.1

### Python Version

3.12

### Steps to Reproduce

- Create a CustomFieldChoices with some options (A,B,C)

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/220f816b-379b-4170-9755-d80f9c9300d0">

- Create a Device Z
- Create a custom field of type selection with the CustomFieldChoices
- Assign the custom field to Device
- On Device Z, on the custom field,  assign choice B

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/079d8a7c-c863-4f76-a90a-cc5642801c34">

- In the CustomFieldChoiceSet delete option B

<img width="2254" alt="image" src="https://github.com/user-attachments/assets/57c3d219-6dae-4d80-9557-1bbd9af33121">

- View Device Z 

### Expected Behavior

The selected option on the choiceset attached to device Z should be null/none, due to the option removal 

### Observed Behavior

Option B remains until the object is edited or saved, despite no longer existing.

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/f5005d80-6a32-4f25-b17d-f70f21f0c62a">

Note - Due to the options inherent within ChoiceSets (eg: Non Null, default etc) but I'm trying to ascertain if this is a bug (ie: NetBox should warn/error on Objects with this choice selected) or expected behaviour - hence requesting feedback

**Comment by arthanson** [comment]
This should throw a validation error if you try to delete a choice and there are items assigned to that choice.

**Comment by bctiemann** [comment]
I think I agree with @goteamkor -- I can think of a lot of use cases where you would want to retain the data from a time when an option was available, but have that option not be available to select anymore. Like if you had a list of "Supported Devices" and you had previously assigned a value from that list to a "device" field on some other model; and then that device becomes no longer supported, so you remove it from the list. I'd much rather have the device field stay filled in, and allow the freedom to define the custom field choices such that that device is no longer offered as "supported".

**Comment by goteamkor** [comment]
We're not talking about opening the object and trying to save it again with the same value that is no longer a valid option. I'm talking specifically about the FR here, which is to alter the behavior of what happens when removing an option from a choice set.

The proposed change would make the removal of a choice set fail when trying to save because there are objects out there that still reference that choice set.
My statement was that just because a choice has been removed from a choice set and there are objects that still have that choice set shouldn't make the removal of the choice set fail.

You shouldn't have to go remove every reference to the choice before netbox will let you remove the choice from the choice set.
