### ISSUE TITLE
Object changes are not logged after upgrade to v4.1.9

### ISSUE THREAD

**Issue by koratfood** [netbox-community/netbox#18260]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.9

### Python Version

3.12

### Steps to Reproduce

1. [v4.1.8] Create site "Testsite1" with slug "testsite1" and otherwise default values
2. [v4.1.8] Edit site "Testsite1", enter "hello" in the Description field, and save
3. [v4.1.8] Delete site "Testsite1"
4. Upgrade to v4.1.9
5. [v4.1.9] Create site "Testsite2" with slug "testsite2" and otherwise default values
6. [v4.1.9] Edit site "Testsite2", enter "hello" in the Description field, and save
7. [v4.1.9] Delete site "Testsite2"

### Expected Behavior

All 6 changes are found in the Changelog.

### Observed Behavior

Only changes made in reproduction steps 1-3 (i.e. before we upgraded to v4.1.9) are found in the Changelog.

**Comment by tobiasge** [comment]
I noticed the same. The problem was likely introduced in this PR: https://github.com/netbox-community/netbox/pull/18225
The `event_tracking` request processor is not put into the registry.

**Comment by layer3lv** [comment]
Same problem in docker version

**Comment by abhi1693** [comment]
Webhooks are also not triggered. The related PR fixes that too.

**Comment by jeremystretch** [comment]
I tracked down why this regression was not caught by CI for PR #18225. When the change logging tests are run in isolation, they fail:

```
$ ./manage.py test --keepdb core.tests.test_changelog
Found 13 test(s).
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
FFFEEEEEEEEF.
...
```

This is because the `event_tracking` context manager is never imported, and thus does not get registered (which PR #18262 fixes).

However, when the entire test suite is run (as during CI), `event_tracking` is coincidentally [imported by a test module](https://github.com/netbox-community/netbox/blob/8c07978042e8c80259d7ad5b2b44c7adfc551716/netbox/extras/tests/test_event_rules.py#L20) for event rules, which happens to run _before_ the change logging tests.

Reliably checking for the registration of `event_tracking` in a test might prove difficult. Will have to give it some more thought.
