### ISSUE TITLE
Add the ability to query all available subnets of type (e.g /27) under a prefix via the api

### ISSUE THREAD

**Issue by StevenArmstrong** [netbox-community/netbox#2100]
### Issue type
[ ] Feature request 

### Description
After defining a top layer prefix of CIDR range /16, i want to be able to issue an api request to give me all available /27 ( as an example) subnets under the prefix based on what is available currently. Initially this will give /27 with all available permutations but not return them if they are being used. I could then create a /27 child subnet automatically with this information and set it to in use.

My use-case is I want to use netbox as a service of record for subnets, this will allow me to feed unique ranges to my automation scripts and request it from netbox. 

This feature request would mean my automation can programmatically call netbox, retrieve an available subnet and then use this information to create a unique subnet in the cloud provider.
 
At the moment you have similar functionality using "/api/ipam/prefixes/\<pk>/available-ips/"
I would like to see something similar for subnets so as an example "/api/ipam/prefixes/\<pk>/\<suffix>/available-subnets/" and be able to pass \<suffix> as a /27 or /29 etc and based on the prefix \<pk> return a list of what is available as a /27 or /29 range in terms of subnets.

**Comment by jeremystretch** [comment]
There's also the `available-prefixes` endpoint beneath a Prefix. This lists all available prefixes within the parent. For example, if you have allocated the first five /27s within a parent /24, this endpoint will list the remaining /27 and /26 as available. This endpoint also allows for automatic creation of new prefixes within the parent, with an optional `prefix_length` parameter.

We could extend this endpoint to accept a `prefix_length` GET parameter as well. The response would ostensibly include only the available prefixes meeting a certain size. So for example, say you have:

* 192.168.0.0/24
  * 192.168.0.64/26
  * 192.168.0.128/27
  * 192.168.0.176/28

A request for `GET /api/ipam/prefixes/<parent_pk>/available-prefixes/?prefix_length=27` would return:

* 192.168.0.0/27
* 192.168.0.32/27
* 192.168.0.192/27
* 192.168.0.224/27

Note that the first two prefixes are _not_ aggregated as a single /26.

**Comment by StevenArmstrong** [comment]
The available-prefixes gives me what I want in terms of creation, thank you, I just couldn't easily find the feature in the docs. For reference: 
Automatic Provisioning of Next Available Prefixes (#1694)
Similar to IP addresses, NetBox now supports automated provisioning of available prefixes from within a parent prefix. For example, to retrieve the next three available /28s within a parent /24:

curl -X POST -H "Authorization: Token <TOKEN>" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" http://localhost:8000/api/ipam/prefixes/10153/available-prefixes/ --data '[
{"prefix_length": 27}
]'

The additional get request, you proposed would be perfect, as it will allow me to query if any addresses of a particular type are left on the parent, instead of having to error handle the failed post request.
Instead I can query /27 from the parent. It returns a response listing the available ones and I can check the message and only then if correct response proceed with the subsequent POST request. It will also allow me to monitor when prefix allocations are getting low on available addresses.

**Comment by MarinBuljan** [comment]
Hi Jeremy,

sorry, probably this is already addressed question but we are having an issue.
Since we (as company) are considering Netbox to be primary tool for address management, we need to have automated prefix allocation from it using API
So what we need is to create prefix and then pull specific prefixes form that.
For example. /29.

So how can I make this in Netbox?
example
Define prefix 192.168.100.0/24 as parent prefix. I want to split this range to /29 subnets (how it could be done?)
How to get next available /29 from this range?
If I provision it manually, then I dont see it anymore in list when doing 

http://172.25.12.67/api/ipam/prefixes/?mask_length=29

Its look ling like this range then is occupied.

Anyway, can you please advice how it should be done?

Thanks in advance.

BR,
Marin

**Comment by DanSheps** [comment]
@jeremystretch The only thing I would add to that is have it check for things like "DHCP pool" and don't traverse into children of a DHCP pool.

**Comment by MarinBuljan** [comment]
> > Hi Jeremy,
> > sorry, probably this is already addressed question but we are having an issue.
> > Since we (as company) are considering Netbox to be primary tool for address management, we need to have automated prefix allocation from it using API
> > So what we need is to create prefix and then pull specific prefixes form that.
> > For example. /29.
> > So how can I make this in Netbox?
> > example
> > Define prefix 192.168.100.0/24 as parent prefix. I want to split this range to /29 subnets (how it could be done?)
> > How to get next available /29 from this range?
> > If I provision it manually, then I dont see it anymore in list when doing
> > http://172.25.12.67/api/ipam/prefixes/?mask_length=29
> > Its look ling like this range then is occupied.
> > Anyway, can you please advice how it should be done?
> > Thanks in advance.
> > BR,
> > Marin
> 
> Query the API like @StevenArmstrong does in his example. You can write a similair script in Python (using the requests library) or something in Ansible to fully automate a deployment (using the uri module.) Test your setup first using the curl on the command line.
> 
> To get the ID of the parent prefix, first query the API for the ID of the subnet. You'll get a JSON output so make sure you can convert the data / use the JSON path to extract the ID. The API url for this is http://IP/api/ipam/prefixes/?q=192.168.100.0/24 (parent prefix)
> 
> curl -X POST -H "Authorization: Token " -H "Content-Type: application/json" -H "Accept: application/json; indent=4" http://localhost:8000/api/ipam/prefixes/10153/available-prefixes/ --data '[
> {"prefix_length": 27}
> ]'

Hi,

thanks for tips.
Just started using it.
Do you know how to occupy certain subnet inside parent so that it will not be listed in available subnets?
For example, I want to request /29 range and somehow mark it so in next api call, this subnet will not be available anymore.
Tried all statuses...reserved, active, container but it does not help.
Noticed that it does not lists all subnets if at least 1 ip address is used inside certain subnet.
Then it list next free /x subnet.

Cheers.

Marin

**Comment by champidead** [comment]
> We could extend this endpoint to accept a `prefix_length` GET parameter as well. The response would ostensibly include only the available prefixes meeting a certain size.

It would be very useful. Any updates on this?
Thanks for NetBox!

**Comment by netvyper** [comment]
Looking into using netbox as a 'source of truth' for automating our network configuration & provisioning. I'd really like to see this feature implemented, so that I can query & choose an appropriate prefix, prior to actually allocating it at the end of the process assuming all the other steps are sucessful.
