### ISSUE TITLE
Add Tenant Groups in the list view for Prefixes list in the IPAM

### ISSUE THREAD

**Issue by zzj7513** [netbox-community/netbox#3093]
### Environment
* Python version:  2.7
* NetBox version:  2.5.3

### Proposed Functionality

    Add Tenant Groups in the list view for Prefixes list in the IPAM
    

### Use Case

    We have multiple teams manage/use the IP Prefix allocation inside the organization, to allow 
    different team to use the IPAM effectively, we pre-allocate existing big blocks to specific 
    teams, 
    the team name defined in Tenant Groups. As the use case, we need the team name in Tenant 
    Groups visible in the Prefix list view.

### Database Changes

    None

**Comment by jeremystretch** [comment]
All objects which support tenant assignment currently display only the assigned tenant and not the group. While it may be feasible to also display the tenant group, this needs to be implemented in a standard way across all objects, rather than only for prefixes.

I'm going to close out this issue as it has not garnered any further discussion.
