### ISSUE TITLE
Add filter to select cables by termination sites

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#3259]
### Environment
* Python version:  2.7.5
* NetBox version:  2.5.13

### Proposed Functionality
Would like to have the ability to list cables filtered by the site assigned to either or both of the termination endpoints.

### Use Case
The goal is to be able to pull up inventories of all the equipment associated with a particular site. Currently there is no straightforward/convenient way to do this for cables.

### Database Changes
None that I would expect.

### External Dependencies
None.

**Comment by coppit** [comment]
The cables UI is not scalable. Consider 15 sites and 300 cables each. That's 4500 cables presented as pages in the UI. Because there's no substring matching for device name, one cannot use naming conventions to help filter down to a specific site.

I also find it odd that devices are listed in the "Stats" box for a site, but cables are not. If this feature is implemented, that could be rectified with a simple link with a "?site=foo" filter in the URL.

**Comment by candlerb** [comment]
If adding filter cables by site, can we have filter by rack as well please!
