### ISSUE TITLE
Add QSFP+ 100gb to x4 SFP+ 25gb break-out cable

### ISSUE THREAD

**Issue by jjbninja** [netbox-community/netbox#3334]
### Environment
* Python version:  
* NetBox version:

**Comment by jjbninja** [comment]
Was this cable added? Did I fill out my request correctly?

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by DanSheps** [comment]
Further, breakout cables have been discussed before and declined due to the current cable/interface model.  Please search as this will also result in this being closed as a duplicate
