### ISSUE TITLE
Racks: Allow to flip and adjust unit-numbering

### ISSUE THREAD

**Issue by neufeind** [netbox-community/netbox#3339]
There is a boolean to indicate descending unit-numbering (implemented with #191). But once you change that flag for an existing rack all devices change their positions as well and the rack gets flipped upside-down (technically correct). Would it make sense to allow flipping rack-numbering once you toggle that boolean? And maybe to be able to mass-adjust numbering by +/- a few units, just in you figure out you missed to count as well one unit on the top or bottom as well?

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
