### ISSUE TITLE
Indicate that 0 day changelog retention means forever

### ISSUE THREAD

**Issue by jlrgraham23** [netbox-community/netbox#3368]
### Environment
* Python version:  All
* NetBox version:  3.6.1

### Proposed Functionality

Correctly indicate that a changelog retention setting of 0 days is treated as indefinite on changelog pages.

### Use Case

The current templates will read "Changelog retention: 0 days" if 0 is selected for indefinite retention.  This is confusing to some users.  Explicitly state the meaning of 0.

### Database Changes

None.

### External Dependencies

None.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jlrgraham23** [comment]
Please re-open, restored all template content...
