### ISSUE TITLE
Search for MAC-address in virtual devices

### ISSUE THREAD

**Issue by quentinsch** [netbox-community/netbox#3386]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.1

### Proposed Functionality
As requested in an earlier issue (#663) it would be nice if you could search for a MAC-address in virtual machines.
Just like the same way it is implemented for Devices there should be a MAC address filter search field on the right in the virtual machine overview.

### Use Case
In troubleshooting situations it is very convenient if you can search for a MAC address. It is already implemented for physical devices but not yet for virtual devices.

### Database Changes
To be determined.

### External Dependencies
None

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by quentinsch** [comment]
@jeremystretch, edited the issue with the correct template, would you please consider opening the issue again?
