### ISSUE TITLE
Tenancy for Power Feeds

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3394]
It would be helpful if power feeds could be assigned to tenants and groups too, like devices and racks to document which feed is dedicated to which customer.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
