### ISSUE TITLE
Unify status options

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3395]
It looks like the Status dropdown has a wide range of varying options. Wouldn't it make sense to have them unified so every dropdown list has the same options?

Here are a few:
- Powerfeed: Active, Offline, Planned, Failed
- Device: Active, Offline, Planned, Staged, Failed, Inventory, Decommissioning
- Rack: Active, Planned, Reserved, Available, Deprecated
- Circuit: Planned, Provisioning, Active, Offline, Deprovisioning, Decommissioned
- Virtual Machine: Active, Offline, Staged
- Cluster: (no status)
- Cable: Planned, Connected

I noticed because I wanted to set a powerfeed to Reserved. It would make sense to merge all them into a single list only which is sorted by "on/off", eg:
Active
Inactive
Online
Offline
Connected
Disconnected
Available
Unavailable
Provisioning
Deprovisioning
Decommissioned
Deprecated
Planned
Staged
Reserved
Failed

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
