### ISSUE TITLE
Manufacturer - The results could not be loaded.

### ISSUE THREAD

**Issue by khangcnttspkt** [netbox-community/netbox#3398]
![Manufacturer](https://user-images.githubusercontent.com/26158447/62529118-382b9280-b868-11e9-8d71-53ca2e28ae41.PNG)

May I can do for this issue, please?

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by khangcnttspkt** [comment]
> This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

Hi DanSheps. I had edit my issues. Can you reopen my topic for help. Thank you.

**Comment by khangcnttspkt** [comment]
I update my case 
![image](https://user-images.githubusercontent.com/26158447/62690052-2d9f0380-b9f6-11e9-8cad-5755412e13e8.png)

**Comment by sconwayubb** [comment]
I had a similar issue with Tags. It turns out that the users seeing this error did not have permission to view tags. I suspect if you add the "View Manufacturer" permission to your user/group, this problem will go away.
