### ISSUE TITLE
Total parameter on Physical device link with Virtual machine

### ISSUE THREAD

**Issue by khangcnttspkt** [netbox-community/netbox#3437]
### Environment
* Python version:   3.6.8
* NetBox version:   2.6.2

### Proposed Functionality

Add field Memory, Disk, CPU,... on physical device.

When we have physical device with total memory, disk. And after add virtual machine with virtual memory, disk, vcpus, ... on to physical device. The total components on physical device will be decreased.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
