### ISSUE TITLE
Netbox IP pinging

### ISSUE THREAD

**Issue by towfiquepbl** [netbox-community/netbox#3438]
Hi, I am new here, started working in Netbox. I manually imported IPs.
but the requirement is to know  'If all the IP is still active or not like after 2 months'.

so need to do the pinging by netbox. Any suggestions please ?

TIA

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
