### ISSUE TITLE
Cable's total length 

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#3440]
### Environment
* Python version:  3.6 
* NetBox version:  2.6.1

### Proposed Functionality
Show add up to all links lenght since first near end until last far end

### Use Case
In most cases, a cable routing has many segments. It's neccesary show the complete lenght cable routing. It isn't necessary to store this value in the database but it's necessary to convert all of them in the same measurement unit.

### Database Changes
It's not necessary

### Example

![imagen](https://user-images.githubusercontent.com/51785108/63427515-35ef3980-c40d-11e9-87c2-8df1ac2fb5aa.png)

**Comment by lmgonzalezl** [comment]
Hi.
I show you another example of a cable that we have and in which it would be quite useful to know the total length at first sight. This simulates a connection between two switches.

![imagen](https://user-images.githubusercontent.com/51785108/63435567-1103c200-c41f-11e9-92b2-352b754b09a5.png)

**Comment by tb-killa** [comment]
I am currently thinking about how best to work here.
I would suggest to add the length within the view https://github.com/netbox-community/netbox/blob/770f4c962cf4bfb5d44bf7cc6ac5f1e080e0cd7f/netbox/dcim/api/views.py#L67 and later in the template 
[https://github.com/netbox-community/netbox/blob/develop/netbox/templates/dcim/cable_trace.html](https://github.com/netbox-community/netbox/blob/develop/netbox/templates/dcim/cable_trace.html)
to reproduce.

Since each segment is output as a three-tuple of (termination, cable, termination), the cable also contains the respective length (cable.length).
