### ISSUE TITLE
No permissions for anonymous user

### ISSUE THREAD

**Issue by Toosaman** [netbox-community/netbox#3443]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.2

Anonymous user can't access any sections on portal, while "LOGIN_REQUIRED = False" in configuration.py

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
