### ISSUE TITLE
Vagrant bootstrap.sh typo

### ISSUE THREAD

**Issue by davetayl** [netbox-community/netbox#3446]
Currently lines 89 and 93 of the vagrant bootstarp.sh script are the same. So it looks like NAPALM drivers aren't being loaded.

```
# Load Initial Data (Optional) Comment out if you like
printf "Step 18 of 19: Load intial data."
python3 /opt/netbox/netbox/manage.py loaddata initial_data > /dev/null

# Install NAPALM Drivers
printf "Step 19 of 19: Installing NAPALM Drivers"
python3 /opt/netbox/netbox/manage.py loaddata initial_data > /dev/null

```

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

Just as a FYI, vagrant is not handled by the core Netbox team, so this would also be closed due to that.
