### ISSUE TITLE
WebHook should provide old data together with new data

### ISSUE THREAD

**Issue by robertpenz** [netbox-community/netbox#3447]
We've implemented a Webhook which gets informed for IP address and service changes, the problem now is that we only have the new values and not the old values. e.g. the dns_name field is changed from bla1.example.com to bla2.example.com we are only seeing the second name in the webhook call. This makes it impossible to delete the old DNS record and add the new one.  We also took a look at the change log and even there only the new name is shown. 

This makes is quit impossible to trigger stuff directly from the netbox which needs to know the old value to clean up.

Please provide the old values along with the new ones in the webhook call.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
