### ISSUE TITLE
active user keys

### ISSUE THREAD

**Issue by dudusf04** [netbox-community/netbox#3477]
Hi ,

I have a problem that can't activate the user keys, i already have multiple users but only one has the key enabled, that user is gone and we don't know his netbox password and he's not superu user, is there any way to get me to help.

### Environment
* Python version:  
* NetBox version:

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
