### ISSUE TITLE
Fix typo in color names

### ISSUE THREAD

**Issue by clatini** [netbox-community/netbox#3517]
Fix typo in color name that appears in color picker: **Fuchsia**, not **Fuschia** :-)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
