### ISSUE TITLE
Region search box - Circuits page

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#3529]
Environment
NetBox version: 2.6.1

Proposed Functionality
Utilize the Region filter via a from search box on the GUI Circuits page. This allows users circuits to filter their connections to a particular region.

Use Case
When viewing circuits, operations and management quite often want to see all the circuits by a geographical location. Eg Continent or Country.

Database Changes
None expected, assuming that the region module can be referenced.

External Dependencies
None

**Comment by DanSheps** [comment]
I think we will need to investigate the performance implications of this.

Right now, you would have to look at the circuit terminations in order to get a site, it there is a site, you then need to go to the regions table.  A few joins and depending on what you have, could slow down queries significantly.

**Comment by jeremystretch** [comment]
Turns out we already have a `region` filter in place for circuits; just need to add the form widget on the circuits list.
