### ISSUE TITLE
Page Not Found after editing tag name

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#3571]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.5

### Steps to Reproduce
1. Have a tag named "Testing"
2. Go and edit the tag name to "Changed name"

### Expected Behavior
Tag data is shown.

### Observed Behavior
"**Modified tag Changed name**" and "**Page Not Found**" ("The requested page does not exist"), and the URL is https://netbox.server.local/extras/tags/testing/ (which is pointing to the slug of the old tag name)

**Comment by jeremystretch** [comment]
Looks like the issue here is that the URL associated with the edit button on the tag view appends a return URL with the ta's current slug (e.g. `/extras/tags/foo/edit/?return_url=/extras/tags/foo/`). This forces a redirect to the old slug even after the new slug has been saved.

Note that this does not happen when editing the tag directly from the tags list (because no `return_url` parameter is passed).
