### ISSUE TITLE
Add Config Context change tracking

### ISSUE THREAD

**Issue by chonty** [netbox-community/netbox#3578]
### Environment
* Python version:   3.5.1-3
* NetBox version:  2.6.5

### Proposed Functionality
Config Context change tracking

### Use Case
Config Context change tracking would allow for external versioning and review.  

If an automation tool is using this information to fill templates and configure devices, you'd want to ensure that the stored information is correct.  Whilst you could do this by hand, when you're dealing with tens+ of config context objects, it would quickly become tedious and you could still miss small, subtle changes to the text content.

### Database Changes
Unknown

### External Dependencies
Unknown

**Comment by jeremystretch** [comment]
> Add Config Context change tracking + webhooks

These would be two separate feature requests. I'm going to edit this issue so that it applies only to the change logging ability. Feel free to open up a separate FR for the webhook portion, however I don't think it makes sense to enable webhooks for ConfigContexts as they are not "real" objects: A device or VM may receive an arbitrary combination of data from various ConfigContexts depending on how they are applied.

**Comment by sdktr** [comment]
Interesting to know whether a change in a configcontext currently triggers a webhook for the indirectly (eg via site) attached entities🧐

**Comment by jeremystretch** [comment]
@sdktr No, it doesn't. Only direct changes to an object will trigger an associated webhook.

**Comment by jarora11** [comment]
@jeremystretch Any idea when this would be move from gathering feedback to slated for implementation?

**Comment by jeremystretch** [comment]
This was implemented in v2.9 under #4840. My mistake; I hadn't realized there was already an issue open for this.
