### ISSUE TITLE
Add Platform Version as child model to Platform

### ISSUE THREAD

**Issue by ReK42** [netbox-community/netbox#3593]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.5

### Proposed Functionality
Add a child model to Platform named Platform Version. Devices could then select either the platform in general or a specific version of it. If the version-specific fields, such as NAPALM driver and arguments, are null they should inherit the values on the base platform, otherwise they should override them.

### Use Case
Platforms can include major version changes that significantly affect functionality and feature set, or even the NAPALM driver required to access them (e.g. Cisco NX-OS prior to version 6.1 requires using nxos_ssh instead of nxos).

This would also add the ability to track major version changes and use that to aid in lifecycle management. This should not extend into minor version tracking and patch targeting, as that is very vendor-specific and can be accomplished through other means, such as an OS version field on the device.

For example, virtual machines could have the following platforms:
- CentOS
  - CentOS 6
  - CentOS 7
  - CentOS 8
- Windows Server
  - Windows Server 2012
  - Windows Server 2012 R2
  - Windows Server 2016
  - Windows Server 2019

### Database Changes
Add a new model, PlatformVersion, with a foreign key to Platform.

### External Dependencies
None

**Comment by Grokzen** [comment]
Woudl all current platform relations have to be migrated to the new PlatformVersion object instances? And would all current relations that is in the code point to this new object? I dont know if you would really point to the old Platform any longer then since if you have to choose between Platform and PlatformVersion it would make the code much more messier. Alternative solution might be to make Platform model a Tree model then you can make any tree relation that you want and you still keep the Platform model and dont have to change any code that enables us to point to a Platform object.

**Comment by ReK42** [comment]
You're right, it would be easier to have devices link to a single model rather than two possible ones, but since this is a simple one-level hierarchy you could do that by simply creating a hidden PlatformVersion instance with the same properties as the Platform.

**Comment by jeremystretch** [comment]
This has been raised before and the solution is to simply include the version number in the platform name. So instead of having a hierarchy with CentOS and Windows Server at its root, you would have a flat list:

- CentOS 6
- CentOS 7
- CentOS 8
- Windows Server 2012
- Windows Server 2012 R2
- Windows Server 2016
- Windows Server 2019

This should be acceptable as the total number of major versions is likely to be relatively low. And if you need to track specific versions down to the minor/patch level, a custom field is probably more efficient anyway.

**Comment by ReK42** [comment]
The intention behind having the hierarchy is so that entries can still be aggregated and displayed together despite being separate major versions. That way a user could go to /dcim/devices/?platform=cisco-ios and see both IOS 12 and IOS 15 devices, for example.

**Comment by jeremystretch** [comment]
This can be done by combining filters:

`GET /api/dcim/devices/?platform=cisco-ios-12&platform=cisco-ios-15`
