### ISSUE TITLE
Add Json Viewer/Editor for local_config_context

### ISSUE THREAD

**Issue by csv7** [netbox-community/netbox#3595]
## Proposed Functionality
When creating/viewing local_context_data via netbox gui, include below mentioned library & changes to html templates to enable user-friendly editing of the context data.

## Use Case
Some users aren't great at editing json. Adding an external editor would greatly simplify the use of local_context_data for some. 
This one looks nice: 
* http://www.daviddurman.com/flexi-json-editor/jsoneditor.html
## External Dependencies
* http://www.daviddurman.com/flexi-json-editor/jsoneditor.html
which has these dependencies:
* jQuery
* JSON (use json2 library for browsers that do not support JSON natively)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
