### ISSUE TITLE
IPAM - IP request form 

### ISSUE THREAD

**Issue by ghostfelix** [netbox-community/netbox#3610]
Hello, 

Can you integrate an IP request form feature into IPAM. This could come in real handy as now for us, we are following a paper based method. If you can include IP request form it would be much appreciated. 

Thanks

**Comment by Grokzen** [comment]
I guess you can build this yourself with CustomScript now if you are running the latest version of Netbox. You can build any custom script and form if you follow this https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
