### ISSUE TITLE
Provide hi-res logo for hi-res displays

### ISSUE THREAD

**Issue by altokarev** [netbox-community/netbox#3631]
Provide hi-res logo for hi-res displays (`@2x` e.g.).

It looks kinda blurry on hi-res displays atm.

<img width="285" alt="Screenshot 2019-10-22 at 17 52 10" src="https://user-images.githubusercontent.com/28726429/67298995-c113ab00-f4f4-11e9-87d9-54ee6d920c70.png">

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by altokarev** [comment]
Hmm.

Is it necessary to use a template for such an issue? Really?

An issue doesn't fit any items listed in the template in fact.
