### ISSUE TITLE
Filter Devices dropdown in Connect view

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#3640]
### Environment
* Python version: Python version: 3.6.8
* NetBox version: NetBox version: 2.6.5

### Proposed Functionality
In the **dcim/interfaces/xxx/connect** view - filter the Device list based on type of connection to be made.

When clicking to connect an interface and selecting, say, Front port, the subsequent view's Device dropdown (in the B-side panel...) should be filtered so that only devices actually having front ports are listed.

### Use Case
Well, when patching stuff, it is a bit annoying having to scroll or type in order to get to the desired device quick. For instance, there are usually only at most a handful of patch panels in a rack - but usually a whole bunch interfaces to be patched there. It would be much more convenient if the list was pre-filtered based on what kind of destination port is actually to be patched to... 

### Database Changes
Not an expert here, but I believe it's purely a change in the controller / view (?).

### External Dependencies
none

**Comment by jeremystretch** [comment]
> When clicking to connect an interface and selecting, say, Front port, the subsequent view's Device dropdown (in the B-side panel...) should be filtered so that only devices actually having front ports are listed.

I understand the motivation behind this, but I have to reject it because the confusion this would cause among novice users (which would manifest itself in the form of erroneous bug reports). Imagine the frustration you'd feel after creating a new device, then trying to create a connection from a different device to it and the new device doesn't appear in the list of available devices. With the current approach, it's immediately apparent that the device is there but is missing a suitable component to complete the connection.
