### ISSUE TITLE
rack_group missing from power feed add/view

### ISSUE THREAD

**Issue by bellwood** [netbox-community/netbox#3647]
### Environment
* Python version: 3.6.9
* NetBox version:  2.6.6

### Steps to Reproduce
1. Import a new power feed, fill all fields (including the rack_group)
2. View the feed

### Expected Behavior
Feed add/view should include rack_group

### Observed Behavior
Feed add/view is missing rack_group

### Additional Details
Pursuant to: 800df1ebbe151b21dae14f96d950afbe35b10e68

Edit: Sorry for so many edits... Powerfeeds as a whole need to be reviewed to add in rack_group. It's also missing from the sidebar search, there's no heading for it when listing all power feeds, etc.

**Comment by kobayashi** [comment]
Power panel view shows Both Rack Group and Power Feeds. Is it not good? 

![Screenshot from 2019-11-02 03-27-16](https://user-images.githubusercontent.com/8712070/68067649-d2448f00-fd20-11e9-917f-a4e638cd5210.png)

**Comment by bellwood** [comment]
We've a lot of common naming in our IX unique to individual rack groups. Having to jump to a power panel just to see what rack_group its' in versus having it right with the rest of the data in view is sub-optimal from a work flow standpoint.

I suppose leaving it out of the tabular list of power feeds is OK if we can add filtering by rack_group in that view.

**Comment by kobayashi** [comment]
I would like to know more about your point. At power panel list view, you can search desired rack group and see the relation between rack group and power feed inside the searched power panel. Does this not fit your workflow?

If we would add rack_group to the page, we have to retrieve nested objects. This may effect for other pages now. This is because the list and search are included from shared template files which show related objects excluding nested for the display object.

**Comment by kobayashi** [comment]
@bellwood do you still have any comments for this?
