### ISSUE TITLE
Editing device location->position

### ISSUE THREAD

**Issue by danielpda** [netbox-community/netbox#3649]
### Environment
* Python version:  
* NetBox version:  

### Steps to Reproduce
1. Select a Device
2. Edit the Device
3. Go to Position - Location 
4. Change Location
5. Broke  

### Expected Behavior

List display with the units in the rack

### Observed Behavior

Keeps waiting with the searching symbol
![Screenshot_20191028_172057](https://user-images.githubusercontent.com/53618738/67714805-67edc080-f9a7-11e9-9b76-976b7c28773d.png)

Sorry but my english is not so fluent, inquiries are welcome!

**Comment by lampwins** [comment]
There have been numerous issues opened on this bug #3521

In the future please be sure to look through the closed issue list and before opening a bug report, verify the bug is reproducible on the latest version of netbox. In this case, you would have found that the issue has been resolved in the latest release.
