### ISSUE TITLE
Ability to search by DNS when 'Assigning new IP' address to device

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#3668]
### Environment
* Python version: 3.7.3 
* NetBox version: 2.6.6 

### Proposed Functionality
When assigning an IP address to an interface that exists on the device pagevia the green "+" sign you are presented with a page with two options, 'new' and 'assign IP'. 

We have all usable address in IPAM, so would 'assign' one. In the 'Assign an IP Address' page there is only the option to search via IP address and not DNS. Many of the infra would like the ability to search for an applicable IP address via DNS name and not IP address.

### Use Case
Other non network team members should be able to update their IP address details of their infrastructure and wish to use DNS rather than IP address

### Database Changes
No known changes required.

### External Dependencies
No known changes required.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by robbagithub** [comment]
Issue has been updated with a fuller description of the functionality required

**Comment by jeremystretch** [comment]
Rescuing this one from stalebot as it should be trivial to implement.
