### ISSUE TITLE
Function for License Management

### ISSUE THREAD

**Issue by dops84** [netbox-community/netbox#3688]
Can we get a Module for license Management in Netbox?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
