### ISSUE TITLE
Duplicate Cable ID via API Call

### ISSUE THREAD

**Issue by AstritCepele** [netbox-community/netbox#3698]
### I am using library Pynetbox but i assume that it will create the same result via Postman/any app API
1. Get the details via API of a Cable Number
2. Update Termination A id into a different port on the same device

The Cable ID will be unique and it will change its Termination A id and port 

2  The cable ID was duplicated on both connections.
Image it is providen: 
![Capture](https://user-images.githubusercontent.com/22580457/69128305-449cc980-0aac-11ea-9703-f3d0fd93a588.PNG)
https://16057066842229083094.googlegroups.com/attach/63ea6f6505d06/Capture.PNG?part=0.1&view=1&vt=ANaJVrGNhtZU9d_elPFoyBhbhW3fa9eYTh4fPi9WVNZhhl7YUhwiUUwP7V1v4JeEFxDF8V3o-FwMYCbsyo6tloaHKx7oKSVvm4_0Jcwd1Eo2PhnaDrHwkCE

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

Please also note that the provided steps to reproduce need much more detail to be actionable.

**Comment by AstritCepele** [comment]
> Netbox: v2.5.10
> Python: 3.6.3
> 
> ### Steps to Reproduce
> ### I am using library Pynetbox but i assume that it will create the same result via Postman/any app
> 1. PUT request to : /dcim​/cables​/{id}​/
> 2. Body : {termination_a_id* , termination_a*}  -> insert the details for a different port on the same device.
> 
> The Cable ID will be unique and it will change its Termination A id and port
> 
> 2 The cable ID was duplicated on both connections.
> Image it is providen:
> ![Capture](https://user-images.githubusercontent.com/22580457/69128305-449cc980-0aac-11ea-9703-f3d0fd93a588.PNG)
> https://16057066842229083094.googlegroups.com/attach/63ea6f6505d06/Capture.PNG?part=0.1&view=1&vt=ANaJVrGNhtZU9d_elPFoyBhbhW3fa9eYTh4fPi9WVNZhhl7YUhwiUUwP7V1v4JeEFxDF8V3o-FwMYCbsyo6tloaHKx7oKSVvm4_0Jcwd1Eo2PhnaDrHwkCE

Content Changed
