### ISSUE TITLE
Make current user available in Custom Scripts

### ISSUE THREAD

**Issue by 2bithacker** [netbox-community/netbox#3705]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.7

### Proposed Functionality

Make the currently logged in user available to Custom Scripts. It may be beneficial to make the entire `request` context available, but all I need currently is the user.

### Use Case

In my use case, we have a policy of commenting on Prefixes with the user who allocated and assigned the prefix to a site. I'm attempting to automate this process using a Custom Script, but currently need to ask the user for their username, despite them being logged in.

### Database Changes

None

### External Dependencies

None

**Comment by hellerve** [comment]
I’m not personally using that kind of context, so I can’t say much, but I do think that spending a minute to think about what properties of the request context might make sense to be shared might be worthwhile.

I don’t think that sharing the whole request is necessarily a good idea. While I think custom scripts are inherently trusted, there is just no need to expose the `session`, for instance. This might seem ridiculous (because the script already has access to Python and its capabilities anyway), but I think that it actually makes sense to not expose those bits of “sensitive” information anyway.

**Comment by jeremystretch** [comment]
@hellerve While I appreciate the security consciousness, I don't think there's anything in the request context that could be considered more privileged than the access already given to a script (which is essentially everything). Given that a custom script can already do things like create users and reset passwords, providing access to the session ID and other request parameters isn't much of a concern.
