### ISSUE TITLE
Custom status for Circuits

### ISSUE THREAD

**Issue by mmarin11** [netbox-community/netbox#3713]
Is it possible to add custom status to circuits? Or is it recommended to use custom fields for this purpose?

Thank you

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
