### ISSUE TITLE
LAG ports can’t span multiple stack members

### ISSUE THREAD

**Issue by millijuna** [netbox-community/netbox#3723]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.7

I have a 3 switch Cisco 3750 stack which is connected to another switch via a two port LAG. Each of the LAG members is on a different stack member. 

In netbox, the LAG is (for some reason) attached to member :1 of the stack. when I try to add the member interfaces (from stack members 2 and 3), the interface editing interface can’t find the LAG on stack member 1.

Edit: this happens when the LAG wasn’t created on the stack master.

### Steps to Reproduce
1. Create a 3 member stack
2. Create a LAG interface on one stack member
3. Try to add an interface from another stack member to that LAG. Can’t be done.

I expect that I would be able to add any interface from any stack member to the LAG.

**Comment by hSaria** [comment]
I believe this is due to how the list of `vc_interfaces` is acquired, namely the condition below. Only the master of a virtual chassis is allowed to see the interfaces of other members in the same virtual chassis.
https://github.com/netbox-community/netbox/blob/1048d3909b9e5fe96acc793c35bbbe9820dacefb/netbox/dcim/models.py#L1820

**Comment by jeremystretch** [comment]
@hSaria is correct: The LAG interface must be created on the stack master. Non-master members can only see their own interfaces.
