### ISSUE TITLE
Vertical Power Outlet

### ISSUE THREAD

**Issue by TawR1024** [netbox-community/netbox#3733]
Hi,, it will be cool to introduce the ability to create vertical blocks of remote control sockets

For example we use [APC Vertical mount PDU ](https://www.apc.com/shop/id/en/products/Rack-PDU-Basic-Zero-U-32A-230V-20-C13-4-C19/P-AP7553)

Type of rack:
PU small blocks where we can install PDU
DevU are simple blocks where we place devices.

| Pu | devU | Pu |

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
