### ISSUE TITLE
Add VXLAN/VNID support

### ISSUE THREAD

**Issue by rogerwiklund** [netbox-community/netbox#3738]
### Environment
* Python version:  3.7.5
* NetBox version:  2.6.7

### Proposed Functionality

Add support for VXLAN VNID in IPAM section.

### Use Case

EVPN-VXLAN is getting to be the defacto standard in modern Datacenters. It would be great if we can document the 24bit VXLAN VNID in the IPAM section. Typically a VNI is tied to a VLAN.

**Comment by DanSheps** [comment]
Duplicate: #2800 #1800 #1725 #1058 #825 #777

As this point, this can be accomplished with a custom field on the VLAN and the maintainer team unfortunately has more core functionality to look at.

While this itself would be trivial, if this was something to be added it should be added properly with all pieces of vxlan otherwise the team will just start getting FRs for all other features (documenting vteps, documenting the underlay, etc)
