### ISSUE TITLE
Region relations not shown correctly

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#3742]
In the regions view, relations are shown trough a right-caret. If I create some Regions and take a look at the regions table view, the relations are not correct.
I've attached screenshots of this issue.

I am using v2.6.6.

![Screenshot_2019-12-10 Editing region 85551 - Kirchheim - NetBox](https://user-images.githubusercontent.com/2934508/70514834-a1802280-1b34-11ea-9478-2cce0059efd5.png)
![Screenshot_2019-12-10 Editing region 85609 - Aschheim - NetBox](https://user-images.githubusercontent.com/2934508/70514836-a1802280-1b34-11ea-87d9-02aea5e7dcb2.png)
![Screenshot_2019-12-10 Regions - NetBox](https://user-images.githubusercontent.com/2934508/70514838-a218b900-1b34-11ea-9460-b89ff606ba30.png)

**Comment by tb-killa** [comment]
Hi please rework your issue to be confirm with the template.
Otherwise this will be closed by Admins.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by hSaria** [comment]
For the record, I wasn't able to reproduce this in v2.6.7 (haven't checked 2.6.6).

**Comment by basti1508** [comment]
I will update the issue tomorrow to follow the guidelines.
