### ISSUE TITLE
Custom field - multiple selections

### ISSUE THREAD

**Issue by HaehnleinMar** [netbox-community/netbox#3744]
Note: This issue is a possible duplicate of #2522.

### Environment
* Python version:  3.7.5
* NetBox version:  2.6.7

### Proposed Functionality

I want to be able to select multiple values in custom fields of type "Selection" like I can with eg. Tags.

![Screenshot from 2019-12-10 13-06-58](https://user-images.githubusercontent.com/9468979/70532131-b2419000-1b56-11ea-8a36-cf7f77bd21a1.png)

### Use Case

I use NetBox as the source of truth for deploying Virtual Machines. I want to give my users the ability to pre-install software on virtual machines. For this I want them to be able to select multiple values from a custom field of type "Selection".

### Database Changes

I honestly have no Idea.

### External Dependencies

None

**Comment by jeremystretch** [comment]
Unfortunately many-to-many relationships are not supported by the data model used to store custom field values, and changing it would require disproportionate development effort.

> I want to give my users the ability to pre-install software on virtual machines.

Tags might be better suited for this task.

**Comment by jdorel** [comment]
I would like to add another use case for this feature: assigning ansible groups to devices/vms.

**Comment by jeremystretch** [comment]
@jdorel Tags work very well for that.

**Comment by jdorel** [comment]
I currently use tags for this, but it makes it harder to coexist with other systems, because of possible namespace collisions. For example I would like that some ansible variables be in Netbox.

For now I have to prefix every tag for group assignation with `ansible_group:`, and every ansible variable with `ansible_variable:`. Having a custom field for that would be perfect.

Although I could use a text field with values separated by spaces, I wouldn't work for variables holding strings.

Maybe the solution would be just adding a `list` type in the custom fields ?
