### ISSUE TITLE
Summary power port allocated draw per rack

### ISSUE THREAD

**Issue by nqvan** [netbox-community/netbox#3770]
### Environment
* Python version:  
* NetBox version:  

### External Dependencies
Hi all,

Currently I see netbox is only calculated allocated power value of feed per rack. Can netbox calculate device power ports allocated draw per rack?

Regards

**Comment by hSaria** [comment]
This'll get closed unless you conform to the issue template. Just warning you before a maintainer sees this :)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
