### ISSUE TITLE
Tenants history

### ISSUE THREAD

**Issue by timopotam** [netbox-community/netbox#3777]
Hello, is it possible to add a function such as "History of device tenants" or is this function already in place? So when you go into any device you can see not only standart information, but also the history of the device tenants.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
