### ISSUE TITLE
Regions incorrectly displayed

### ISSUE THREAD

**Issue by walday** [netbox-community/netbox#3778]
### Environment
* NetBox version:  2.6.8

New installation, after add some regions view this image:

![2019-12-19 18_07_24-Regions - NetBox](https://user-images.githubusercontent.com/59055055/71175945-86c35180-228a-11ea-9737-83df69db2a3e.png)

In footer regions incorrectly displayed

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
