### ISSUE TITLE
Duplicates in use

### ISSUE THREAD

**Issue by getbin** [netbox-community/netbox#3790]
# hi,
I found some problems in NetBox (v2.6.10-dev). I have a lot of IPs. I tried to bind 10.10.10.1 in server A. When I rebind 10.10.10.1 in server B, it didn't have any Prompt, when I click "10.10.10.1", she prompts me "Duplicate IP Addresses", this response is not timely, a little less obvious. Can you provide options or hints when binding the IP?
### G

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
