### ISSUE TITLE
Add Fans to Device Component List

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#3825]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.9

### Proposed Functionality

Add a component type for fans.  The data model would include:

- Model/Part Number: Required
- Serial Number: Optional (only for device and not device type)
- Air Flow Direction: Required (default option is front-to-rear with a second choice of rear-to-front) - Could use a boolean in the data model

### Use Case

Air Flow is an important DCIM feature that is currently missing.  Operators may want to track and eventually audit their DCs to verify airflow direction.

### Database Changes

Add a new data model type with the fields mentioned in the proposed functionality.

### External Dependencies
None

**Comment by hSaria** [comment]
This seems like something already covered by inventory items.

**Comment by tb-killa** [comment]
This could be combined with the Floorplan issue who actually is already opened.

**Comment by jeremystretch** [comment]
> Air Flow is an important DCIM feature that is currently missing.

NetBox allows users to track airflow direction by DeviceType model number. For instance, Juniper has two part numbers for its QFX5100-48S switch:

* `QFX5100-48S-AFI` (front-to-back airflow)
* `QFX5100-48S-AFO` (back-to-front airflow)

I believe the catalyst for this FR was the realization that the device type definitions for two devices in this scenario are identical, except for the model number suffix. There is a desire for a a mechanism to differentiate airflow without having to create otherwise duplicate device types.

There is no need to introduce a new component model for fans, as the InventoryItem model already provides the ability to distinguish airflow direction by the fan module part number (e.g. `QFX5100-FANAFI` versus `QFX5100-FANAFO`).

A related but separate FR (which is what I had anticipated from the discussion) would be the introduction of a new field on the DeviceType model to indicate airflow. This would obviate the need for tracking airflow by model number at all. But again, this would need to be a new FR with a separate discussion.

> This seems like something already covered by inventory items.

Just to reiterate, this is correct: fans should be modeled as inventory items..
