### ISSUE TITLE
Adding existing IP to interface

### ISSUE THREAD

**Issue by rmrf-run** [netbox-community/netbox#3940]
Running latest release 2.7.0

Went to add existing IP to interface and received an error of

`module 'ipam.filters' has no attribute 'IPAddressFilter'`
Debug error points to 
`addresses = filters.IPAddressFilter(request.POST, addresses).qs[:100]`
https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/views.py#L763

I changed it to `addresses = filters.IPAddressFilterSet(request.POST, addresses).qs[:100]` and was able to search for the existing IP to attach to interface

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
