### ISSUE TITLE
Device Components Region Filter bug

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#3966]
### Environment
* Python version:  3.7
* NetBox version:  2.7.1

### Steps to Reproduce
1. Go to the Device components page eg interfaces
eg. https://netbox/dcim/interfaces/
Error occurs for all components
2. Select a region and click search by apply
Following is an example of the url generated. https://netbox/dcim/interfaces/?q=&region=34&site=

### Expected Behavior

Filter appears of the components as per the region selected

### Observed Behavior

Netbox crashes with the following error

Request Method: | GET
Request URL: | http://netbox/dcim/interfaces/?q=&region=99&site=
Django Version: | 2.2.9
Exception Type: | TypeError
Exception Value: | 'Region' object is not iterable

Note this issue has been verified by other netbox users.

**Comment by kobayashi** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
Please provide both Expected/Observed behavior.

**Comment by kobayashi** [comment]
Sorry, I found this was discussed in mailing list.

**Comment by kobayashi** [comment]
Region filtering for interface is provided in 2 ways.
1. `regin` which requires region slug to filter.
2. `region_id` which requires region id.

Could you try `region_id=99` if you are filtering by region id? Or `region=<your region name>` .

**Comment by darcynz** [comment]
Hi there,

Ill try tomorrow, but i was filtering via the gui so i would expect it uses
the correct value.

Regards

**Comment by jeremystretch** [comment]
Closing this as it does not conform to the bug report template. Please modify your issue so provide _all_ of the required information and then request that it be re-opened.

**Comment by darcynz** [comment]
Bug updated, please reopen and/or let me know if more detail is required.
