### ISSUE TITLE
Add console connection settings field (baud rate)

### ISSUE THREAD

**Issue by alexjhart** [netbox-community/netbox#3975]
Please add the ability to track baud rate of the console port on a device. From connecting adhoc to configuring a console server, this information saves time when connecting. Since the defaults vary, and can often be changed, it's important to track this information somewhere, why not where you already have the port and type defined in Netbox? While other settings could also be tracked, this is the most common to vary between devices, so it's an easy place to start. While you could go with a common list (such as https://en.wikipedia.org/wiki/Serial_port#Speed), this could just be an integer field rather than a selection. It could also just be a generic serial connection settings text field.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
