### ISSUE TITLE
Remove unused jQuery file

### ISSUE THREAD

**Issue by mtbutler07** [netbox-community/netbox#3981]
### Proposed Changes
Remove the (seemingly) unused jQuery library (v1.12.4) from the project-static directory.
[netbox/project-static/jquery-ui-1.12.1/external/jquery/jquery.js](https://github.com/netbox-community/netbox/blob/develop/netbox/project-static/jquery-ui-1.12.1/external/jquery/jquery.js)

### Justification
1. I could not find where this version of jQuery was actually being used.
2. Vulnerability scanner is flagging the library and referencing XSS vulnerabilities CVE-2019-11358

**Comment by jeremystretch** [comment]
NetBox merely packages the `jquery-ui` release as published. We are currently including the most recent release, although it appears a bug has been opened for this upstream: https://bugs.jqueryui.com/ticket/15353

As we don't have the development resources to pick apart the library and determine for certain whether it is safe to do so, I'm extremely hesitant to simply remove the file. Doing so may break components of the UI that we are unable to reliably test for ahead of time.

I think it's fair to defer to the user: If required to satisfy whatever compliance checks are in place, go ahead and delete the file from your local installation as a workaround (with the understanding that components of the UI _might_ break). Otherwise, we'll wait for the packaged library to be addressed upstream.
