### ISSUE TITLE
Unable to create stacked LAG bondings

### ISSUE THREAD

**Issue by MartinK07** [netbox-community/netbox#3991]
The current implementation makes the creation of a stacked LAG bonding impossible. Although a LAG parent can be selected during modification, on conformation the following error gets promoted: "Link Aggregation Group (LAG) interfaces cannot have a parent LAG interface."

Stacking bonding interfaces might be uncommon for network devices, but under Linux it is possible to define is currently in use (two LACP bondings grouped together as Active-Passive for HA)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
