### ISSUE TITLE
Update the nginx documentation

### ISSUE THREAD

**Issue by smutel** [netbox-community/netbox#4024]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

In the nginx configuration, the line below:

```
proxy_set_header X-Forwarded-Host $server_name;
```

should be replaced by this line to take account of port used to reach netbox:

```
proxy_set_header X-Forwarded-Host $http_host;
```

In the previous configuration, nginx assume that you are calling it on port 80. So the next field on the JSON response when you call the API only contains port 80.

**Comment by jeremystretch** [comment]
LGTM, but I want to ensure including the port number won't break anything. Per [Django's documentation](https://docs.djangoproject.com/en/2.2/ref/settings/#use-x-forwarded-host) this should be fine.

Testing confirmed that when listening on a default HTTP port (i.e. 80), the port number is omitted from the URLs returned in API responses when `$http_host` is used, so that should not be an issue.
