### ISSUE TITLE
Interface Bulk Import Exception when adding interfaces to virtual machines

### ISSUE THREAD

**Issue by dealer-san** [netbox-community/netbox#4036]
When bulk adding interfaces to virtual machines, Netbox throws an exception:

![2020-01-28 182920](https://user-images.githubusercontent.com/3180981/73317592-3978bf00-41fc-11ea-9eaa-b2d3b306ad94.png)

Example input data:

virtual_machine,name,type
hostname,eth0,virtual

Import seems to work without problems when importing for devices. Was able to reproduce issue in both v2.7.2 and v2.7.3.

**Comment by DanSheps** [comment]
Are you using interface import under devices?

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by dealer-san** [comment]
Correct.

I've updated the original bug report to actually use the template. Note to
self: don't try to quickly submit bug reports when the wife is hungry and
impatient.
