### ISSUE TITLE
Next/Previous device buttons in Device view

### ISSUE THREAD

**Issue by rkerr** [netbox-community/netbox#4061]
### Proposed Functionality

In the Rack view there are Next Rack and Previous Rack buttons to cycle through racks in a site. These are quite useful, however similar functionality is missing from other screens. I would suggest adding this to the Device view in order to allow you to cycle through other devices in the same rack.

### Use Case

When making a change I often find it is a change that affects a number of devices that are physically next to each other in the same rack. It would save some clicks to be able to go direct to the next device in the rack having completed an edit.

**Comment by kobayashi** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
