### ISSUE TITLE
Collapsing / filtering DHCP addresses in prefix - IP address view?

### ISSUE THREAD

**Issue by crazyman143** [netbox-community/netbox#4070]
Hi,

I'd like to ask a question and reference [#857](https://github.com/netbox-community/netbox/issues/857), which was closed for inactivity.

 We have some large ipv4 prefixes (/16's). And the majority of IPs in these are DHCP. 

I have less savvy users in here documenting their servers etc. They prefer to find a prefix by description and then drill down (IPAM > Prefixes > *click* > IP Addresses tab). They're getting frustrated with all the DHCP addresses they have to page through on that view.

 Could there be a way to apply a filter option here to hide them? I can do it from the main "IP Addresses" view. But I have to filter by the prefix I want as well. server admins struggle with this because they don't know what the masks or network IDs are. 

Any advice on how to make this easier?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
