### ISSUE TITLE
Install docs addition - redis

### ISSUE THREAD

**Issue by squigley** [netbox-community/netbox#4073]
The documentation is missing instructions to make sure redis is started (and enabled), so when you run the migration script, for a new install, it fails as it cannot connect to redis.

I suggest adding the following to the redis section:
```
Make sure that redis is started and enabled to automatically start at boot.

Ubuntu

# service redis-server start
# systemctl enable redis-server
CentOS

# service redis start
# systemctl enable redis
```

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by squigley** [comment]
This is ridiculous. The documentation is broken when you follow it verbatim. I try to fix it, and get people putting more effort into arguing with me about how I submitted the way to fix it, than just fixing it. Waste of my time. I won't bother again.
