### ISSUE TITLE
Add a VLSM tree with GraphViz

### ISSUE THREAD

**Issue by NRGLine4Sec** [netbox-community/netbox#4076]

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
