### ISSUE TITLE
New functions [4 offers]

### ISSUE THREAD

**Issue by ArtemSannikov** [netbox-community/netbox#4157]
### Environment
* NetBox 2.7.4
* Python 3.6.9
* OS: Ubuntu 18.04 LTS

### Proposed Functionality

1. Maximum input power allowed for new device is 32 kWatt, but we have ones with input power of 277 kWatt.

2. We need a function to hide the electric connection types that are not used in the region. Certain types of electrical connectors are needed to be added, including: Hard Wire 3 wire (1PH+N+G), Hard Wire 5-wire (3PH + N + G).

3. We need you to add a sections titled “Endpoint” for cameras / phones / PCs / MFPs. Each section should include fields: Name, MAC address (required parameter), IP address (primary default), Vendor (default - insert automatically according to MAC address field), Model, PoE Consumption, Bandwidth.

4. Changelog of object contains the last input only. But we need the whole history: what was changed, what was a new input, or what was added / deleted (specifically if the object contains of lots of fields / entities).

**Comment by hSaria** [comment]
You would usually open a separate feature request for each of the items above.

1. I agree with this request. Some considerations must be made with regards to how much power can be available from a power feed with the current limitations.
2. The hiding part is a bit out of reach, I would imagine. As for adding the electrical connectors, I think that's acceptable.
3. Such an endpoint would generally be addressed as a device with sub-interfaces, because that's what they are actually. PoE interfaces is already in #1099. Power consumption is already an existing functionality (create a device, add a power port to it with the maximum and allocated power, and connect it to a power outlet/feed). I'm not too sure what you mean by bandwidth.
4. This is being addressed in #2511

Though again, multiple feature requests are put into their own individual issues in an effort to track any work.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
