### ISSUE TITLE
Search by 'Custom fields'

### ISSUE THREAD

**Issue by ArtemSannikov** [netbox-community/netbox#4201]
### Environment
* NetBox 2.7.4
* Python 3.6.9
* OS: Ubuntu 18.04 LTS

### Proposed Functionality

Make it possible to search ‘IP Addresses’ by ‘Custom Fields’

**Comment by heineek** [comment]
I confirm that in version 2.7.4 search by custom field value doesn't work (search request returns all objects). But It works on my test docker-version 2.6.7

**Comment by heineek** [comment]
I have updated to version 2.7.6, search by custom fields is working now.

**Comment by jeremystretch** [comment]
If you believe this to be a bug, please submit a new issue using the [bug report template](https://github.com/netbox-community/netbox/issues/new?template=bug_report.md) including the steps to replicate the issue on the latest stable release. However, it looks like you're running into #4091, which was fixed in NetBox v2.7.5.
