### ISSUE TITLE
Only save a (partial) record if at least something changed

### ISSUE THREAD

**Issue by neufeind** [netbox-community/netbox#4203]
(I already mentioned it in #2511 but now see it was a bit out of scope for that other issue. So here is a separate feature-request.)

Maybe it would be possible to only create a changelog-entry (or save something at all) if settings changed. We had the case where a script updated various entries using the PATCH-method using the API and writing values to existing entries. But it didn't first download the current values and check if there was a difference. Maybe Netbox could detect that the diff was actually empty (all values already current) and then simply not creating a diff / an entry in the changelog.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
