### ISSUE TITLE
Negative Voltage Support on Power Feeds

### ISSUE THREAD

**Issue by craized** [netbox-community/netbox#4205]
In telecommunications, it's very common to receive -48V DC power feeds. I would like to propose support for negative numbers on power feed voltage, or a boolean to signify negative voltage.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by craized** [comment]
Hi Dan, this was my first time posting to this project, sorry for missing the requirements. I've updated the request and would appreciate getting it reviewed again
