### ISSUE TITLE
Add option to assign a Rack in bulk edit

### ISSUE THREAD

**Issue by 33Fraise33** [netbox-community/netbox#4268]
### Environment
* Python version:  /
* NetBox version:  2.7.3

### Proposed Functionality
Add the option when editing multiple devices to assign a Rack to them. Face and Unit are optional items so I think it should be possible to add this in the bulk edit. 

### Use Case
When moving multiple devices from one location to another it comes in handy to be able to move lots of devices to a rack at a time. 

### Database Changes
None I can think of, frontend change. 

## External Dependencies
/

**Comment by jeremystretch** [comment]
We've considered this in the past, but there are a number of validation issues such that the feature is useful only when none of the devices have a position or face assigned. For example, moving two devices each in their own rack in position 10 to a single new rack will obviously fail, as both devices cannot exist in the same position. (And we can't simply nullify the assigned positions because that can lead to unexpected results; such as if the user didn't realize the devices were in the same position.)

What I'm getting at is that if we implement the feature, it's often _not_ going to work as expected and users will become frustrated.

**Comment by 33Fraise33** [comment]
It might be an option to move those 2 devices into the new rack but then not racked. Moving non racked to non racked is the main use case here. 

For us this is the main use case but I understand that this is not the only use case out there. It might be an option to give a popup in case of conflichts. An other nice option would be to be able to 'edit' a rack and drag and drop devices onto a rack unit (front or back). Saving fills in all the rack units on the devices. (This might be another feature request but together might be a good solution)

**Comment by jeremystretch** [comment]
Passing on this proposal as there have been no further comments and IMO it's likely to cause more problems than it solves. It might be easier to address in the future once we've adopted a fully API-driven front end.
