### ISSUE TITLE
Display device name and image simultaneously in rack elevations

### ISSUE THREAD

**Issue by jennec** [netbox-community/netbox#4317]
### Environment
* Python version:  
* NetBox version:  2.7.8

### Proposed Functionality
Device Images (Front and Rear) in Rack elevations to have have an opaque overlay with the device name label showing.  Possibly as another toggle button next to show images if this is not a preferred state.  the overlay could also be coloured as per the device color coding.  my example uses approx 20% opacity.  
![Rack Device Image Name Proposal](https://user-images.githubusercontent.com/4245161/75995654-a74b9100-5ef4-11ea-90df-5ee0b529fb33.png)

### Use Case
The example image above should provide enough idea of what it could look like.  

The Rack views and elevations look great with front and rear images, views, but without the device label it doesn;t really help identify the device.  Yes you can hover over the device to see it, but this is time consuming and not very efficient.  

Allowing for colour codes and labels to be overlayed would provide the best of both current view options.  

### Database Changes
none that I am aware of.

### External Dependencies
No additional dependencies as far as I am aware.

**Comment by jeremystretch** [comment]
You have two different feature requests here. Please choose one and open a separate FR for the other.

**Comment by jennec** [comment]
Done, split into two requests as requested: 

Second Request: #4331

**Comment by DanSheps** [comment]
If this is accepted, I feel like it may be best to make it optional/toggleable.

**Comment by jeremystretch** [comment]
I played around with this while working on #1529. Even with a tint, a complex background image makes the text very difficult to read, particularly at a small size. (Note that the default size of a rack unit in NetBox is much smaller than the screenshot above appears.) And if you increase the opacity of the overlay, the image becomes obscured, defeating the point of including it at all. Ultimately it's a poor design choice to try and convey two pieces of information on top of each other, which is why we went with the option to toggle between image and text.

**Comment by ktims** [comment]
A contrasting outline on the text works quite well.

**Comment by jennec** [comment]
Although I woudl prefer a variations on what I suggested, having toggle to enabled this would be a good options as well.

An alternative would be to have a label floating to either side of the device.  Without any label the Rack elevation doesn;lt convey to someone who is not familiar with the Rack contents what devices are being show.
