### ISSUE TITLE
LDAP authentication fails after upgrade to 2.7.9

### ISSUE THREAD

**Issue by Carbenium** [netbox-community/netbox#4328]
### Environment
* Python version:  3.5.3
* NetBox version:  2.7.9

### Steps to Reproduce
1. Upgrade to v2.7.9 and run upgrade.sh
2. LDAP authentication fails

### Expected Behavior
LDAP authentication still works after upgrade

### Observed Behavior
With the recreation of the venv after each upgrade optional packages like `django-auth-ldap` are not reinstalled.

**Comment by dstarner** [comment]
So that is because `django-auth-ldap` is not in the `requirements.txt` file due to it being an optional dependency / configuration setting. [In the documentation concerning LDAP auth](https://netbox.readthedocs.io/en/stable/installation/5-ldap/#install-django-auth-ldap), it explicitly says that you need to manually install it. Not sure if we want to add an option to the `upgrade.sh` script like `--ldap-enabled` that will add as well.

**Comment by dstarner** [comment]
This is a duplicate of #4322

**Comment by Carbenium** [comment]
Yep, I really didn't see that issue...
