### ISSUE TITLE
Markdown Tables Broke Somewhere in the 2.7 train

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#4343]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.10

### Steps to Reproduce
Insert a table using the example markdown netbox references in https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

All other Markdown seems to render

It worked in 2.6 train, and I am pretty sure it worked earlier in 2.7 train.

### Expected Behavior
Render the table:

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

### Observed Behavior
Shows the markdown code as one line & does not render:

| Tables        | Are           | Cool  || ------------- |:-------------:| -----:|| col 3 is      | right-aligned | $1600 || col 2 is      | centered      |   $12 || zebra stripes | are neat      |    $1 |

**Comment by ryanmerolle** [comment]
I personally use tables to show inventory of spares at a site that are not in a rack like cables and sfps

**Comment by jeremystretch** [comment]
We ditched py-gfm in NetBox v2.7.10 because it was pinning Markdown to a very old release (v2.6.11) and no longer appears to be maintained. The inclusion of the admonition and fenced_code extensions were meant to maintain feature parity for our purposes but it appears support for tables was overlooked.

I was under the impression tables were included in core, but it looks like we have to enable an [extension](https://python-markdown.github.io/extensions/tables/) for them.
