### ISSUE TITLE
Multiple Mac address on same physical link

### ISSUE THREAD

**Issue by ba31** [netbox-community/netbox#4399]
### Environment
* Python version:  3.7.5
* NetBox version:  2.7.10

### Use Case
Like firewall , windows cluster could have same mac address across multiple VLAN on same physical trunk link.

### External Dependencies
Do not know because I am netbox user not developer.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
