### ISSUE TITLE
class 'pkg_resources.VersionConflict' after v2.7.11 upgrade

### ISSUE THREAD

**Issue by CraigRMoore** [netbox-community/netbox#4437]
### Environment
* Python version:  3.5.6
* NetBox version:  2.7.11

### Steps to Reproduce
1. From the list of tenants select an existing tenant
2. Error occurs 
3. Try and add a new tenant
4. Error occurs

Tenant form or new tenant form appears

<class 'pkg_resources.VersionConflict'>

(setuptools 28.8.0 (/opt/netbox-2.7.11/venv/lib/python3.5/site-packages), Requirement.parse('setuptools>=36'))

**Comment by candlerb** [comment]
@CraigRMoore, what OS are you running Netbox under?

This problem started in 2.7.10, and I reported this under [Ubuntu 16.04](https://groups.google.com/d/msg/netbox-discuss/hxvLVblGdKc/q7hIAKUOHwAJ).  There are three other reports [here](https://groups.google.com/forum/#!topic/netbox-discuss/QquDZFgjlhI), [here](https://groups.google.com/forum/#!topic/netbox-discuss/ArMjPCsN4uU), [here](https://groups.google.com/forum/#!topic/netbox-discuss/FUeuMqs7sUk) but those don't say what OS is involved - possibly CentOS 6/7?

Workaround:

```
echo "setuptools>=36" >local_requirements.txt
./upgrade.sh
```

**Comment by jeremystretch** [comment]
As discussed on the mailing list, this is not a NetBox bug. The error is occurring because you're running a very outdated version of `setuptools`, and `pip` doesn't enforce the requirement above (`setuptools>=36`) for whatever reason. (`setuptools` gets installed automatically when creating a virtual environment.). If anything, this is a bug in pip, or possibly `pkg_resources`.

You can work around it by upgrading your **system** installation of `setuptools`, then running the upgrade script again:

```
# pip install -U setuptools
# ./upgrade.sh
```

Pip should then install the updated `setuptools` release when the virtualenv is created. Like most Python projects, we don't track it as an explicit dependency.

**Comment by candlerb** [comment]
I note that someone on the list had upgraded their setuptools to 46.1.1 and still got the problem:
<https://groups.google.com/forum/#!topic/netbox-discuss/ArMjPCsN4uU>

In any case, can I politely suggest that the requirement to upgrade setuptools be mentioned in the installation/upgrade documentation.  It was not necessary prior to 2.7.10, and it's becoming a frequent support issue.

**Comment by CraigRMoore** [comment]
Thanks very much Brian,

Apologies for not noticing the previously logged cases…
We are running CentOS 7.4.1708

Regards,

Craig.

**Comment by CraigRMoore** [comment]
Just confirming that I have upgraded setuptools to 46.1.3 on Centos 7.4.1708 and that has fixed the problem.
