### ISSUE TITLE
IP address penetration VRFs

### ISSUE THREAD

**Issue by getbin** [netbox-community/netbox#4451]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.11

Now, there is an IP address of / 32, and the binding device can freely choose the VRF range,
For example, I have
1.1.1.0/24
2.2.2.0/24
When I add device IP, I can set VRF of 1.1.1.2/32 to 2.2.2.0/24. This is not supposed to be.

My suggestion is that the front end automatically judges the IP prefix and shortens the options for users to set VRF.

**Comment by hSaria** [comment]
I don't think that's a bug. You can have the same prefix in two different VRFs – those are two different routing tables after all.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
