### ISSUE TITLE
Put some function to add users who have to assign an IP address or laptop to be sure that such hostname belongs to that user.

### ISSUE THREAD

**Issue by H4ckW0lf** [netbox-community/netbox#4477]
Hello NetBox team, it would be interesting to put some function to add users who have to assign an IP address or laptop to be sure that such hostname belongs to that user, I am using the tool again and from what I have seen it does not have that option when you go to a tenant.

It would be great if there is a section where it says accounts and in it you can add user account + name + description + IP + desktop + hostname that belongs to it.

Regards,

**Comment by sdktr** [comment]
You should try to refit this issue in a template. https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md

**Comment by kobayashi** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely). THX @sdktr!
