### ISSUE TITLE
Relative URL Issue on Rack Elevation Page?

### ISSUE THREAD

**Issue by eabrodie74** [netbox-community/netbox#4498]
Apologies in advance if this is a duplicate of an issue already raised. I set my web port to 81, and while all links throughout the NetBox site reference the absolute URL, <ip>:81/...., the device links on the rack elevation page all point to http://netbox/...

Is this expected behavior, or a bug?

Thanks!
Evan

**Comment by kobayashi** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
