### ISSUE TITLE
IPMI Interface

### ISSUE THREAD

**Issue by Sislik** [netbox-community/netbox#4535]
### Environment
* Python version:  3.6.4
* NetBox version:  2.8

### Proposed Functionality
Add IMPI interface to default selections of interfaces types

### Use Case
Each physical server is having IPMI interface (iLO, iDRAC, iLOM). These interfaces are used for management only and there is no point of having for them specific as 100base-tx or 1000base-t. Also it will be easier for searching for these IPMI interfaces across all servers.

**Comment by tioan** [comment]
First i think you mean IPMI not IMPI.
Second this issue is needless because IPMI interface also have an interface type.

**Comment by Sislik** [comment]
Yes it is having interface type, but all depend for the whole purpose of the IPMI (thx for correction :)) It can then be up to the user if he want to have them specified by exact type of interface or just by basic definition.
As i want to be adding by scripts around 100k devices (just discovery by ipmitool on linux or powershell in windows) im just more than happy to receive the IP/Mask/MAC and that it is IPMI.
Anyway it is just suggestion :)

**Comment by DanSheps** [comment]
IPMI is not an interface type, we only track interface types like ethernet

**Comment by jeremystretch** [comment]
The interface model also has a "OOB management" boolean field specifically for this purpose.

**Comment by schmitmd** [comment]
@jeremystretch , I know this issue is closed, I just want to ask a related question: Is there already a way to add something like a Custom Link to a /dcim/device/ object that would do something like open a URL to the OOB management interface?  I'm not seeing anything that I can use in the existing device model that would help my Jinja2 template be able to get the correct data for this (except primary_ip which isn't quite right).  Am I missing something? Would you suggest I make a new issue for this?
