### ISSUE TITLE
Unintelligible codes from export csv file 

### ISSUE THREAD

**Issue by 463024907** [netbox-community/netbox#4539]
Environment

- Python version: python/eoan 2.7.17-1 amd64

- NetBox version: (v2.7.11)

Steps to Reproduce
I get the answer through google which says the problem is "Chinese is included in the csv fil."
 and also it reminds me "I need to add "utf_8_sig" to file header;"
how should I modify the code ?

**Comment by kobayashi** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
