### ISSUE TITLE
Super-VLAN (RFC3069) Support

### ISSUE THREAD

**Issue by garrymar** [netbox-community/netbox#4668]
Dear netbox developers,

It would be nice to have an ability to add super-VLANs in netbox, which are described in RFC3069 (multiple VLANs sharing the same IP prefix). The feature is very popular among internet service providers.

I suppose it can be implemented using two approaches:
- allow /32 IPv4 prefixes to be added to netbox;
- have an opportunity to bind individual IPv4 addresses to VLANs

Thank you for this extremely useful software!

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
