### ISSUE TITLE
can't update virtual machines data using import

### ISSUE THREAD

**Issue by anutator** [netbox-community/netbox#4716]
netbox 2.8.5
python 3.6.8

I update Linux machines info using Ansible and get correct value memory and hdd size in csv file.
But I can't update this fields using import. For example this fields:
`cluster,name,vcpus,memory,disk`
I have an error:
```
Enter the list of column headers followed by one line per record to be imported, using commas to separate values. Multi-line data and values containing commas may be wrapped in double quotes.

    Row 1 name: A virtual machine with this name already exists.
```
I can only import NEW virtual machines but can't change properties of already existing machines.
Besides there is Required option "cluster". But I'd like to have only required option name while editing virtual machines.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
