### ISSUE TITLE
Netbox Applications (Very Interesting)

### ISSUE THREAD

**Issue by fireman0865** [netbox-community/netbox#4750]
Hello dear ,
I have been working for a while in Netbox as python/django for an enterprise but my mission is ending in one month .I have developed many plugins and the most important is the application plugin .
I will pull it in my Github sooner and will let you know .
I would like also to have your thoughts .
Here is some screenshot
Thanks
![cap1](https://user-images.githubusercontent.com/3670561/84482749-30aaf600-ac90-11ea-8a3d-1f3a6ff7959a.PNG)
![cap2](https://user-images.githubusercontent.com/3670561/84482762-33a5e680-ac90-11ea-9ea5-4aa9046e3287.PNG)
![cap3](https://user-images.githubusercontent.com/3670561/84482776-36a0d700-ac90-11ea-834d-1497db505a53.PNG)
![cap4](https://user-images.githubusercontent.com/3670561/84482789-39033100-ac90-11ea-9bde-46b646842808.PNG)
![cap5](https://user-images.githubusercontent.com/3670561/84482806-3d2f4e80-ac90-11ea-90ed-abd579603b65.PNG)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
