### ISSUE TITLE
assign a virtual ip to multiple devices

### ISSUE THREAD

**Issue by aradmueller** [netbox-community/netbox#4763]
Can an ip address object be assigned to multiple cluster devices, for example a firewall cluster active/active or active/passive? A virtual IP (VIP) should be assignable to two interfaces of two diffentent cluster devices.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
