### ISSUE TITLE
Display user full name in Change Log

### ISSUE THREAD

**Issue by mathieu-mp** [netbox-community/netbox#4785]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.5

### Proposed Functionality
Display user full name beside/instead of its raw username, namely in Change Logs.\
This could be offered through a `configuration.py` option, or become standard behavior.

On front page, "username - 2020-06-23 14:41" would become "John Doe (@username) - 2020-06-23 14:41" or just "John Doe - 2020-06-23 14:41"\
The enhancement would also affect User column on Change Log tabs for any object.

### Use Case
A raw username is not always relevant to easily identify the real person beyond, namely when the username is retrieved from an AD and the AD policy leads to obscure ids.\
Displaying the full name would ease the identification of users, and users would be able to associate any change with a team-mate to call to discuss changes or solve issues.

### Database Changes
Full name value is already available when displaying personal profile, but the API only shows id and username properties.\
Only assuming: a new field might have to be created inside the User model. Any change to first or last name inside the admin panel should propagate to this value. Again, i can only assume as I have very little programming skills and I did not dive into this part of the code.

### External Dependencies
Probably none

**Comment by jeremystretch** [comment]
The username is displayed because it is guaranteed to be defined and unique, which cannot be said for a user's optional first and last name attributes. Like most applications, NetBox assumes that you're using meaningful usernames to represent individual users.

There is a second reason for this as well: An ObjectChange instance records both a reference to the User instance as well as a static representation of the username. This ensures that the attribution of a particular change to a user remains intact even after the user is deleted from NetBox.
