### ISSUE TITLE
Cannot add new devices to a rack via csv import

### ISSUE THREAD

**Issue by jholecek** [netbox-community/netbox#4800]
Hello,
when I was trying to add new devices via Import csv I always got this message:

> Server Error
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> <class 'dcim.models.Device.device_type.RelatedObjectDoesNotExist'>
> 
> Device has no device_type.
 
It's related to Netbox v2.5.8.

Thanks and best regards,
Jakub

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
