### ISSUE TITLE
Markdown angle brackets link issue

### ISSUE THREAD

**Issue by DeemGit** [netbox-community/netbox#4845]
From markdown manual:

_URLs and URLs in **angle brackets** will automatically get turned into links. 
http://www.example.com or <http://www.example.com> and sometimes 
example.com (but not on Github, for example)._

`netbox/utilities/templatetags/helper.py`
```
@register.filter(is_safe=True)
def render_markdown(value):
    """
    Render text as Markdown
    """
    # Strip HTML tags
    value = strip_tags(value)
```

but `strip_tags` will automatically cut off such tags and this markdown won't work.
example : markdown `<` http://google.com `>`  is just removed in comments.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
