### ISSUE TITLE
Searching by MAC address

### ISSUE THREAD

**Issue by lps-rocks** [netbox-community/netbox#4869]
### Environment
* Python version:  3.7.6
* NetBox version:  2.8.7

### Proposed Functionality

Allow global searching of objects via MAC address.

### Use Case

This is one of the most common search mechanisms used by networking administrators when tracking down an unknown device or a device that may not be operating properly. 

### Database Changes

Possibly an index on the mac field for interfaces

**Comment by mskalecki** [comment]
Searching by MAC already works well, with the caveat that you need to know if you're looking for a physical device or VM, and you need to do the search using the MAC Address filter in the list view for Devices or Virtual Machines respectively.

In practice, those caveats aren't a big deal, because you can quickly learn to identify VMs by the first 6 characters of their MAC address (the OUI).  For example, if I see 00:15:DB, I know it's a Hyper-V VM, and if I see 00:50:56, I know it's a VM on my VMWare cluster.

**Comment by lps-rocks** [comment]
Thank you for those spots, I expected the search field to be associated with the model that the mac address is tied to.

Interestingly enough, the 'Interfaces' list /dcim/interfaces/ (which is the model the mac address is tied to) does not have a mac address search field. 

May be worth adding the mac address filter to the 'interfaces' page as well as the global search capabilities.

**Comment by jeremystretch** [comment]
> Allow global searching of objects via MAC address. Also, add the ability to search by MAC on the 'dcim/interfaces' in the GUI.

These proposal need to be tracked as two separate feature requests. Please pick one and update your initial post; you may open a separate issue for the other.

**Comment by lps-rocks** [comment]
> > Allow global searching of objects via MAC address. Also, add the ability to search by MAC on the 'dcim/interfaces' in the GUI.
> 
> These proposal need to be tracked as two separate feature requests. Please pick one and update your initial post; you may open a separate issue for the other.

Done.
