### ISSUE TITLE
Please implement moving ends of a cable

### ISSUE THREAD

**Issue by ThomasGiger** [netbox-community/netbox#4881]
### Environment
* Python version:  unknown - using a pre-installed system
* NetBox version:  2.8.7

### Proposed Functionality
Haven't found a way to move one end of a cable from one port/interface of a device to another one. The cable needs to be deleted and another one needs to be added, as it seems.

### Use Case
One could have made a mistake while adding a cable or the change is to reflect something that happens in pratice - it would be a real time-saver if one end or both of a cable could be reassigned to some other port/interface without havin to deleted and re-add the cable, which is a some work at least if you care about type, color, label and all those details.

### Database Changes
This appears to be a UI enhancement, so none expected.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Blocked by #4900

**Comment by raddessi** [comment]
This is no longer blocked with the addition of 4900 correct?

**Comment by jeremystretch** [comment]
Open for volunteers under v2.11.

**Comment by eronlloyd** [comment]
I'd love to see this get implemented, and would donate towards a bounty if needed.

**Comment by hellerve** [comment]
We have an implementation for this in a plugin that I’d be happy to try to port to the core of NetBox instead. Making it part of the core would also enable different interactions (via the tables directly rather than cabl detail, which is how it currently happens in the plugin).

I’d be happy to contribute the initial version and then iteratively refine the interface based on the desired UI/UX.

**Comment by hellerve** [comment]
I added a (working) draft containing the work I had at hand. Let me know whether the UX works for y’all!

**Comment by Nothing4You** [comment]
unstale
