### ISSUE TITLE
Support for Etag and Last-Modified in API response

### ISSUE THREAD

**Issue by EppO** [netbox-community/netbox#4917]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.12

### Proposed Functionality

Implement [Etag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Etag) and/or [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) response headers for the netbox API.
I would allow to reduce the load on the netbox API with the information provided by the client (etag and/or If-Modified-Since headers).

### Use Case

Today, when you send a request to the netbox API, you don't get much information of the "freshness" of the data in the response headers:

```
> GET /api/virtualization/virtual-machines/?name=mytestvm HTTP/1.1
> Host: netbox.mycorp.com
> User-Agent: curl/7.64.1
> accept: application/json
> Authorization: token mysupersecrettoken
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.2
< Date: Wed, 29 Jul 2020 00:53:13 GMT
< Content-Type: application/json
< Content-Length: 764
< Connection: keep-alive
< Vary: Accept, Cookie, Origin
< Allow: GET, POST, HEAD, OPTIONS
< API-Version: 2.7
< X-Frame-Options: SAMEORIGIN
```

### Database Changes

None.

**Comment by jeremystretch** [comment]
Models in NetBox for which the latest modification time is tracked already report it in their API representations as the `last_updated` attribute. What is the proposed benefit of duplicating this in an HTTP response header?

**Comment by jeremystretch** [comment]
I'm going to decline this for two reasons:

1. Django REST Framework does not appear to provide built-in support for it, meaning that any solution would require a custom implementation or the introduction of a new dependency.
2. Since determining the `last_updated` time requires retrieving the object from the database anyway, there's not much benefit to communicating this in a header. That is, making a HEAD request to check the last modified time would result in a similar amount of overhead to a normal GET request, at least without a significant amount of custom development.

**Comment by EppO** [comment]
> Models in NetBox for which the latest modification time is tracked already report it in their API representations as the `last_updated` attribute. What is the proposed benefit of duplicating this in an HTTP response header?

When netbox at scale during the VM provisioning (to get some VM facts for example), there is no current way to cache the response closer to the VM. I was thinking about putting a cache proxy in the region of the VM, talking with the central netbox instance in another region, but the lack of HTTP headers prevents any caching at the HTTP level. That's unfortunate.
