### ISSUE TITLE
Get Version of Installed NetBox Through API

### ISSUE THREAD

**Issue by CSimpiFoN** [netbox-community/netbox#4918]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8.8

### Proposed Functionality
API endpoint to get the currently installed version

### Use Case
- Be able to make deployment automation to decide if the latest version is already installed
- Be able to make to create new version check automation and alerting if new version is available

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
I should note that the _API version_ is passed as the `API-Version` HTTP header value in every response, however this does not convey the full NetBox version.

Does it make sense to create an endpoint specifically for this? If we go that route, I imagine there's probably other information we'd want to return as well; maybe a `status` endpoint or something to that effect?

Another option would be to replicate/replace the `API-Version` header with e.g. `NetBox-Version` and include it with every response. This could easily supersede the API version header (since it contains the same information), but that would be a fairly disruptive change for existing clients so we'd need to support both in parallel for some time.

**Comment by sdktr** [comment]
The header in API -calls is mostly relevant to instruct clients which version to use while rendering the output, right? Assuming there will be no breaking API changes between major releases a full version would be redundant?

Maybe a separate 'environment' endpoint is the cleanest option. Besides the netbox version it could expose detailed version info of dependencies that might end up being inspected on startup as well (https://github.com/netbox-community/netbox/issues/4933)? There's the upgrade notification (https://github.com/netbox-community/netbox/issues/738) that fits into this type of information as well?

**Comment by CSimpiFoN** [comment]
A status endpoint sounds nice that we can call for readiness/liveness too

**Comment by jeremystretch** [comment]
Marking this as tentatively accepted with the understanding that the implementation will take the form of a new "status" REST API endpoint, containing at minimum the running NetBox and Python versions. We may opt to add additional context such as installed dependencies, plugins, etc. but further consideration is needed.

**Comment by jeremystretch** [comment]
Example of the endpoint's current output:

```json
{
    "django-version": "3.1",
    "installed-apps": {
        "cacheops": "5.0.1",
        "debug_toolbar": "2.2",
        "django_filters": "2.3.0",
        "django_prometheus": "2.0.0",
        "django_rq": "2.3.2",
        "django_tables2": "2.3.1",
        "drf_yasg": "1.17.1",
        "mptt": "0.11.0",
        "rest_framework": "3.11.0",
        "taggit": "1.3.0",
        "timezone_field": "4.0"
    },
    "netbox-version": "2.10-beta1",
    "plugins": {
        "netbox_animal_sounds": "0.1"
    },
    "python-version": "3.6.9",
    "rq-workers-running": 0
}
```

Please note that we're not taking any suggestions for changes at this time. Please wait to try the v2.10 beta to provide any feedback regarding this endpoint, as it may still change.
