### ISSUE TITLE
Netbox to support Elastic Search for Caching

### ISSUE THREAD

**Issue by kgrvamsi** [netbox-community/netbox#4948]
### Proposed Functionality
To support Elastic Search as backend for caching instead using Redis.

**Comment by lampwins** [comment]
This issue has been closed as it does not conform to one of the
[provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the
[contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like
to request that your issue be re-opened, please first update the content so that it matches the appropriate
template (this may require rewriting your issue entirely).
