### ISSUE TITLE
Add chinese translation

### ISSUE THREAD

**Issue by BaiYongJun** [netbox-community/netbox#4960]
## Environment

Python version: 3.7.7
NetBox version: 2.8.8

## Proposed Functionality

Add chinese translation

## Use Case

Netbox has a lot of Chinese users, so I think Chinese translation is necessary

## Database Changes

None

## External Dependencies

None

**Comment by Dzordzu** [comment]
I don't support idea of @BaiYongJun
The official language of the current web, networking and IT overall is english. It's the most known language for people that are using tools such as Netbox. 

Additionaly there are some other issues with multilingual approach:
* translations have to be maintained
* plugins would have to support other languages
* another useless button
* it encourages people to use non english descriptions, names, symbols etc. - for me it's the biggest no no

**Comment by tyler-8** [comment]
> translations have to be maintained

Not only that, the Django-native translation framework would have to be integrated throughout the project first, which in and of itself is a massive undertaking since it's not present today in NetBox - that's not even including the actual translation aspect.

Integrating the translation framework would be a separate FR and have to be completed before any language-specific support can be viable.

**Comment by jeffrey4l** [comment]
I support this feature. There are lots of multi language support request long time ago, check #1068 #1795  #1854 . But we have no any approach for a long time.

I am agree with @tyler-8 , django i18n framework is great and easy to be set up. We can use it to make multi language suuport easier.

**Comment by lampwins** [comment]
As @tyler-8 points out, localization is a MASSIVE undertaking and requires broad-reaching, fundamental changes, and infrastructure to implement. The largest barrier for NetBox is always going to be long term ownership of the translations. Consider that anytime we implement something new, the relevant translations will have to be written which just adds to the maintenance burden.

Because there is a massive undertaking necessary before we can even attempt to take on any language-specific translations, I have to reject this request.
