### ISSUE TITLE
Add ability to filter device by rack role

### ISSUE THREAD

**Issue by tobiasge** [netbox-community/netbox#5014]
### Environment
* Python version:  3.7.3
* NetBox version:  v2.8.9

### Proposed Functionality
Add Filter for rack role one device listing page

### Use Case
Find all devices that are in racks with a specific role

### Database Changes
None

### External Dependencies
None

Edit:
I have implemented this and will create a PR if this issue is accepted.

**Comment by jeremystretch** [comment]
With limited exceptions, we generally don't support second-degree filtering of objects (e.g. filtering on an attribute of a related object). Doing so would necessitate devising a highly dynamic filtering solution to ensure consistent coverage with a minimum of code. Otherwise, we'd end up with hundreds of discrete, manually-defined filters that would be very difficult to maintain.

If you're interested in taking on this work, I'd suggest opening a new FR to propose a solution. Otherwise, we'll have to reject this because it takes us down the road of piecemealing out dozens of similar filters.

**Comment by tobiasge** [comment]
Since there is already a Rack group filter, I thought that this would be a good way to add this too.
I understand your point with this leading to too many filters.
At the moment I have not enough experience with Django filters to build a completely dynamic filtering system.

As this filter is important for us, what would you recommend to implement this?
A plugin or a custom script?

**Comment by jeremystretch** [comment]
> At the moment I have not enough experience with Django filters to build a completely dynamic filtering system.

Unfortunately, open source projects like NetBox rely on members of the community to take the initiative. I can only take on so much by myself.

> As this filter is important for us, what would you recommend to implement this?

Make two API calls: one to retrieve the relevant racks (filtered by role), and the second to filter devices by that set of rack IDs.

Going to close this issue out since it would need to be implemented under a much broader initiative as discussed above.
