### ISSUE TITLE
Error message is misleading when the report is missing in the worker

### ISSUE THREAD

**Issue by dgarros** [netbox-community/netbox#5015]
### Environment
* Python version: 3.7.7
* NetBox version:  2.9-beta2

### Steps to Reproduce
1. Create a simple report
2. Copy the report to the NetBox instance but NOT to the worker instance
3. Execute the report from the UI

### Expected Behavior
If the report is not present in the worker it would be great to have a clear error message that indicate that the reports is not there. Something like
```
Unable to run this report from XXX (name of the worker), please check if this report is present.
```

### Observed Behavior
In the UI, the error message is reporting `Error during report execution`
In the worker, the error message is `'NoneType' object has no attribute 'run'`

**Comment by jeremystretch** [comment]
> 2. Copy the report to the NetBox instance but NOT to the worker instance

This seems to be glossing over a much larger issue. The WSGI and RQ worker processes must always run with the same code base (whether that's by referencing the same filesystem or via other means of synchronization). If they don't, a _missing_ script is not even the most concerning failure, because that at least results in an immediate and largely benign failure. The much more dangerous scenario is the RQ worker unknowingly running an _outdated_ version of a script (using input data intended for the current version), risking a potentially disastrous outcome.

IMO this is a bit outside NetBox's realm of control. It might be possible to validate scripts by hashing the Python class at queue time and then evaluating it against the loaded class at execution time, but I don't know what level of effort that would entail.

**Comment by dgarros** [comment]
Based on my experience dealing with the onboarding plugin, some users are not aware of the worker and they either don't have it running or don't restart it when they are upgrading NetBox by default.

Without going as far as validating the hash of the scripts/reports, I think anything that can be done to provide more information if the system is not in the expected state would go a long way and will reduce the number of questions.

**Comment by jeremystretch** [comment]
You could argue (in a separate issue) that the documentation could use improvements in specific areas, and indeed the whole lot has been refreshed for the upcoming v2.9 release. But ultimately the burden of understanding all components of a NetBox implementation, as with any application, falls to the administrator.

**Comment by jeremystretch** [comment]
Seems like the scope of this issue is limited to conveying a more detailed error message. Should be a good candidate for volunteers.
