### ISSUE TITLE
Make serial numbers unique

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#5021]
### Environment
* Python version:  3.6.9 
* NetBox version:  2.8.9

### Proposed Functionality
Please make it possible to use unique serial numbers for Devices as asset tag. Both should be unique 

### Use Case
At the moment we can create two different devices with the same serial numbers, in contrast to asset tag. In some cases, this can contribute to the creation of duplicates in the system.

**Comment by jeremystretch** [comment]
Uniqueness is intentionally not enforced for device serial numbers as they cannot be guaranteed to be unique, even within the scope of a specific device type. You can find discussion around this in old issues. (Uniqueness of the asset tag is enforced because its namespace is controlled by the NetBox owner.)
