### ISSUE TITLE
Make readthedocs versionated

### ISSUE THREAD

**Issue by JonasKs** [netbox-community/netbox#5051]
### Change Type  
* [x] Addition  
* [ ] Correction  
* [ ] Deprecation  
* [ ] Cleanup (formatting, typos, etc.)  

### Area
* [ ] Installation instructions
* [ ] Configuration parameters
* [ ] Functionality/features
* [ ] REST API
* [ ] Administration/development
* [x] Other

### Proposed Changes
Make readthedocs versionated, so that we can read the docs for previous versions of NetBox.

Right now, I'm only able to read the `stable` documentation: 
![image](https://user-images.githubusercontent.com/5310116/91289272-6ee58b00-e792-11ea-93d9-0a3ce20dc605.png)

I wish it worked a bit like `requests`, where I'm able to check out documentation for older versions:  
![image](https://user-images.githubusercontent.com/5310116/91289578-d26fb880-e792-11ea-9a48-f23f7dad9943.png)

**Comment by jeremystretch** [comment]
We stopped publishing the documentation for old releases because Google kept sending folks to the outdated versions, leading to a lot of confusion and frustration. We publish on the current stable release (and beta release, when applicable). The documentation for older releases is still available via GitHub, or locally by installing and running `mkdocs serve`.

**Comment by JonasKs** [comment]
Ah, makes sense. I’ll build it locally. Cheers!

**Comment by jeremystretch** [comment]
FYI you can run `pip install -r docs/requirements.txt` to install `mkdocs` and its required dependencies.
