### ISSUE TITLE
Enable check box in interface template

### ISSUE THREAD

**Issue by takmiz** [netbox-community/netbox#5070]
### Environment
* Python version:  3.6.8
* NetBox version:   2.9.2

### Proposed Functionality
I need a enable check box in interface template.
Device Type is very cool function!
But I hope only indicate interface is enable when creating device.
I don't want all interface enable.

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
