### ISSUE TITLE
Allow Plugin to install additional Django App

### ISSUE THREAD

**Issue by dgarros** [netbox-community/netbox#5086]
### Environment
* Python version:  2.7.7
* NetBox version:  2.8.9, 2.9.2

### Proposed Functionality
Extend the current plugin model to allow a plugin to install/enable a third party Django Application.

The proposal is to extend the `PluginConfig` class to support a new `django_apps` attribute. 
```
class MyPluginConfig(PluginConfig):
    name = "my_plugin"
    verbose_name = "my plugin"
    version = __version__
    base_url = "my_plugin"
    .... 
    django_apps = ["app1", "app2"]
```  

### Use Case
As a plugin creator I would like to be able to leverage existing django App.
For example the SAML plugin from @jeremyschulman for netbox netbox-plugin-auth-saml2 is based on django3-auth-saml2. So it’s required to install the other django app independently
there are many existing django app that could be easily reused/extended within NetBox if we could seamlessly install them from a plugin 

### Database Changes
None

### External Dependencies
None

**Comment by cpmills1975** [comment]
I support code re-use when it is appropriate to do so, but NetBox needs to be careful that the plugin architecture doesn't start causing plugin bloat due to large numbers of dependencies being installed silently without user interaction. Just look at the Jenkins CI/CD tool for an example of this. Plugin bloat would also make identifying problems with NetBox itself more difficult than it needs to be.

**Comment by dgarros** [comment]
I've been using a similar solution with a .patch method but it's not going to work for a public plugin that is dependent on another Django App.
I think everyone agrees there is a risk associated with python dependencies management but in my opinion this risk is not bigger by introducing this feature. Any plugin can already bring a lot of dependencies and create some packaging issues.

**Comment by lampwins** [comment]
We mulled this over briefly in the initial plugin implementation and decided to punt due to the growing scope at the time. Our concern at the time included the risk of a plugin dependency interfering directly with core dependencies. Also, we had an understandable concern with the level of support issues that would arise with plugins. As some time has now passed, I personally feel that the support burden has proved to be relatively low, or at least well below our estimations. Granted, it has only been a few months :)

The technical concern, certainly still exists, but I would still be in favor of supporting this, by allowing plugins to register a list of Django apps to be appended to `INSTALLED_APPS`.

**Comment by glennmatthews** [comment]
Another example app that it would be helpful to be able to add is [django-health-check](https://django-health-check.readthedocs.io/en/latest/readme.html)
