### ISSUE TITLE
dumpdata broken looking for table extras_script

### ISSUE THREAD

**Issue by nniehoff** [netbox-community/netbox#5099]
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.2

### Steps to Reproduce
1. Install Netbox (or use docker-compose from the netbox-docker project), I followed the docs and got to the point at which I could log in to the UI to test.  It was not necessary to create any objects in the DB.
2. Run:
```
python manage.py dumpdata --format yaml --traceback
```

### Expected Behavior
Data to be output to stdout in yaml format.  NOTE:  without the `--format yaml` argument, json is output to stdout however the error still occurs.

### Observed Behavior
When trying to use the dumpdata command to get a current dump of the database I get the following error:
```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "extras_script" does not exist
LINE 1: ...OR WITH HOLD FOR SELECT "extras_script"."id" FROM "extras_sc...
                                                             ^
```

For the full traceback see https://pastebin.com/pjk7zFh2

**Comment by jeremystretch** [comment]
As a workaround, you can exclude these models when running `dumpdata`:

```
python manage.py dumpdata --format yaml --traceback -o netbox.yaml --exclude extras.Script --exclude extras.Report
```

**Comment by nniehoff** [comment]
@jeremystretch thanks, confirmed the workaround

**Comment by jeremystretch** [comment]
Short of hijacking Django's `dumpdata` management command, I don't think we can do much about this. The Report and Script models are designated as "unmanaged" because they don't actually exist in the database but still need to generate content types and permissions. AFAIK changing them to proxy or abstract won't work for this, and Django has [decided not to exclude unmanaged models](https://code.djangoproject.com/ticket/13816) when dumping data.

I'm going to close this out as it seems the workaround mentioned above should suffice.
