### ISSUE TITLE
not able to delete legacy permissions

### ISSUE THREAD

**Issue by marendres** [netbox-community/netbox#5113]
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.3

### Steps to Reproduce
1. Select group with permissions from earlier netbox version
2. select "delete?" for a object_permission
3. click "save"

### Expected Behavior
Saves the Group and removes the selected permission

### Observed Behavior
As expected the group is closed and there is the banner: "The Group “myGroup" was changed successfully."
But the permission still shows up in the group overview, though in change permission menu of the same permission the group is not mentioned anymore.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.9.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by marendres** [comment]
The initial objects and permissions have been created in early versions of netbox.
But the permissions are not showing up in the group overview anymore, there seemed to be some kind of delay.

I am able to reproduce this with adding permissions as well:
1. create permission
2. add permission to group
=> permission is not visible in the group configuration but the group is associated with the permission. After a few hours it appears.

As the permissions can be removed after all, the impact of this is not too big.

**Comment by thoms27** [comment]
same issue

**Comment by ledgley** [comment]
same issue

**Comment by jeremystretch** [comment]
I'm not able to replicate anything resembling the reported behavior.

Does it still happen if you disable caching? (Set `CACHE_TIMEOUT = 0` in `configuration.py` and restart NetBox to disable caching.)

**Comment by ledgley** [comment]
I tested the following:

Set `CACHE_TIMEOUT = 120` & restart NetBox
1.  Grant User Permission
*  Present via Admin panel immediately
*  Present via API immediately

Wait 2 minutes

1.  Revoke User Permission
*  Permission still present in Admin Panel
*  Absent via API immediately
*  After two minutes permission is absent in Admin panel

Set `CACHE_TIMEOUT = 0` & restart NetBox

1.  Grant User Permission
*  Present via Admin panel immediately
*  Present via API immediately

1.  Revoke User Permission
*  Absent via Admin panel immediately
*  Absent via API immediately

**Comment by jeremystretch** [comment]
Looks like yet another caching bug.

**Comment by lampwins** [comment]
First, I can confirm this bug with these steps:

0. For simplicity, start with no groups or permissions, and ensure caching is enabled
1. Navigate to Groups in the admin panel
2. Add a new group and save
3. Navigate to the new group in the admin panel
4. Click the plus button to create a new object permission
5. In the pop-up, create new object permission and save
6. Click save on the group
7. Navigate to back to the group and notice the new object permission is not listed, even though it is linked and can be confirmed by viewing the groups listed on the object permission's details.

I am able to resolve this by adding `.nocache()` to `ObjectPermissionInline.get_queryset()` but I am not entirely sure what the root cause is here yet. I think it has something to do with the explicit use of the through models in the inline forms for `AdminUser` and `AdminGroup`.

I know cacheops explicitly disables caching for `ModelAdmin` forms and I have asked for some clarification here: https://github.com/Suor/django-cacheops/issues/287
