### ISSUE TITLE
RelatedObjectDoesNotExist in NetBox version: 2.9.3

### ISSUE THREAD

**Issue by Shash-gowda** [netbox-community/netbox#5122]
**ERROR** 
<class 'django.contrib.auth.models.User.config.RelatedObjectDoesNotExist'>

The user has no config.

Python version: 3.6.8
NetBox version: 2.9.3

**INSTALLED ntc_onboarding plugin** 
     Can't add the device via the plugin

**Observed Behavior**
A RelatedObjectDoesNotExist exception is raised during model validation, causing a server error.

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
