### ISSUE TITLE
Allow strict filtering of cables by tenant

### ISSUE THREAD

**Issue by m384wwn** [netbox-community/netbox#5140]
### Environment
* Python version: 3.8.2
* NetBox version:  2.9.3

### Proposed Functionality
On the cables page, when you filter by tenant(s) you will get a list of cables which connect on both sides to the selected tenant(s) as well as one side only. I am proposing, perhaps a checkbox next to the Tenant filter that says "strict".  When enabled it will only show cables which connect on both sides to the selected tenant(s).

### Use Case
We often have facilities which some of the inter-room/site, cabling is managed by another company (tenant). We always provide patch cables to their patch panels but never the other way around. We also keep track of their cabling for troubleshooting and so that things 'connect' in netbox.

We can currently generate a list of our cables (as we patch to their panels) but we can't generate a list of their cables.

### Database Changes
none

### External Dependencies
none

**Comment by lampwins** [comment]
I feel this is somewhat related in spirit to #4944. I get your use case but it seems very specific and requires us to implement a type of filtering logic we have never done before.

Perhaps we could allow separate filters for both the A and B sides of the termination.

**Comment by m384wwn** [comment]
> separate filters for both the A and B sides of the termination
Sounds like that would also achieve the same result, even gives a bit more specificity.

**Comment by jeremystretch** [comment]
The major impediment to implementing this (even for a specific side; A or B) is that the termination fields are GenericForeignKeys which can point to (currently) nine different models. Tenancy is determined by referencing `device__tenant` for device components, whereas `circuit__tenant` is used for circuit terminations. Additionally, PowerFeed has no concept of tenancy.

I'm marking this as `needs owner` in case someone wants to dig into it and see if they can come up with something clever. Otherwise, it's probably not going to be implemented.
