### ISSUE TITLE
Buttons Collapse and Expand are missing in 2.9.3 netbox while they were present in 2.8 version of netbox

### ISSUE THREAD

**Issue by marbarmar** [netbox-community/netbox#5157]
### Environment
* Python version:  2.7.5
* NetBox version:  2.9.3

### External Dependencies

none

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
