### ISSUE TITLE
Create an explicit configuration parameter to control background task execution timeout

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5171]
### Environment
* Python version: 3.6.9
* NetBox version:  2.9.3

### Proposed Functionality
Introduce a new configuration parameter named `RQ_DEFAULT_TIMEOUT` to specify the maximum execution time of a background task (e.g. running a script or report).

### Use Case
The default timeout for an RQ queue is currently controlled by the `DEFAULT_TIMEOUT` parameter set under the `REDIS` configuration. This is misleading, as the parameter appears to control the timeout for connecting to a Redis database, as opposed to the the duration of a task's execution. (Indeed, the current documentation [erroneously indicates](https://netbox.readthedocs.io/en/stable/configuration/required-settings/#redis) that this parameter represents the "connection timeout in seconds.")

### Database Changes
None

### External Dependencies
None

**Comment by billybob83400** [comment]
Hello,
I got this error when I perform 'docker up':
/opt/netbox/netbox/netbox/settings.py:230: UserWarning: DEFAULT_TIMEOUT is no longer supported under REDIS configuration. Set RQ_DEFAULT_TIMEOUT instead.
  warnings.warn('DEFAULT_TIMEOUT is no longer supported under REDIS configuration. Set RQ_DEFAULT_TIMEOUT instead.')

I can I set this RQ_DEFAULT_TIMEOUT instead of the REDIS ?

Thanks

**Comment by jeremystretch** [comment]
@billybob83400 please post to our [mailing list](https://groups.google.com/g/netbox-discuss) for support issues.
