### ISSUE TITLE
Remember user preference to show/hide device type images in rack views

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#5203]
### Environment
* Python version:  3.6.8
* NetBox version:  2.9.3

### Proposed Functionality
It would be nice if the value of the "Show images" setting on a rack view could be persisted as a user preference (using the mechanism introduced in #3294).

### Use Case
We are making use of device type front/rear images on most of our devices in Netbox. By default, Netbox will render these images in a rack view, except when the user toggles the "Show images" button.
However, this is only valid for the current view -- as soon as another rack view is opened, or the current page is refreshed, Netbox falls back to the default mode, i.e. showing images.

Some users may not see any use in the images, and prefer to always see the name and device type color instead. Having a dedicated user preference key for this setting would allow for this functionality.

### Database Changes

none
### External Dependencies
none

**Comment by jeremystretch** [comment]
Reminder for whoever takes this on: Be sure to record the chosen preference name in `docs/development/user-preferences.md`.

**Comment by ogorov** [comment]
I could try to solve this issue.

**Comment by jeremystretch** [comment]
@ogorov but _will_ you? If you're willing to commit to the work, I'll assign this to you. Otherwise, I'm going to re-apply the "pending closure" label.

**Comment by ogorov** [comment]
@jeremystretch yes, i'll try. I'll do it if my skills are enough.

**Comment by proudbro** [comment]
When it will be implemented? Really looking forward for it

**Comment by k0ste** [comment]
+1 for this

**Comment by thatmattlove** [comment]
@hoalex, @proudbro, @jeremystretch:

This is now implemented in the `feature` branch, at least as originally phrased. However, I haven't closed this yet as I wanted to get some further input. In `feature`, the new behavior is that the state of the "Show Images"/"Hide Images" button is persisted _locally_. This means once you toggle the button so that the images are hidden (which would display "Show Images" in the button), this is remembered in the browser for all rack views until the browser's localStorage is cleared.

However, we _could_ take this a step further and make this configurable via the user profile in addition to the current behavior. This would guarantee that the setting is _always_ persisted for the user, regardless of browser. I don't think it would be a ton of work to implement this, but I didn't want to go forward with it if all the interested parties were happy with the new behavior as-is.

**Comment by jeremystretch** [comment]
I think it's fine to keep this in local storage for now. We need to spend some time thinking about how best to scale the [user preferences framework](https://netbox.readthedocs.io/en/stable/development/user-preferences/) before we add any more to it.

**Comment by thatmattlove** [comment]
Agreed. I do have some thoughts there, and I think it will become more relevant as we move to an SPA model. For the time being, I think we can consider this issue closed as part of 3.0.
