### ISSUE TITLE
Sync rear ports configure on a device type to all device with the same type ?

### ISSUE THREAD

**Issue by JulesRe** [netbox-community/netbox#5259]
### Environment
* Python version: N/A
* NetBox version: 2.9.4

  Can we sync all the rear ports configure on a device type to all device with the same type ? Because that hard to make by hand all rear port on each device.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
