### ISSUE TITLE
Group connect Rear Ports 2 optical Patch panel. 

### ISSUE THREAD

**Issue by amirigo12** [netbox-community/netbox#5279]
### Environment
* Python version: 
* NetBox version:

**Comment by amirigo12** [comment]
I have 2 or more optical Patch Panel. For Example 2 Optical Patch Panel - 24 rear and front ports.
 
How to group the 24 rear ports
Patch 1 and panel patch 2?
You can connect one port, but it takes a lot of time.

If we imagine that there are 10 patch panels with 48 ports.
This is to manually connect 480 rear ports between patch panels. It will take a very long time.
Therefore, the question arose of how to connect the rear ports in a group

If the cable is Solder between the patch panels the rear ports are port to port.

**Comment by amirigo12** [comment]
https://github.com/netbox-community/netbox/issues/2854 
How activate button new Button (Bulk-Actions) ? For group connet ports patch panel ?

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by amirigo12** [comment]
Thanks for the information, we hope that this functionality will appear in the next versions netbox . Group connection of ports 1: 1 of different patch panels.
