### ISSUE TITLE
return rack group with device

### ISSUE THREAD

**Issue by nvitaly** [netbox-community/netbox#5281]
### Environment
* Python version: 3.7
* NetBox version: v2.9.7

### Proposed Functionality

We have rack group (cages) and we have racks, when i retrieve list of devices from API or in UI I can only see Rack, yes I can click inside and find  out Rack group but this is extra request. I might gave same name of rack or even just similarly looking names in different rack groups. which makes list hard to work with.

I am currently considering just renaming Rack so it include Cage (rack group) but it seems redundant, 

I propose: return adjacent to the rack rack group with the device same way we have rack, site in it. 

May be I am missing something, let me know.

**Comment by jeremystretch** [comment]
The REST API is necessarily limited to returning only directly related objects in most cases. Otherwise, every request would take an inordinate amount of time to process and return far more information than is needed. The API is structured so that a consumer can make efficient requests to retrieve only the specific information needed. For example, you might make one request to retrieve a set of devices and their associated racks, and then make a second request to retrieve the rack groups for each of the racks. This is a very common pattern in REST APIs, and not specific to NetBox. Alternatively, consider using a client such as [pynetbox](https://github.com/digitalocean/pynetbox) to abstract these operations.
