### ISSUE TITLE
<class 'django.contrib.auth.models.User.config.RelatedObjectDoesNotExist'>

### ISSUE THREAD

**Issue by dineshkumarpalanivelu** [netbox-community/netbox#5322]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.8

<class 'django.contrib.auth.models.User.config.RelatedObjectDoesNotExist'>

User has no config.

Python version: 3.6.8
NetBox version: 2.9.8

I am getting this error after logging into netbox and clicking IP Address

I want to see the IP Address allocation page after clicking IP Address 

but this above mentioned error is coming

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
