### ISSUE TITLE
Unable to add Rack reservation

### ISSUE THREAD

**Issue by DavidLiedke** [netbox-community/netbox#5333]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.7

### Steps to Reproduce
1. Go to --> Organization --> Racks --> Reserverations
2. Add new Reservation
3. Choose Rack

"The results could not be loaded"
![TeamViewer_UPH9xhFuLd](https://user-images.githubusercontent.com/25581728/98647261-e90ac200-2334-11eb-82a6-81a10342dfa6.png)

**Comment by dteknet** [comment]
I do confirm the same but in a slight different way. The list of racks is displayed, but if to choose some and then open the list again, the message appears.
Python 3.6.9, NetBox 2.9.9

![image](https://user-images.githubusercontent.com/65331309/98674276-40bf2280-2361-11eb-97d0-d9aed348927f.png)
![image](https://user-images.githubusercontent.com/65331309/98674304-4b79b780-2361-11eb-8fb0-91dfd9de1d5e.png)

**Comment by jeremystretch** [comment]
I'm not able to reproduce this issue on v2.9.9. However, I have opened #5350 for a related bug, which is preventing proper filtering of the available racks based on the selected rack group (and causing the error @dteknet illustrates above). However, the fix for this is likely not related to the original bug report here.

@DavidLiedke I suggest first upgrading to v2.9.9 to see if the problem persists. If so, try inspecting the REST API call being made with your browser's developer tools (typically opened by pressing F12).

**Comment by DavidLiedke** [comment]
All works fine with Version 2.9.9.

Thank you.
