### ISSUE TITLE
Incident management tool and report Extract ?

### ISSUE THREAD

**Issue by SATadsl** [netbox-community/netbox#5388]
### Environment
* Python version: 
* NetBox version: 

### External Dependencies

Hello, 

I really need your help can I have an integrated incident tool with NetBox ?? 

I mean like integrate an incident management tool that I can add with NetBox and if there is not can you please help me with a name for a good incident Management tool ? and also can I extract report from NetBox ?? please I need your help .

Best Regards

**Comment by xkilian** [comment]
Look at the documentation about reporting in Netbox. 

- [Documentation for reporting](https://netbox.readthedocs.io/en/stable/additional-features/reports/)
- [Reporting collection, may have what you need](https://github.com/netbox-community/reports)
- Look for the Netbox Day 2020 youtube videos to learn more about Netbox
- https://github.com/hovodab/alrescha may be some integration you are looking for with regards to Netbox and Confluence. This is on my list of things to try.

Incident Management/Ticketing/workflow tools are not in scope by any means for netbox IMO. You may develop a plugin that serves as a connector between Netbox and ServiceNow, RequestTracker, JIRA or other ticketing system. There may be existing  plugins, I do not know. If you are looking for a good general purpose ticketing system, start with Request Tracker, linking the two systems(Netbox and RT) should not be rocket science.

In any case, you should have tried the mailing list with this type of general question instead of creating an issue.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
