### ISSUE TITLE
Consistent available prefix presentation in sub-prefixes

### ISSUE THREAD

**Issue by martinkiska** [netbox-community/netbox#5397]
### Environment
Python version: 2.7.5
NetBox version: 2.9.3

### Steps to Reproduce
1. create 10.64.0.0/16 prefix, afterwards create another sub-prefix 10.64.0.0/24 and allocate few prefixes in 10.64.0.0/24 space. When doing so you will not be able to see those available prefixes in 10.64.0.0/16 master prefix. Please check attached picture or comments in https://github.com/netbox-community/netbox/issues/5158#issuecomment-735601563

![image](https://user-images.githubusercontent.com/75117548/100732737-7047d480-33cd-11eb-9008-1d388bb6c8fb.png)

### Expected Behavior
I expect consistent behavior -> if netbox is showing available prefixes for parent prefix, it should also show available prefixes for sub-parent prefixes. Current output is confusing causing people to think, that sub-prefix is fully allocated without available prefixes.

### Observed Behavior
I see available prefixes only in parent prefix - while going through the GUI we have inconsistent information regarding available prefixes allocation.

**Comment by jeremystretch** [comment]
> When doing so you will not be able to see those available prefixes in 10.64.0.0/16 master prefix.

IMO this is preferable behavior. Within the context of the prefix being viewed (10.64.0.0/16), all of 10.64.0.0/24 has been allocated. To see available space within that prefix, view the prefix's children.

We wouldn't want to display space available within child prefixes, because it would very often be distracting. Consider a scenario where each site gets a /24 out of a /16. When looking for available space for a new site, you don't want to see space available within each /24, because it's not relevant and would only take up space on the page.
