### ISSUE TITLE
Extend model VirtualMachine to store minimum memory

### ISSUE THREAD

**Issue by xcdr** [netbox-community/netbox#5398]
### Environment
* Python version: 3.8.6
* NetBox version: 2.9.10

### Proposed Functionality
Extend VM model for minimum memory.

### Use Case
We use PROXMOX VE for hosting our VMs and we have possibility to specify base and minimal amount of memory for VM (ballooning feature).

It would be cool to store minimum memory for VM in NETBOX because We doing automatic inventory via REST API.

See chapter "10.2.6. Memory" in: https://10.222.11.44:8006/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings
### Database Changes
```
memory_min = models.PositiveIntegerField(
    blank=True,
    null=True,
    verbose_name='Minimum memory (MB)'
)
```

**Comment by jeremystretch** [comment]
NetBox specifically avoids stepping too far into the realm of VM orchestration. It provides some basic fields for CPU, memory, and disk resources suitable for conveying external cloud resources but not much more, because it is assumed that anyone running an extensive VM cloud of their own already has an orchestration system in place.

However, you can always add this as a custom field for your local NetBox deployment.

**Comment by xcdr** [comment]
OK, but We use this rather for reporting/overview and not for orchestration.
