### ISSUE TITLE
Ports must be created with a Type -- which is a problem if we don't know what type it is.

### ISSUE THREAD

**Issue by Infiniverse** [netbox-community/netbox#5412]
### Environment
* NetBox version: v2.9.9

### Steps to Reproduce
1. Create a port/interface
2. Try and leave the type blank

### Expected Behavior

I expected to be able to create an untyped port, but I couldn't.

When I don't know what kind of port we have (is it APC or UPC? Is it LC or SC?) I cannot create a device-type.
Sometimes we want to document even if we don't know what the specifics are yet. It would be useful to introduce an 'Unknown' type to facilitate this.

**Comment by jeremystretch** [comment]
This is expected behavior: The `type` field is a required field for the model.

> When I don't know what kind of port we have (is it APC or UPC? Is it LC or SC?) I cannot create a device-type.

This is by design. A device type is intended to be a complete representation of a physical device. In cases where interfaces are modular and may vary among instances (for example, modular patch panels), they should not be added to the device type. Instead, they should be populated as needed on individual devices. (Components can be added to many devices in bulk through the NetBox UI.)

**Comment by Infiniverse** [comment]
I understand this from a purety perspective. But doesn't it mean that we cannot document our network formally until you've added any missing types? For example, we are on v2.9.9 which doesn't have a 'splice' type yet (which is coming in v2.10) - how would you recommend we document our splice ports? - there is no way of creating a port without a specific type, and all of the types are wrong which means that our documentation isn't correct.
