### ISSUE TITLE
Paginator on top of tables

### ISSUE THREAD

**Issue by kbsx32** [netbox-community/netbox#5429]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.9

### Proposed Functionality
Move or add paginator at top of any tables (e.g. prefixes, ip address, prefix ip addresses)

### Use Case

At least there is no search/filter in prefix ip addresses view so the only way to find IP address is to scroll down many pages to find next-page button.

Futhermore, I think it is better to navigate between table pages via page navigator that on the top of page. When it is in bottom of page you have to scroll down all pages to find next-button page until reach object you want

### Database Changes
N/A

### External Dependencies
N/A

**Comment by DanSheps** [comment]
We can look at inclusion for this after the final release of 2.10.

Would you be willing to take this on (I think adding the pagination at the top as well would be good)

**Comment by jeremystretch** [comment]
I've tagged this as `needs owner`, but want to caution that any proposed changes must carefully adjust the UI layout. (Please don't just copy & paste the paginator at the top of the template, leaving a large amount of wasted space.)

**Comment by cpmills1975** [comment]
Happy to have a go at this if it is re-opened and assigned to me?

**Comment by DanSheps** [comment]
@cpmills1975 Assigned you, feel free to give it a good while heeding the advice the advice given regarding wasted space

**Comment by cpmills1975** [comment]
So, I've done some work on this and I have what feels like a reasonable solution for the pagination at the top of the table. However, the bottom one troubles me - especially when it appears directly under the table when the side bar is long (device list for example) vs when it appears under the side bar when the sidebar has less search options and appears shorter than the list (interfaces for example).

I've tried to juggle things around a bit such that the pagination is always in line with the right hand side of the table, but it is proving quite difficult to get it to appear in a consistent way.

Digging through the templates and the inspector in Safari, I can see that the page is fundamentally using the Bootstrap grid system. The sidebar is 3 columns wide, but with a minimum and maximum width specified, while the underlying table is nominally 100% wide, but shrunk by the side bar. If I make the table 9 columns wide, not only does it still take up the whole page, the page as a whole renders in a more responsive manner on smaller devices (IMO the page doesn't render particularly well on smaller screens as it stands, but I won't go in to that here).

Was structuring the page in this way (with only the sidebar width set and then constrained) a deliberate choice? If it was, can I ask why? Would there be any objections to setting the table to 9 columns wide rather than letting the browser automatically shrink it?

Are any changes to the UI pointless now given the plans to re-think the templates in #5893?

**Comment by jeremystretch** [comment]
This has become much easier to implement since the paginator HTML was tweaked for HTMX-enabled tables under #8057. However, I'm going to tag it for v3.2 so that we can expose the paginator location (top, bottom, or both) as a well-defined user preference (#7759).
