### ISSUE TITLE
SVG image upload fail for rear/front image in device types

### ISSUE THREAD

**Issue by netixx** [netbox-community/netbox#5433]
### Environment
* Python version: 3.8.6
* NetBox version: 2.9.9

### Steps to Reproduce
1. Edit a device type
2. Select an SVG file as a rear or front
3. Save the form

### Expected Behavior
Image is uploaded and save with the device type

### Observed Behavior
Error returned on the image field :
`Upload a valid image. The file you uploaded was either not an image or a corrupted image.`

We are using the file storage backend. We also tried SVGZ format which didn't work as well.
PNG upload works fine.

**Comment by jeremystretch** [comment]
This is due to lack of support for SVG in the PIL library, which is used by Django's ImageField for validation (see [Django bug #14092](https://code.djangoproject.com/ticket/14092)).

Changing the `front_image` and `rear_image` fields on the DeviceType model to FileFields would allow for SVG upload, however custom validation would be needed to ensure uploaded files are valid images.

**Comment by netixx** [comment]
Thank you for the update. In the meantime, could we restrict the image types in the image picker/system browser to supported types only ?

In my case, I was mislead because I saw "*.svg, *.svgz" in the filtered file types.

**Comment by jeremystretch** [comment]
> In the meantime, could we restrict the image types in the image picker/system browser to supported types only ?

Yes, I think that makes sense. I'm going to limit the accepted file types to exclude SVG. Still happy to entertain moving away from ImageField to ultimately enable support for SVG, but as mentioned that will be more involved so it would need a separate FR.
