### ISSUE TITLE
Change log entry displays "No changes" when editing description field on device components and previous value was null.

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#5517]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2

### Steps to Reproduce
1. Create a device from a device type with interfaces.
2. Edit an interface on the device and set the description field to some value.
3. View the change log entry for the edit.

Note, the same observed behaviour also happens when editing the description field on:
* Front Ports
* Rear Ports
* Console Ports
* Console Server Ports
* Power Ports
* Power Outlets
* Device Bays

### Expected Behavior
In the **Difference** section it should display that _description_ was changed from null to the value that was submitted in the edit.

Example of corresponding behaviour from editing the _mac_address_ field:
![image](https://user-images.githubusercontent.com/1220054/102894737-d8855580-4463-11eb-90b7-bae2ede23bb5.png)

### Observed Behavior
![image](https://user-images.githubusercontent.com/1220054/102894810-f488f700-4463-11eb-90f6-a383fffa0661.png)

**Comment by jeremystretch** [comment]
There's no delta displayed because interfaces (and other components) populated when creating a new device don't generate a change record. (Whether or not this is desired is subject to debate, but IIRC we decided not too to, both to cut down on log spam and because a user didn't technically create the component directly.)

When viewing a change record, the diff displayed is generated by comparing the current record against its predecessor. When no preceding record exists, there is no diff to show. This is true for _any_ attribute on _any_ model, not just device components. (You're seeing a diff for `mac_address` because NetBox is comparing the object's second change record to its first.)

**Comment by dare-to-recurse** [comment]
That makes sense, and I agree with the reasoning behind reducing log spam and the technicality of the user not creating the component directly.

This is honestly something that would be considered a nice-to-have for the situation I noticed it in, not a requirement in any way, so compared to the downside of additional log spam it's not really worth it.

**Comment by lampwins** [comment]
@dare-to-recurse are you willing to take this issue on? Without a community owner, this is not likely to get traction from the core team due to the lack of substantial interest from others.

**Comment by dare-to-recurse** [comment]
I'd class myself as a beginner when it comes to programming (especially in python), but I could give it a go.
I have to note that work is extremely busy for me over the coming 1-2 months though, so I might not have the time to look at it properly until after then.

Would that still be okay?

**Comment by jeremystretch** [comment]
Incidentally, this has been addressed by the change in #5913 and will be fixed in the upcoming v2.11 release.
