### ISSUE TITLE
Keep Track of Virtual Hosts on a shared Linux server

### ISSUE THREAD

**Issue by astukestarr** [netbox-community/netbox#5537]
Mayber there is a way to do this in the current config and I just dont see it.
### Environment
* Python version: python3
* NetBox version:  2.10.2

### Proposed Functionality
I'd like to track virtual servers inside a VM, so I might have a Physical server, then a web server, but inside the web server there are multiple virtual hosts for different websites, like abc.com and def.com. It seems like we would have to add another level to drill down to.

### Use Case
I'm trying to track where an email account may be hosted, or a website. So you might have a Host, then VM, then Domains inside that vm. You might have an different Virtual host if their email is in a different place than the website.

### Database Changes
I don't know, I'm not a programmer

**Comment by candlerb** [comment]
(Aside: this probably ought to be changed to "Discussion" rather than "Issue")

The way I recommend modelling this is with "Services".  Go to a device or VM, and:

- add service abc.com, TCP port 443
- add service def.com, TCP port 443

The UI allows multiple instances of the same protocol+port, although it doesn't allow this to be left empty.

Unfortunately you can't search for "abc.com" in a global search; but if you go to `IPAM > Services` you can search there.
