### ISSUE TITLE
extras/plugins: fix typo in dict key

### ISSUE THREAD

**Issue by pvinci** [netbox-community/netbox#5618]
### Environment
* Python version: 3.8
* NetBox version: Develop

### Steps to Reproduce
1. 
2. 
3. 

### Expected Behavior
dict key of "version"

### Observed Behavior
dict key of "verison"

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by pvinci** [comment]
@DanSheps 
How would you suggest conforming this?  A typo in a dict key is not strongly typed.
Would adding something like this be sufficient?
$ grep -r verison .
./netbox/extras/plugins/views.py:            'verison': plugin_app_config.version

**Comment by DanSheps** [comment]
You didn't explain what the problem is, please go ahead and explain the problem before we consider opening this and follow the contributing guidelines.

We have no idea what you are asking for here.  What is the exact problem?  How do you cause this problem?  What is the result?  What should happen.
