### ISSUE TITLE
Set VRF for available IPs to same VRF as parent prefix

### ISSUE THREAD

**Issue by gstorme** [netbox-community/netbox#5703]
### Environment
* Python version: 3.7.3
* NetBox version: 2.10.1

### Steps to Reproduce
1. Create prefix in VRF Global
2. Change VRF of the prefix to a specific VRF
3. Go to /ipam/prefixes/{prefix-id}/ip-addresses/

### Expected Behavior
The available IP's are preset to the VRF of the parent prefix.
When clicking the "x available IPs" button, it will create an IP with the VRF of the parent prefix.

When using the button "+ add an ip address", the VRF is set correctly since it's redirecting to `/ipam/ip-addresses/add/?address=172.16.20.6/24&vrf=4&tenant_group=&tenant=`

### Observed Behavior
The available IP's are still linked to VRF Global.
When clicking the "x available IPs" button, it will create an IP with VRF Global.

![image](https://user-images.githubusercontent.com/3859276/105998755-43eac480-60ad-11eb-9b13-fadc94a38583.png)

**Comment by ljb2of3** [comment]
@DanSheps I'd call this a bug, not a feature. As I get more non-networking folks using netbox to self-assign IPs this is going to cause significant confusion.

**Comment by DanSheps** [comment]
I understand where you are coming from, but this isn't exactly a bug.

**Comment by nkeulen** [comment]
This problem annoyed me too, I've fixed it in my local version. 
I can put in a pull request for this one if someone can assign the issue to me. 

I actually do think it is a bug by the way. 
Some jinja template lines from netbox/ipam/tables.py are not getting included because some stuff got renamed I think. 

Anyhow if someone can assign this issue to me, I'll add a pull request for it.
