### ISSUE TITLE
Site GPS coordinates accept only 6 digits behind dot

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#5707]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.4

### Steps to Reproduce
1. Create new site
2. Edit site an try to use 7 digit GPS coordinates for latitude an longitude (google maps default is 7 digits behind dot)
3. Can not enter GPS coordinate with 7 digits behind dot.

### Expected Behavior
Use 7 digit long GPS coordinates.
for example 40.6895683,-74.0449588

### Observed Behavior
Only 6 digit long coordinates are possible. 
For some of our locations, GPS coordinates with 6 digits are too inaccurate. They then point e.g. to a neighboring building via the "map it" link.

**Comment by jeremystretch** [comment]
> Only 6 digit long coordinates are possible.

This is expected behavior. The GPS coordinate fields support up to six decimal places.

> For some of our locations, GPS coordinates with 6 digits are too inaccurate. They then point e.g. to a neighboring building via the "map it" link.

This provides a precision [up to 0.11 meters](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude/8674#8674); far more than sufficient for identifying the location of a building. If the map doesn't show what you expect, it's likely that your coordinates are wrong.
