### ISSUE TITLE
full trace (interface to interface) not available if using circuits between sites

### ISSUE THREAD

**Issue by Gheorghita** [netbox-community/netbox#5717]
### Environment
* Python version:  3.6.8
* NetBox version: v2.10.4

### Steps to Reproduce
1. Create 3 sites in different regions with devices
2. create 2 circuits
3. connect one device from site A to Site C via Site B
![multipleSites](https://user-images.githubusercontent.com/9327352/106280768-03bf4980-6247-11eb-9ef6-ea6d9f704599.png)

### Expected Behavior
Trace from interface 1 (site A) to interface 2 (site C)
![1-n-splice-noCircuite-Cable Trace for Interface gi25 - NetBox](https://user-images.githubusercontent.com/9327352/106279654-6adbfe80-6245-11eb-8524-ac163e3e4216.png)

### Observed Behavior
trace breaks at the first circuit.
![1-n-splice-Circuite-Cable Trace for Interface gi25 - NetBox](https://user-images.githubusercontent.com/9327352/106280093-1e44f300-6246-11eb-8f61-cf3f0f8078de.png)

Works as expected if I don't use circuits and directly connect ports from different sites. (trace from the first picture is the result)

**Comment by jeremystretch** [comment]
This is expected behavior and is specifically called out in the [v2.10 release notes](https://netbox.readthedocs.io/en/stable/release-notes/version-2.10/#new-features): Circuits are considered endpoints of the cable path. This change was made to fix several bugs which had plagued the cable tracing logic for a long time.

**Comment by jeremystretch** [comment]
FYI I've opened #6071 to address this as a feature request.
