### ISSUE TITLE
Virtual chassis member redirect

### ISSUE THREAD

**Issue by danwalkeruk** [netbox-community/netbox#5746]
If you click on 'Add Member' from a Virtual Chassis page, once you've added the member it forwards you to the Device page (of the member) instead of the VC page.

Not sure if this is expected behaviour, but it seems to break flow a bit.

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
