### ISSUE TITLE
Child devices should not appear in the list of Non-Racked Devices (reopening)

### ISSUE THREAD

**Issue by wols** [netbox-community/netbox#5756]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Proposed Functionality
1. create a parent
2. place the parent in a rack
3. create childs
4. "rack" the childs as an unracked devices
5. place the childs in parent bays

**childs are `racked` (in bays of `racked` parent)**

reopens #4595

### Use Case
clear picture of reality:

- childs are module
- bays are slots
- parents are shelfs
- shelfs are in racks

**modules are also in the rack** 

### Database Changes
other joins?

### External Dependencies
no

**Comment by cpmills1975** [comment]
Are you saying child devices *should not* appear in the list of unracked devices because they are 'racked' inside a parent?

If you are, I'd agree with you. The unracked devices list should be there to list devices which are 0U devices and devices that do not have a U position recorded.

In a rack full of blade chassis, having many many blades shown in the unracked devices table is IMHO incorrect.

**Comment by yaigor5** [comment]
> child devices should not appear in the list of unracked devices because they are 'racked' inside a parent
IMHO child devices can be listed as "Non-Racked Devices" only if deattached from parent

**Comment by alanNutanix** [comment]
yet another agreement that child devices should not be shown in the non-racked device.  (if and only if their parent device is racked.)
