### ISSUE TITLE
VPN Tunnels

### ISSUE THREAD

**Issue by rhys-g-jones** [netbox-community/netbox#5845]
I know this has been requested in the past and its be turned down rather quickly i believe

In light of the shift to SD-WAN technologies and Tunnels being used to services like Azure and AWS, it would be great to be able to track these connections in Netbox,  Circuits i agree are not the correct place for this type of connection but i would like to know peoples thoughts to now considering a dedicated section for Site to Site VPNs or Tunnels

While these don't have guaranteed speeds and fixed mediums they are becoming much more prevalent in todays networking

this is the only major aspect i see missing in netbox

Thanks

Rhys

**Comment by xkilian** [comment]
Maybe this could be a starting point or continuation for your needs: https://github.com/vapor-ware/netbox-virtual-circuit-plugin/issues/55

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
