### ISSUE TITLE
Can't create prefix via available-prefixes API endpoint with all needed constraint permissions

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/netbox#5869]
### Environment
* Python version:  3.6.9
* NetBox version:  2.10.3

### Steps to Reproduce
1.  As admin create active prefix
2.  Create permission to view all prefixes
3.  Create permission to add reserved prefix
4.  As test user with permissions above POST on /api/ipam/prefixes/{created_active_prefix_id}/available-prefixes/ with body {"status" : "reserved", "prefix_length" : 24}
5.  API will return 404 NOT FOUND error
6.  GET on /api/ipam/prefixes/{created_active_prefix_id}/available-prefixes/ works fine

### Expected Behavior
Create reserved child prefix.

### Observed Behavior
NOT FOUND error

This is related to #5841, but deserves separate bugreport. 
Creation via web interface works fine.

**Comment by DanSheps** [comment]
So just so we are clear.  The test user has the following permissions:

* View all prefixes
* Create prefixes with status "reserved" (only)

**Comment by Dimaqa** [comment]
Yes, that's right.
![image](https://user-images.githubusercontent.com/33034690/109172820-3bf96f80-7794-11eb-9f0b-a9b4a2d68d4a.png)

**Comment by jeremystretch** [comment]
The 404 is returned due to a permissions failure. DRF is checking the necessary permissions (POST, status=reserved) against the parent prefix object rather than the one being created. I'm not sure how to properly adjust the permissions evaluation.

As a workaround, you can request the next available prefix using GET, and then create it directly using a POST to the `/api/ipam/prefixes/` endpoint.

**Comment by Dimaqa** [comment]
Can't you override `def has_permission(self, request, view):` in `PrefixViewSet` with same idea as in `def get_serializer_class(self):`? Because it's not that simple to ensure parrallel lock in your workaround
