### ISSUE TITLE
Use numeric identifiers in all URLs

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5873]
### Proposed Changes
Replace the usage of slugs in URLs with numeric IDs. For example, for a site with the ID 123 and slug 'site-a', the URL would change from

`/dcim/sites/site-a/`

to

`/dcim/sites/123/`

All child views (edit, import, etc.) would change as well.

### Justification
1. Provides a more consistent URL pattern, where all objects are identified the same way.
2. Allows us to phase out the use of slug fields.

**Comment by ryanmerolle** [comment]
Having slugs is nice in the url, but plenty of other tools because of consistency and other challenges of trying to keep slugs in the url path.  LibreNMS comes to mind here.  Most of the benefits of slugs in a url with regards to external integrations can be solved with other means.

If it greatly helps out on the backend & development I think its fair to do.

**Comment by jpobeda** [comment]
I agree. I like the slugs as well but consistency is always favored.

**Comment by jeremystretch** [comment]
Well, that was easy. :slightly_smiling_face:
