### ISSUE TITLE
ASN Repository 

### ISSUE THREAD

**Issue by amaizenshtein** [netbox-community/netbox#5899]
I would like to ask to add a new FR for ASN repository, current Netbox version doesn't provide repository for ASNs
This is important to be able to list all ASNs which are used and make right planning for future assignments
Ideally it would be good to have ASNs stored in repository the same way as we have it for devices/Prefixes/Circuits/Virtual Machines

**Comment by DanSheps** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jeremystretch** [comment]
Aside: I feel like we're seeing more and more people submitting issues without following the template provided by GitHub. @amaizenshtein when you go to [create an issue on GitHub](https://github.com/netbox-community/netbox/issues/new/choose), you should see a choice of the type of issue to open:

![Screenshot_2021-03-01 netbox-community netbox](https://user-images.githubusercontent.com/13487278/109518210-098f9100-7a78-11eb-9013-d8fa25925d1b.png)

Clicking any of these will present the issue form with the issue template already filled in. Do you see this? And do you see the template (Markdown code in the text field) after clicking one of the green buttons?

**Comment by amaizenshtein** [comment]
@jeremystretch yep I see it, let me reapply
