### ISSUE TITLE
Drop port_speed and upstream_speed fields from CircuitTermination

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5902]
### Proposed Changes
Remove the `port_speed` and `upstream_speed` fields from the CircuitTermination model (the first two fields pictured below).

![Screenshot_2021-03-01 CenturyLink 1002840283 - Side A - NetBox](https://user-images.githubusercontent.com/13487278/109567539-81c77800-7ab3-11eb-9313-41a8b3290c16.png)

### Justification
These fields predate NetBox's ability to track individual interfaces, and are largely obsolete. Their naming is also somewhat confusing. I'm curious to see whether anyone is still relying on them.

**Comment by a-d-v** [comment]
We are relying on this field for QoS purposes, where the configuration requires circuits to be configured with a speed lower thah the interface speed.
I agree the naming is somewhat confusing, but hope we can keep this functionality.
Would renaming to Egress and Ingress speed be better?

**Comment by phurrelmann** [comment]
This is commonly used to model asymmetric DSL or FTTH  circuits. E.g. the physical interface is 1G but the circuit speeds are sth. like 100/40 or 500/100.

**Comment by sdktr** [comment]
We use it (the port speed) for DSL based circuits as well. We have cases were the L1 speed of A- and Z-termination (up vs downstream) are bigger then the commit of the circuit.

To be honest in our use case the fields are abused according to the 'SoT way of thinking'. This is because we sync these L1 speeds based on the actual trained speed as reported by the DSL interface of the CPE, which we manage as a ServiceProvider. We should have these 'cached device facts' in some sort of TSDB instead to clearly distinct 'desired' (netbox) vs 'actual' (fancy tsdb cache product X) state.

**Comment by jeremystretch** [comment]
Alright, seems like these fields are still in use then. An argument could be made to rename them, but I don't think it's strong enough to justify a breaking change. Appreciate the feedback!
