### ISSUE TITLE
API: Get IP-Address objects which are assigned to an vm interface did not work

### ISSUE THREAD

**Issue by Mordecaine** [netbox-community/netbox#5997]
### NetBox version

v2.10.4

### Python version

3.6

### Steps to Reproduce

https://10.138.1.131/api/ipam/ip-addresses/?assigned_object_id=12&assigned_object_type=virtualization.vminterface

### Expected Behavior

https://10.138.1.131/api/ipam/ip-addresses/?assigned_object_type=12&assigned_object_type=virtualization.vminterface
should return only the address object, which is assigned to this virtual machine network interface

### Observed Behavior

I get back all address objects in netbox

In an earlier version I was able to get all IP address objects which were assigned to a virtual machine network interface:
https://10.138.1.132/api/ipam/ip-addresses/2369/?interface=nic01

In This version I tried the following:
https://10.138.1.131/api/ipam/ip-addresses/?assigned_object_id=12&assigned_object_type=virtualization.vminterface

But netbox returned all ip address objects

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by DanSheps** [comment]
There is no filter for this.  Instead, you need to use vminterface= or vminterface_id=

**Comment by DanSheps** [comment]
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by Mordecaine** [comment]
@DanSheps 
Thanks Dan. I have looking for this.:
"There is no filter for this. Instead, you need to use vminterface= or vminterface_id="

It worked fine with vminterface_id

**Comment by xcdr** [comment]
Hi, I have related question.

When creating instance of ipam.ip_addresses, I should use vminterface_id or assigned_object_type/assigned_object_id?

**Comment by jeremystretch** [comment]
@xcdr please start a new [discussion](https://github.com/netbox-community/netbox/discussions) instead of commenting on closed issues.
