### ISSUE TITLE
Cascade delete IP addresses with interfaces

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#6015]
### NetBox version

v.2.10.6

### Feature type

Change to existing functionality

### Proposed functionality

Steps to Reproduce:
- Create any device with Interfaces components
- Add IP address on interface
- Delete Device
- IP address is removed from the system

I propose to change the current behavior when removing an interface with assigned IP.
Now it occurs cascading IP address deletion with device and its interfaces despite user has prohibition on IP deletion. 

### Use case

Previously added IP address will return to the list of IP addresses and can be assigned instead of creating it again

Based on: https://github.com/netbox-community/netbox/issues/5945

**Comment by jeremystretch** [comment]
We generally avoid any workflows wherein data can be deleted unexpectedly. I personally would prefer to disable the deletion of an interface with assigned IP addresses, but it's open for discussion.

**Comment by ljb2of3** [comment]
I think I'd side with @jeremystretch on this one. Deleting the IP just because the interface got deleted would be unexpected behavior to me. However, there are times where the proposed functionality could be useful. Perhaps some sort of "deleting this interface / device will leave orphaned IPs (1.1.1.1, 2.3.4.5, etc). Delete these too?" prompt would be useful, but barring that if I had to choose between "auto delete IPs" and "block delete unless IPs are removed" I'd go with blocking the delete operation.

**Comment by abrahamvegh** [comment]
I agree with @ljb2of3, presenting the option, especially when the objects will be orphaned, would be nice, but otherwise I think one of NetBox’s strong suites is making it difficult to accidentally lose data.

**Comment by jeremystretch** [comment]
Somewhat related to #5418

**Comment by jeremystretch** [comment]
The best solution here might be to present the option to the user when an interface is being deleted. We should be able to add a checkbox labeled "delete _n_ assigned IP addresses" to the confirmation form.

**Comment by proudbro** [comment]
@jeremystretch , yes, good idea

**Comment by ljb2of3** [comment]
I like this idea. It gives you the option to delete or not, and seeing the
"delete n assigned IP addresses?" message works as a reminder that you may
be deleting the wrong thing if you didn't expect to see it.
