### ISSUE TITLE
revoke|delete user key from admin panel

### ISSUE THREAD

**Issue by azatuni** [netbox-community/netbox#6065]
### NetBox version

v2.10.4

### Feature type

New functionality

### Proposed functionality

Hi,

it will be great to have functionality to revoke/delete user keys. For example  from admin panel secrets => user keys => action => delete selected user keys

### Use case

In case if the user could be compromised the admin could not only change his password but also revoke/delete his key.

**Comment by jeremystretch** [comment]
We need to update the admin actions for the model to include the "delete selected" action (which is normally available by default).

**Comment by jeremystretch** [comment]
Ok, I remember why we did this originally. It's because the UserKey manager has had bulk deletion disabled. This helps prevent the accidental deletion of all UserKey instances, which would render the entire set of Secrets inaccessible.

Let's keep this as-is for now to be safe. It may be worth revisiting the idea once the secrets functionality has been split off into its own plugin (see #5278). Also note that user keys _can_ be deleted through the admin UI individually.
