### ISSUE TITLE
Deleting a single device role raises exception

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6174]
### NetBox version

v2.10.10

### Python version

3.8

### Steps to Reproduce

1. Add a Device Role "Device Role A"
2. Assign the device role to a device or VM
3. Go to Devices -> Device Roles
4. Find "Device Role A" and click the delete icon on the right hand side
5. Confirm deletion

### Expected Behavior

An error saying you can't delete the role due to it being assigned to device(s).

### Observed Behavior

An AttributeError is raised. 'DeviceRole' object has no attribute 'get_absolute_url'

This is working as expected in the 2.11-beta.

**Comment by jeremystretch** [comment]
Looks like this bug has been lurking around for a while. The exception is indeed triggered because the DeviceRole model lacks a `get_absolute_url()` method. The ipam.Role model would have the same issue, except that we allow roles to be deleted even if assigned to prefixes and/or VLANs (the assignment gets nullified).

A workaround to this is to select the desired device role(s) from the list and click the "delete selected" button at the bottom of the page: The bulk edit functionality doesn't trigger the error. Given that a viable workaround exists and this is effectively fixed in the upcoming v2.11.0 release, I'm going to close this out. I appreciate the report though!
