### ISSUE TITLE
Interface descriptions are lost when I create a new device from a device type 

### ISSUE THREAD

**Issue by FehmiBB** [netbox-community/netbox#6261]
### NetBox version

v2.10.5

### Python version

3.6

### Steps to Reproduce

1. create a new device type
2. assign an interface
3. add a description to this interface
4. create a new device based on this device type

### Expected Behavior

The description assigned to the interface in the device type should also be found in the interface of the created device 

### Observed Behavior

The interface description gets lost

**Comment by jeremystretch** [comment]
This behavior is intentional. The description on a component template is used to describe the component itself, whereas the description on an instantiated component is relevant to the specific device or connection. It wouldn't make sense to automatically replicate descriptions from device types to devices, because doing so would result in a lot of redundant information.
