### ISSUE TITLE
Pre-Change-Data missing on cascaded Deletions

### ISSUE THREAD

**Issue by moonrail** [netbox-community/netbox#6389]
### NetBox version

v2.11.3

### Python version

3.8

### Steps to Reproduce

1. Create a Device/VM
2. Create a Journal-Entry on this Device/VM
3. Create two Interfaces on this Device/VM
4. Create a IP on the first Interface
5. Delete the first Interface
6. Look into Changelog (or API /extras/object-changes) and find, that the IP-Address-Entry will not have any "Pre-Change"-Data
7. Delete the Device/VM
8. Look into Changelog (or API /extras/object-changes) and find, that the Interface- and Journal-Entries will not have any "Pre-Change"-Data

### Expected Behavior

Pre-Change-Data should be in the Changelog.

This is the case, if e.g. an IP-Address is deleted directly, but not when its deleted by a cascade.

### Observed Behavior

Pre-Change-Data is missing in the Changelog, when an object is deleted by a cascade.

**Comment by jweiher** [comment]
Hi,

to me the way and locations where the snapshot method of the ChangeLogginMixin is called seems a bit odd. I think the reason why it is not working on related models is simply because it gets called in the views when fetching a single object and it does not know anything about related objects.
In my opinion it would be a better solution to wire the calling of the snapshot method somewhere in the models so all of the changelogging happens under the hood and is not scattered around the codebase.
just my 2 cents

-- Jan

**Comment by jeremystretch** [comment]
Opting to put the call to `snapshot()` in the view was a performance optimization: We only want spend time taking a snapshot if we anticipate making changes to the model. For instance, we wouldn't want to take a snapshot of each instance in a list if we're just viewing a list of objects with no intent to modify them.

That said, maybe it's an unnecessary optimization. We could try calling it inside `from_db()` for each instance to ensure that a pre-change snapshot is _always_ present, though testing is needed to determine the performance impact.

**Comment by jeremystretch** [comment]
A lot has changed since this bug was opened, but this seems solvable now by simply calling `snapshot()` in the `pre_delete` receiver.
