### ISSUE TITLE
Routing Features

### ISSUE THREAD

**Issue by lilmike1464** [netbox-community/netbox#6425]
### NetBox version

v2.11

### Feature type

Data model extension

### Proposed functionality

For device interfaces, change "802.1Q Mode" to:
Mode:
  - Routed
    - PTP # Uses IP Unnumbered, mainly from Loopback addresses now a days 
    - Broadcast # Has an IP address directly on the interface
  - 802.1Q
      - Access
      - Tagged
      - Tagged (All)

Then allow a virtual interface to be assigned to multiple parent interfaces. The preference would b:
Virtual Interface: Loopback0
    IP Address: 192.168.1.0/32
    Parent Interfaces: Eth1/1, Eth1/2

Parent Interface: Eth1/1
  Mode: routed --> PTP
  Type: IP Virtual

### Use case

A lot of ISPs and data centers are now using IP Unnumbered for their MPLS and VxLAN Underlays. It would be helpful to be able to define links between Top of rack switches and aggregate switches as such. Multiple routing protocols use IP Unnumbered.

**Comment by DanSheps** [comment]
I still don't think we need routed mode based on the use-case described here.

Routed mode is implied when there isn't a 802.1q mode and the specific "mode" (broadcast/p2p) is implied based on the mask and/or connection.  If you have a virtual interface assigned to two physical interfaces, you can derive the configuration from that as well.

That said, one thing that isn't modelled well is a routed sub-interface as we currently have no way to capture the dot1q tag in a routed subinterface without marking it as a dot1q interface.

**Comment by jeremystretch** [comment]
> PTP # Uses IP Unnumbered, mainly from Loopback addresses now a days

This is heavily opinionated. An interface's treatment as point-to-point is a function of the address applied, rather than its "mode" as defined in NetBox. For example, you might have an 802.1Q-encapsulated point-to-point interface.

> That said, one thing that isn't modelled well is a routed sub-interface as we currently have no way to capture the dot1q tag in a routed subinterface without marking it as a dot1q interface.

Why wouldn't you just define the subinterface as access mode for the assigned VLAN?

**Comment by kvondersaar** [comment]
> Why wouldn't you just define the subinterface as access mode for the assigned VLAN?

The answer here would depend on the definition of a VLAN.   NetBox's model conflates a VLAN with an 802.1q tag, but this is not necessarily the case in real network operation.  Especially if you're utilizing things like QinQ and tag re-writes, or Layer 3 sub interfaces.    It is entirely possible to have a device with five physical interfaces with a subinterface on each of those physical interfaces and those subinterfaces utilize the same 802.1q tag.  That does not mean that those interfaces bridge into the same bridge domain.   In fact, they wouldn't bridge at all.  But without some external understanding of the device you model 5 interfaces that bridge into the same VLAN by applying a VLAN object.   Or you end up creating 5 unique but otherwise pretty indiscernible VLAN objects, one per subinterface.

Personally I think deriving the "routed" mode from the fact that the interface has no 802.1q mode is fine and pretty intuitive.  That same implicit information could be maintained by having "dot1q_tag" as a property of a sub interface.  That property can be set manually, or implicitly overridden by setting the interface to 802.1q (tagged or untagged) mode which would then imply bridging.
