### ISSUE TITLE
The links in the "Elevation" part are broken

### ISSUE THREAD

**Issue by quentindavid** [netbox-community/netbox#6571]
### NetBox version

v2.11.6

### Python version

3.6

### Steps to Reproduce

1. Go in Elevation menu
2. Point on any device within a rack and note it's link URL

### Expected Behavior

You should see the reverse proxy URL ie https://reverse-proxy-url/dcim/devices/556/

### Observed Behavior

http://ip_of_backend/dcim/devices/556/

In the devices list, the links are working properly.

**Comment by quentindavid** [comment]
Same issue when you are in the "Racks" page, you select a rack. Then you have a visual illustration of the rack, and the link are wrong when you click on any device within the rack.

**Comment by quentindavid** [comment]
Well, it seems to be fixed if the value "ALLOWED_HOSTS" in the configuration page corresponds to the reverse-proxy front URL.

Which is still weird is that all URL are not consistent.

**Comment by jeremystretch** [comment]
NetBox doesn't inherently know what hostnames for which it may receive requests; this information must be forwarded to it by the HTTP frontend (e.g. nginx or Apache) in order to generate correct absolute URLs. See our [sample nginx and Apache configs](https://github.com/netbox-community/netbox/tree/develop/contrib) for reference.

Most URLs in the UI are relative to the path root (`/`). The rack elevations use absolute links because each elevation is actually an SVG image.
