### ISSUE TITLE
Include prefix utilization in API/model

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#6606]
### NetBox version

v2.11.6

### Feature type

Data model extension

### Proposed functionality

Currently, the prefix utilization is calculated after the database query has been made.
It would be great iw that utilization (in percent) is a value in the API of the prefix model.

### Use case

This way, we could filter out 100% used prefixes when using ObjectVar dropdowns or other ways of programmatic selecting prefixes with available space, without the need for extra coding and database queries

### Database changes

As per @jeremystretch  : This could be changed, as we did with storing prefix depth and child count in #6087

**Comment by jeremystretch** [comment]
There are two approaches to this:

1. Pre-render and store the utilization for prefixes as changes are made in NetBox, then include this value in the API serializer
2. Extend the serializer to call the `get_utilization()` method on demand

IMO the first option, while more challenging to implement, would be the preferred solution, as it also knocks out a good amount of overhead when viewing the prefixes list. The second option, because of the additional overhead it would impose on REST API requests, would probably need some mechanism to toggle its inclusion (similar to what we currently do with device/VM config contexts). I'd prefer to avoid that pattern where possible.

**Comment by zombah** [comment]
@jeremystretch I like the idea to be able get prefix utilization via api, if this feature acceptable i want volunteer to devel pr for this
