### ISSUE TITLE
long netbox page load time

### ISSUE THREAD

**Issue by sgelineau17** [netbox-community/netbox#7168]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

Compared Netbox in version 2.11.12 versus version 3.0.1

### Expected Behavior

Optimisation

### Observed Behavior

Hello,

I have a Netbox server in production which is in version 2.11.12. I also have a qualifying Netbox server which is in version 3.0.1. The qualification server is a production copy, it has just been updated, the characteristics of the VM are identical.

Version 3.0.1 is much longer to find than version 2.11.12.

Both servers are on a fully up-to-date CentOS 8 basis.

The production Netbox server runs Python in version 3.7 and the production Python 3.9 server.

I give you screenshots of a loading of the Prefixes tab with the debug on the network tab.

![Netbox-Prod](https://user-images.githubusercontent.com/61157268/132033250-5da10380-759c-4d68-b1a7-7e85b9cb7bdf.png)

![Netbox-Qualif](https://user-images.githubusercontent.com/61157268/132033052-324b208c-32ab-4a64-8940-312650536982.png)

**Comment by DanSheps** [comment]
Testing on internal test instances, I see a lower load time on v3 then on v2 for the prefixes with a larger number of prefixes.

Could you provide more information?  I see 572 prefixes listed on the v3 instance but no prefixes are displayed, likewise the v2 instance has no prefixes displayed.

Can you provide the following information for each instance:

* Prefix count
* VRF count
* Tenant count
* Site count
* IP Address count
* Column configuration (displayed columns)

These all can have an impact on load times.

**Comment by Sislik** [comment]
Netbox 3.0.1 python 3.9, centos 7 loading 63547 IPs (DB size is 260 MB)
![image](https://user-images.githubusercontent.com/64298143/132049141-27b768cc-4de2-4e08-9b81-aa8e0dd18453.png)

Netbox 2.10.4 python 3.6, centos 7 loading 63547 IPs (DB size is 769 MB)
![image](https://user-images.githubusercontent.com/64298143/132049224-feb6af3f-1fa1-411c-abf4-46ee6174a951.png)

same DB backend servers, upgraded clone of web server. In generic the 3.0 is way faster than older version and upgrade reduced the DB size quite a lot.

**Comment by jeremystretch** [comment]
Let's take a few steps back here. Pasting screenshots from your browser is not going to work. You're also randomly using v2.10.4 above whereas your initial report was for v2.11.12.

First, you need to set up two instances of NetBox (one running v2.11.12 and one running v3.0.1) with the **same exact data** and configuration. This is crucial to identifying a reliable baseline.

Then, once those have been set up, you'll need to use a tool like `curl` to make the actual HTTP requests. There are myriad factors which may impact the performance of a general purpose web browser, and we need to isolate as many of those as possible. `curl` works great for this because it's a very low-level tool, and we can call it with `time` to get exact measurements. For example:

```
$ time curl https://netbox/ipam/ip-addresses/
```

It's best to run each request a number of times and take the average. Then you can compare measurements between the two installations.

**Comment by Sislik** [comment]
@jeremystretch I'm different user :) so there is just original post and my example, that there is no issue on 3.0.1 and it is way faster in my case with same test he did :)

**Comment by jeremystretch** [comment]
Closing as there has been no further response from the poster.
