### ISSUE TITLE
API-Version response header missing

### ISSUE THREAD

**Issue by gstorme** [netbox-community/netbox#7198]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

Install or upgrade v3.0.1
curl -I https://netbox/api/

### Expected Behavior

Version 2.x and 3.0-beta2 gave these responses:
API-Version: 2.11
API-Version: 3

### Observed Behavior

Since 3.0.1, there is no API-Version response header

**Comment by gstorme** [comment]
It's because of https://github.com/netbox-community/netbox/commit/d2fe59ae8f9c34c1f8a7d51c0d113348d7bed937#diff-a884cc97453294b269cf8c9ca6839327b8b3b2dd453102266a9c1899fa7fe409

When I add request header "Content-Type: application/json", it returns the API-Version response.

**Comment by jeremystretch** [comment]
This change was intentional: The inclusion of the nonstandard `API-Version` header is of no significance to web browsers and should have been omitted for non-JSON clients.

@gstorme does this still impose an issue for you, or are you good now with the addition of the `Content-Type` header in your queries?

**Comment by gstorme** [comment]
Ok clear, works fine with the request header, so all good
