### ISSUE TITLE
Add color field to interfaces

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#7249]
### NetBox version

v3.0.2

### Feature type

Data model extension

### Proposed functionality

See #3682.

### Use case

Network devices can also have color coded ports, for example to differentiate WAN and LAN ports of a consumer grade router.

### Database changes

Yes, similar to #3682.

### External dependencies

No.

**Comment by thatmattlove** [comment]
Is there any reason why tags isn't suitable for the use-case? Tags are also colored, and you can assign more than one, and consume them in other useful ways (filtering, API, etc).

**Comment by jeremystretch** [comment]
I'm with @DanSheps on this. I don't see why it would even be necessary to track these colors, since the interfaces are already labeled. FYI color was added to pass-through ports because different color modules are often used to convey some attribute of the physical path. Such is not the case with interfaces. IMO if you really need to track this, a custom field is the answer.
