### ISSUE TITLE
Unable to load documentation, file not found: /opt/netbox/docs/models/extras/customfield.md

### ISSUE THREAD

**Issue by xth0331** [netbox-community/netbox#7392]
### NetBox version

v3.0.3

### Python version

3.8

### Steps to Reproduce

1. Create a other
2. Click on "add Custom Fields"
3. Click on the "?HELP" question mark

### Expected Behavior

Documentation about the feature appears.

### Observed Behavior

Unable to load documentation, file not found: /opt/netbox/docs/models/extras/customfield.md

**Comment by jeremystretch** [comment]
Looks like we're missing model-specific pages for a few models under extras, including custom fields. Should just need to refactor the existing documentation a bit.

Also relevant: #7372 has replaced the embedded modal with a simple hyperlink in the upcoming release, which will result in a 404 (rather than the error above) when a linked file is missing.
