### ISSUE TITLE
Save button on top

### ISSUE THREAD

**Issue by rfl64** [netbox-community/netbox#7422]
### NetBox version

v3.0.4

### Feature type

Change to existing functionality

### Proposed functionality

Would be possible locate Save and other buttons that are at the bottom of the page at top position?

### Use case

Every device, interface, etc, when I want to save I must use vertical bar to move page from top to bottom to save.

thanks in advance.

**Comment by jeremystretch** [comment]
IMO this could lead to confusion. I'm also not sure where you would place the buttons to look natural.

**Comment by jeremystretch** [comment]
ISTR we've tried the fixed/floating effect in the past and never got it to work right. Maybe it's more feasible since the UI overhaul? I'll mark this as `needs owner` for anyone who would like to give it a shot.

**Comment by bluikko** [comment]
While having another session of scrolling up/down because of the `Edit` and `Delete` buttons I had an idea that could be one option - it does feel a bit strange though:

Could the "action buttons at the bottom of the page" be added to the bottom of the menu column at the left? Perhaps only visible when the buttons at the bottom of the page are not visible?

I.e. at the bottom left corner of the viewport. If the menu is "collapsed" to icons only, then it could show the "Edit" icon and "Delete" icon with the right button color (same as the buttons at the bottom of the page).

It does feel a bit like "abuse" of the menu but this would solve the button visibility/scrolling requirement issue in quite a nice way. If the "fixed/floating" buttons are difficult to implement then perhaps it could be an easy way too.

**Comment by rhyser9** [comment]
Something I just discovered that makes my life much easier, is that you can submit forms with the Enter key. Reduces the need to scroll down and hunt for the save button.

**Comment by bluikko** [comment]
> Something I just discovered that makes my life much easier, is that you can submit forms with the Enter key. Reduces the need to scroll down and hunt for the save button.

Does not work always. For example try it in a field which input type is a drop-down box. And choose to edit a drop-down box that is surrounded by other drop-down boxes... I've opened #7667 about that.

Another reason is that there might be several buttons at the bottom. For example: "save & continue editing", "save", "cancel". Enter may use the first one, while the user might want the second.
