### ISSUE TITLE
 Confirmation of changes

### ISSUE THREAD

**Issue by SerhiiZahuba** [netbox-community/netbox#7426]
### NetBox version

v3.0.4

### Feature type

New functionality

### Proposed functionality

I propose a new functionality, namely confirmation of changes or changes. For example, 5 people work in the infrastructure department (4 juniors and 1 of their leader), if one of the junior makes a change, then his manager must confirm this change. For example, I added new equipment to netbox, it is not immediately displayed in the system, but goes into an application that my manager must confirm.

### Use case

Thus, we will be able to check what each employee contributes and whether he did it correctly.

**Comment by jeremystretch** [comment]
This sort of thing has come up in conversation a few times. It definitely sound like it'd be a cool feature, though we'd need to iron out the implementation.

Presumably, we could save the "proposed" new state of an object in a dedicated ProposedChange model (or something to that effect). A user with the proper permission could then either apply the change, updating the object with the new attributes, or reject it. I would assume that any changes to an object applied in the interim would invalidate the proposed change, to avoid potential issues with data integrity.

How to best handle permissions requires some more though, as this introduces a new concept: We need a way to indicate that a user is allowed to _propose_ creating/modifying a model, but not to actually apply the changes. Or, alternatively, leave the existing permissions unchanged and just offer the option of proposing a change instead of applying it immediately.

**Comment by rfdrake** [comment]
I have an idea for this, but I'm not sure if it's going to be easy to write.   I saw an open issue about exporting and importing more object types as YAML and it got me thinking about something like this:

It would be very nice if we could dump an entire site (or tenant, or any other aggregate object) with subobjects as JSON or YAML.  At that point it would be a little easier to export and import data from different netbox instances.  Then a designer might have their own instance where they do all the planning for a new site.  It gets reviewed in another instance and once approved it would be uploaded to a master instance.

There is still some question marks, like how do you handle duplicated data on a merge, and what do you do with circuits which leave a site?  But those details might be punted for later.

**Comment by jeremystretch** [comment]
I think @ziggekatten is right on the money here. While an interesting idea, it's almost certainly not going to be worth the trouble to pursue, at least at this stage in NetBox's development. It might be something to reconsider when/if we amass a larger development team.
