### ISSUE TITLE
Adding connection: before selecting "device", "name" gives list of all ports in rack

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#7528]
### NetBox version

v3.0.7

### Python version

3.8

### Steps to Reproduce

1. Add a device with a power port (say)
2. Click on the "connect" button next to the power port
3. On the "B" side form, click the port "Name" field, **before** selecting a device

### Expected Behavior

Not to be able to select a port until the device has been selected.

### Observed Behavior

The drop-down menu shows *every* port on *every* device in that rack:

![image](https://user-images.githubusercontent.com/44789/136947746-9531fc85-efe6-48ee-a34d-f5bb95c2681a.png)

Since the port names are not qualified by the device name, this isn't useful, yet potentially it requires rendering many hundreds of ports.

I didn't *think* it used to work this way, but I could be wrong.

**Comment by jeremystretch** [comment]
This is expected behavior. NetBox is returning the list of available components given the constraints provided. There are many cases where such behavior is desirable: For instance, suppose there is only one PDU in a rack. It would make no sense to force the user to select that PDU before selecting an outlet.
