### ISSUE TITLE
Serial number field for Virtual machines

### ISSUE THREAD

**Issue by pmusolino-rms** [netbox-community/netbox#7537]
### NetBox version

v3.0.7

### Feature type

Data model extension

### Proposed functionality

Would it be possible to add a serial number field to virtual machines?  I know it could certainly be added as a custom field, but many network devices as they exist in either public/private cloud or vm clusters still retain serial numbers for licensing and seems to be something that could be a standard but not required field.

### Use case

Exporting data and inventory/licensing tracking of non physical devices.

### Database changes

New field to Virtual machine table

**Comment by rodvand** [comment]
I can see a use case for this. More and more functionality is moving from hardware appliances to virtual appliances and the vendors tend to stick to their "everything needs a license" model. So my virtual Palo Alto firewall has a serial number, and I can see the value in recording this. Not sure if the use case is "wide" enough to warrant a separate field encompassing all virtual machines, but I've definitely thought about it.

**Comment by aauerswald** [comment]
Hello,

please add the serial field to virtual machines. At the moment we use a custom field, but this is not searchable.

**Comment by ryanmerolle** [comment]
This could be a good candidate for 3.6

**Comment by tagur87** [comment]
I also agree that this would be a helpful field for virtual machines. We are starting to migrate our VPN devices from physical hardware to virtual appliances. These virtual appliances (Ivanti Connect Secure) have serial numbers that are used for registration with the vendor. We have other vendors that also do this...(kemp, clearpass, etc).

I would be willing to try to add this field, since it seems fairly straightforward to add to the VM model.

**Comment by tagur87** [comment]
Anyone opposed to aiming at 3.7 for a milestone? I worked up a simple prototype yesterday mirroring the field used in devices. 

Any concerns with me working on that?
