### ISSUE TITLE
NAPALM require a primary IP although there is code to use the device name

### ISSUE THREAD

**Issue by AlbanBedel** [netbox-community/netbox#7660]
### NetBox version

v3.0.8

### Python version

3.9

### Steps to Reproduce

1. Configure a platform with a NAPALM driver
2. Set the platform on a device which has a name but no primary IP
3. Test the napalm API code
4. Go to the device page

### Expected Behavior

1. The API call resolve the device name to connect to the device
2. The "Status", "LLDP Neighbors" and "Configuration" tabs are visible in the device view

### Observed Behavior

1. The API call fail with "This device does not have a primary IP address configured."
2. The "Status", "LLDP Neighbors" and "Configuration" tabs are not visible

**Comment by AlbanBedel** [comment]
Reverting 7788bf3 was intentional?

**Comment by jeremystretch** [comment]
> "This device does not have a primary IP address configured."

Apparently.

**Comment by DanSheps** [comment]
> Reverting [7788bf3](https://github.com/netbox-community/netbox/commit/7788bf3ce34aaa98d83bfafdb14bc82a7079e7a5) was intentional?

Not sure why you think this is reverted, the logic is still present.

**Comment by kkthxbye-code** [comment]
@jeremystretch @DanSheps - I think you are misunderstanding him, and that he is correct.

The current code:

https://github.com/netbox-community/netbox/blob/61b61b1bc07c08c10256cb645327d074622b938f/netbox/dcim/api/views.py#L411-L436

As you can see, the codepath in the else from L422 is dead code because the check for device.primary_ip was added back at some point (L412-413). device.primary_ip can never be falsy at that point, as it's already checked and thrown if falsy. If this was really intended, the dead code should be removed.

What's weird is that I can't find a diff for a commit where the code in L412-413 was added back, at least not from github when viewing the file history. Seems to indicate that he could be right that it's a merge mishap.

**Comment by jeremystretch** [comment]
This is tagged as "needs owner" for whoever would like to dig further into it and propose a specific change.

**Comment by AlbanBedel** [comment]
@kkthxbye-code yes it is a merge mishap, I spent a whole evening tracking it down to 22ee670 where you can see that one parent bring 7788bf3, so this branch doesn't have the early check, and the other parent commit do.

I proposed a specific change in my first comment, but @DanSheps added some requirement that are going beyond just fixing the broken merge.

**Comment by DanSheps** [comment]
You could do a nested if or set some control variables to properly check using and/or

```
    {% if perms.dcim.napalm_read_device and object.status == 'active' and object.platform.napalm_driver %}
        {% if object.platform.primary_ip or object.name|resolvednsnamefunction %}
```

Obviously, you would have to craft a filter for the template engine to resolve the dns name, but that shouldn't be too bad (literally just what is in the code with a try/catch statement)

**Comment by kkthxbye-code** [comment]
> Obviously, you would have to craft a filter for the template engine to resolve the dns name, but that shouldn't be too bad (literally just what is in the code with a try/catch statement)

Doing a DNS lookup before rendering the page is not ideal in my opinion. Page render is blocked until a response has been  received.

> Any changes you make to the template must check either that the hostname is resolvable or there is a primary IP available

Can't we just fail in the napalm API call if the hostname doesn't resolve, the logic is already there? Why do we have to check in the template? If the host on the IP doesn't response the API call fails as well, that isn't checked in the template.

**Comment by DanSheps** [comment]
> Can't we just fail in the napalm API call if the hostname doesn't resolve, the logic is already there? Why do we have to check in the template? If the host on the IP doesn't response the API call fails as well, that isn't checked in the template.

To be clear, the original request is #4831

Tabs are there but are un-usable.  This gives false assumptions to a user that they might work.

My opinion is this:

* If the device resolves by hostname, it has an IP, that should be documented in the SoT
* We should only do napalm requests on devices with valid IP addresses.

Now, I get the use case, however I think this is still wrong.  Just because you don't use IPAM in NetBox doesn't mean you shouldn't at least have the primary IP documented in NetBox.

Just my 2c

**Comment by AlbanBedel** [comment]
> Tabs are there but are un-usable. This gives false assumptions to a user that they might work.

They would only be visible after you configure a platform with a NAPALM driver and set this platform on the device. Once that is configured I don't see what case is left were you wouldn't want the tabs to be visible.
 
> My opinion is this:
> 
> * If the device resolves by hostname, it has an IP, that should be documented in the SoT
> 
> * We should only do napalm requests on devices with valid IP addresses.
> 
> 
> Now, I get the use case, however I think this is still wrong. Just because you don't use IPAM in NetBox doesn't mean you shouldn't at least have the primary IP documented in NetBox.

My use case is network that use DHCP, so there is no fixed IP that can be documented.

**Comment by DanSheps** [comment]
> > Tabs are there but are un-usable. This gives false assumptions to a user that they might work.
> 
> They would only be visible after you configure a platform with a NAPALM driver and set this platform on the device. Once that is configured I don't see what case is left were you wouldn't want the tabs to be visible.

Platforms are not specific per device.  You are asking to infer the napalminess of a device from the platform.  The platform model is to give a hint about the operating system of a device (Can be as simple as `Cisco IOS` or as complex as `Cisco IOS-XE Catalyst 9300 17.03.03` or more).  The reason the napalm driver is there is because the napalm driver is generally common for a given operating system.

I think a better approach, may be to allow a new field for a device's management interfaces that defines whether the device's management IP is DHCP or not.  If that is the case, then perhaps show the tabs and allow napalm lookups by hostname.

**Comment by AlbanBedel** [comment]
> I think a better approach, may be to allow a new field for a device's management interfaces that defines whether the device's management IP is DHCP or not. If that is the case, then perhaps show the tabs and allow napalm lookups by hostname.

So currently the "napalminess" is inferred from "has a platform with NAPALM driver and an IP", I don't think that making this logic even more complex is a good idea. If what you  want is to be able to disable NAPALM on selected devices why not just add a device field to disable NAPALM?

**Comment by DanSheps** [comment]
My main point is that this seems very much an edge case, and it should be functionality that someone opt into per device not opt out of per device
