### ISSUE TITLE
Uploading / Deleting / Editing images does not generate a change log

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7812]
### NetBox version

3.0.9

### Python version

3.8

### Steps to Reproduce

Upload / edit or delete an image associated with a rack, site or location. No change log entry is generated.

I am using S3 storage for images, I have not tested if change logs are generated when using other storage methods.

### Expected Behavior

A change log item is generated for adding, modifying or deleting an image.

### Observed Behavior

No change log is generated.

**Comment by jeremystretch** [comment]
While I think it's fair to approach this as a bug, I'm going to treat it as a feature request primarily because the resolution involves modifying the ImageAttachment class to inherit from ChangeLoggedModel, which introduces a new field (`last_updated`). Also for this reason, I'm going to implement this within the `feature` branch for v3.1.
