### ISSUE TITLE
Images in Tenants os Custom fields

### ISSUE THREAD

**Issue by arleinalesso** [netbox-community/netbox#7842]
### NetBox version

3.0.10

### Feature type

New functionality

### Proposed functionality

Add images box in Tenants os Custom fielads for any options. PLease.

Thanks

### Use case

Add topology, photo or any specific information.

**Comment by arleinalesso** [comment]
Please, add E2000 PC and E2000 APC on front ports and add GPON and XGPON on interfaces device.
Thanks

**Comment by jeremystretch** [comment]
Please spend some more time on your request above. It's not clear what you're asking for or why.

> Please, add E2000 PC and E2000 APC on front ports and add GPON and XGPON on interfaces device.

Please open a separate FR for this, including justification for the addition.

**Comment by arleinalesso** [comment]
Including a field to place images on tenants is so that we can place delivery circuits for the client, that is, place a visio drawing with information about the circuit that the client has.
Another use is in custom fields so we can add images wherever we need them.
These changes are to give more flexibility to the excellent Netbox.

Thanks

**Comment by jeremystretch** [comment]
Image attachments are intended to enable the association of photographs with physical objects, which is why they apply only to physical resources in NetBox (sites, devices, etc.). NetBox is not a good place to store documentation files such as topology drawings. It is recommended instead to store these on a suitable file server or content management system, and link to those files from the NetBox objects. (This can often be automated using a [custom link](https://netbox.readthedocs.io/en/stable/models/extras/customlink/)).
