### ISSUE TITLE
Interface to VRF Associations

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7852]
### NetBox version

v3.0.10

### Feature type

Data model extension

### Proposed functionality

Enable interface to VRF mapping.

### Use case

Generally NetBox should support most base functions an interface supports.  One obvious function missing in the current model is the ability to map interfaces to a VRF.

I do not know we can rush in to this without first discussing if and how should IP assignment be limited be associated to an interface only if they are both in the same VRF.  This constraint could be challenging to implement given the current IP model.  I think at the very least the MVP would just allow interfaces to be associated to a VRF without any constraints on IP assignments.

**Comment by jeremystretch** [comment]
> I do not know we can rush in to this without first discussing if and how should IP assignment be limited be associated to an interface only if they are both in the same VRF.

We probably don't want to enforce any validation around this, especially since it would prevent users from assigning any VRF IPs to an interface until that interface has been assigned to a VRF. I also imagine some users will prefer to assign only IPs or only interfaced to VRFs. Also [custom validation](https://netbox.readthedocs.io/en/stable/customization/custom-validation/) is an option now for users who may want to enforce this.

**Comment by ryanmerolle** [comment]
I agree with your logic.
