### ISSUE TITLE
Assigning a Site Group to a IPAM Prefix does nothing

### ISSUE THREAD

**Issue by soer7022** [netbox-community/netbox#7920]
### NetBox version

v3.0.10 & 2.11.9

### Python version

3.9

### Steps to Reproduce

1. Create a prefix and a site group
2. Click edit on the prefix
3. Assign the site group to the prefix
4. Click save
5. Click edit on the prefix
6. Notice that the prefix is not assigned to the site group

### Expected Behavior

I expect the Prefix to be assigned to the site group. And if this is not possible I at least expect to get an error

### Observed Behavior

No error, it just accepts and nothing happens

**Comment by jeremystretch** [comment]
Prefixes cannot be assigned to site groups. The site group field exists solely as a filter for the site field.

**Comment by zacho112** [comment]
Would it be an idea to add a scope to the prefixes like on VLANs? Eg. if you have a L2 network across multiple "sites"/buildings, you might need to document the device on site X but the VLAN/Prefixes etc. is on site A, which actually terminates the L3 info, which could be mapped to a site-group, instead of that site, so all "subsites" are able to fetch the info, without hardcoding anything.

**Comment by jeremystretch** [comment]
> Would it be an idea to add a scope to the prefixes like on VLANs?

This has been proposed under #6414.
