### ISSUE TITLE
No Cable Trace without Interface

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#7951]
### NetBox version

v3.0.9

### Python version

3.7

### Steps to Reproduce

1. Create Rack
2. Add patchpanel device with front and rearport
3. Add second patchpanel in same or other rack
4. Connect rearports
5. Connect a frontport to something that is not a interface (e.g. frontport of same patchpanel)
(connect as many device in series as you want (frontport device 1 -> rearport device 1, rearport device 1 -> rearport device 2, rearport device 2 -> frontport device 2 ...and so on...)  
6. Click cable trace on the cable

### Expected Behavior

The cable trace is shown

### Observed Behavior

'No paths found'

**Comment by DanSheps** [comment]
Hello,

This is not a bug, it is in fact an intended consequence of the new way cable traces are done.

**Comment by DanSheps** [comment]
> What is the benefit of this 'feature'?

This isn't a "feature", this is the way cable paths are done.  There **must** be a start interface/circuit for the path to be considered valid

**Comment by PaulR282** [comment]
So it can't be changed or patched, that it works without an interface?

**Comment by DanSheps** [comment]
Yes it can, but it needs to be developed as a feature and not as a bug.

At this point, because you don't seem to understand the process, I am first going to direct you to review the [Contributing guidelines](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md) as well as the wiki to review the [Getting Involed](https://github.com/netbox-community/netbox/wiki/Getting-Involved) section and the [Issue intake policy](https://github.com/netbox-community/netbox/wiki/Issue-Intake-Policy).

Once done, please open this as a proper feature request using the provided form for feature requests.
