### ISSUE TITLE
New model: business system

### ISSUE THREAD

**Issue by xth0331** [netbox-community/netbox#8048]
### NetBox version

v3.1.0

### Feature type

New functionality

### Proposed functionality

Is it possible to add a new model, which is used to describe business systems, such as OA or websites, which include virtual machines, servers, etc.

Not sure if it makes sense

### Use case

This can integrate and classify multiple physical resources and virtual machine resources

**Comment by apellini** [comment]
It could be useful to explain application stack present in your organization

**Comment by jeremystretch** [comment]
I'm not sure what you mean by "business system." Can you elaborate on your proposed implementation please?

**Comment by xth0331** [comment]
Sorry, my English is poor, For example, a search service,It contains multiple virtual machines.

**Comment by zombah** [comment]
> Sorry, my English is poor, For example, a search service,It contains multiple virtual machines.

I use tags for such things.
For example create tag busines_system_search_service and apply this tag  
to all involved elements: vm's, int's, ip's and etc.

**Comment by jeremystretch** [comment]
I'm afraid this isn't an actionable feature request without much more detail around the proposed implementation and its use case. Perhaps consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new) to work out exactly what it is you'd like to see added to NetBox. Once you've sorted out these details and fleshed out a complete proposal we can revisit the feature request.

**Comment by apellini** [comment]
Sorry for late response. This feature could be useful because we could create a relationship model based on Application that are running on our DC and relate them network resource to build standards to construct your Application Stack and giving modeling that could be used on CI/CD pipelines.

Below an example. Development team A develops applications based on LAMP Application stack and SysAdmin deploy three server for each application, one dedicted to Apache with mod_proxy module,  one for PHP backend and one MySQL/MariaDB for DB, this one is totally managed by DBA.

Each of this services has their management application on common environment that hosts Ansible, GIT Repo and Backup services.

Network Admins for having control of network opening needs to dedicate a network for each layer in a non-SDN environment.

Using this model we could correlate application layer to network in order to map and mantain this correlation and permits to automation to build correctly all application.

Also if you correlate network opening to this model you could create an automation that could clone openings in case of network expansion or implement network micro segmentation between layers.

**Comment by bluikko** [comment]
I too currently use tags for this sort of thing. But it will be not manageable in the long run as more "business systems" are documented in NetBox - there would be dozens of tags.

I too would find something like this useful. Much, much more implementation details would be needed...

Sounds like there would be a new model, say "Application", that could refer to other models. What models would it refer to? What attributes would such a model have?
