### ISSUE TITLE
Ability to pass on VLAN ID in bulk CSV interface import

### ISSUE THREAD

**Issue by nemo438** [netbox-community/netbox#8050]
### NetBox version

v3.1.0

### Feature type

New functionality

### Proposed functionality

Have the ability to pass on the VID when importing interfaces in the initial stage.

Suggestion csv untagged mode
```
device,name,type,mode,untagged_vid
Switch01,Gi1/0/1,1000BASE-T (1GE),access,173
```
Suggestion csv tagged mode
```
device,name,type,mode,tagged_vid
Switch01,Gi1/0/1,1000BASE-T (1GE),access,(173,186,998)
```

### Use case

When adding a new device, it would be nice to have the ability to import all information straight away. Sometimes it takes more time write an script to import than just to export and edit in excel.

**Comment by candlerb** [comment]
I don't think this can work just using the VID.  This is because the VID is not unique: you can have multiple distinct broadcast domains, using the same tag.

However it could work if you gave sufficient information to identify a single VID, which would depend on your environment. e.g. `{vid:173, site:"foo"}` if your vid's are unique per site.

**Comment by nemo438** [comment]
Sorry for late response, GitHub notification email was stuck in spam.

I think it would work perfectly to use the {vid:173, site:"foo"} at the import phase to specify VID and site.

If the user has the possibility to export data perform the mass update and then import it again it would be great.
