### ISSUE TITLE
missing available ip addresses in prefix after upgrade to 3.1.2

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#8173]
### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

1. upgrade from 3.1.1 to 3.1.2
2. go to any prefix "IP Adresses" ipam/prefixes/{ prefix id }/ip-addresses/

### Expected Behavior

See "IPs available" as in 3.1.1

![netbox-3 1 1](https://user-images.githubusercontent.com/3961842/147546313-8bc8b44a-4d96-48e6-b6d5-33a9f1b73c1c.png)

### Observed Behavior

Only used IPs are shown

![netbox-3 1 2](https://user-images.githubusercontent.com/3961842/147546348-3a08017f-8dc7-4f54-8b15-36ed5dd3e6f5.png)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8131 for further discussion.

**Comment by DanSheps** [comment]
Duplicate of #8131

**Comment by bluikko** [comment]
I would propose to fix the subject line of #8131. It is not even found when searching for "free" or "available" (or did not when I raised my similar duplicate issue), since it only talks about a button and not the free indicators.

Yes it is about the same issue, but the OP has nothing about the indicators and only talks about a button.
