### ISSUE TITLE
Employ HTMX to render emedded tables

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8184]
### NetBox version

v3.1.2

### Feature type

New functionality

### Proposed functionality

Leverage HTMX to allow ordering and paginating tables of related objects embedded within an object view. For example, when viewing images attached to a device (originally raised in #7003). We should be able to leverage the existing functionality on ObjectListView to support this.

### Use case

Provides a more responsive and efficient UX.

**Comment by sdktr** [comment]
While great for the user experience, i'm worried that all the effort into htmx will later on be a reason to not employ an api-based gui because of all the duplicate effort?

The api based gui might not be a goal in itself, but will probably not become one anytime soonish if further investments in the bootstrap framework are continued?

**Comment by jeremystretch** [comment]
What's nice about HTMX is that it can be implemented opportunistically with very little effort relative to a complete API-driven framework like React or Vue. In fact, we may find that its strategic deployment obviates the need for such a framework entirely. In any case, there are myriad other factors which have prevented work on implementing a new UI framework over the past several years, not the least of which is an absence of any interested volunteers.

**Comment by jeremystretch** [comment]
I'm making great progress with this. Still have a number of embedded table to update, but that's mostly boilerplate work.
