### ISSUE TITLE
Many views broken in 3.1.3 due to moved "templatetags/tag.html"

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#8187]
### NetBox version

v3.1.3

### Python version

3.8

### Steps to Reproduce

1. Update from 3.1.2 to 3.1.3
2. Try to open Devices or Virtual Machines views, there is an error about missing "utilities/templatetags/tag.html"

It seem to stem from https://github.com/netbox-community/netbox/commit/f369b5f588ad29d9de0f36cfdce586bd3769e7eb where `tables.py` was not updated after file moved?

Now it might also be that I screwed up my update, but it is the same automated process that has worked for a number of updates.

### Expected Behavior

The views should work like before.

### Observed Behavior

It seems like the file `netbox/utilities/tables.py` has a wrong path for an include, seems some files have moved around.

It is only result of my quick troubleshooting while trying to get the production instance back up - my fault, should have actually clicked around plenty in the testing instance before updating production....

**Comment by jeremystretch** [comment]
Looks like the template is being rendered directly by TagColumn, rather than using the `{% tag %}` template tag, so it was missed during cleanup.

As a temporary workaround, you can copy `netbox/utilities/templates/helpers/tag.html` to `netbox/templates/utilities/templatetags/tag.html`, or disable the "Tags" column in the table.
