### ISSUE TITLE
Add folder local/ to .gitignore

### ISSUE THREAD

**Issue by Houtek** [netbox-community/netbox#8210]
### NetBox version

v3.1.3

### Feature type

Change to existing functionality

### Proposed functionality

The topic "Troubleshooting LDAP" in the documentation for LDAP configuration mentions how to enable LDAP logging. 
In the example it says "'filename': '/opt/netbox/logs/django-ldap-debug.log'". 
When you do a "git status" you'll get the message 

> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>        logs/

When /logs would be added to .gitignore, the message wouldn't appear.

### Use case

Users who aren't that deep into git and its output wouldn't be unsettled

**Comment by jeremystretch** [comment]
I'm not sure it makes sense to add `logs/` as an exempt location. Typically, you'd export logs to whatever location is typical for your platform (e.g. `/var/logs`) rather than the local directory. However, I can think of several cases where it would make sense to have a general-purpose `local/` subdirectory that is exempted from git: I'm going to tweak this FR a bit to do that instead. (You'll then be able to use e.g. `local/logs/` if desired.)
