### ISSUE TITLE
Ability to link a virtual machine to a specific device in the cluster

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#8222]
### NetBox version

3.1.3

### Feature type

Data model extension

### Proposed functionality

The ability to Optionally connect a virtual machine to a device in a cluster.

### Use case

- to show where a VM (should be, or used to be) running - (we can keep this upto date with the api) or some of the sync scripts
- to document "pinned" vms - some vms even though in a cluster are pinned to specific hardware
- remove some of the need for "false" clusters. ( right now to show this data ether a custom field is needed or a fake cluster with just that single device in it)

### Database changes

extension to existing models

**Comment by ITJamie** [comment]
technically there are two "links".

one connection for "compute" one for "storage".

but id happily ignore the storage part. 
being able to link a vm to its compute device would ease some of our usecases.

**Comment by hagbarddenstore** [comment]
@ITJamie Wouldn't a simple "Pinned to Device"-field suffice?

I'm assuming you're talking about things like Nutanix CVMs on a Nutanix cluster, for which each CVM is pinned to "its" host Device.

**Comment by ITJamie** [comment]
If you mean a custom field for this. Yes that would work in a worst case as a workaround. Having the model updated would mean being able to have an actual working link to the device running the vm. 

It would also mean people could choose / configure the option much easier

**Comment by geor-g** [comment]
> I'm assuming you're talking about things like Nutanix CVMs on a Nutanix cluster, for which each CVM is pinned to "its" host Device.

In my experience, this feature request is quite common, wrt all kind of cluster people are running, regardless of the specific implementation: Ganeti, OpenStack, OpenNebubla, 'homegrown' stuff via corosync and pacemaker, etc.

If I understand this feature request correctly, this is about specifying a 'preference' wrt on which physical machine a virtual one should be running, by default.

It might help in situations like rebalancing clusters, doing (live) migrations to keep virtual machines running while rebooting or powering of physical ones, but still being able, afterwards, to get the virtual machines 'back on track', ensuring these run (again) on their preferred physical hosts.

While implementing this, we could think about doing the opposite as well: having a(n) 'exclusion link(s)' modelling relationship which don't work, because, for example, the same service, hosted on two virtual machines, shouldn't / must not be running on the same physical host.

**Comment by jeremystretch** [comment]
There's some related discussion under #4482.

**Comment by hagbarddenstore** [comment]
> If you mean a custom field for this. Yes that would work in a worst case as a workaround. Having the model updated would mean being able to have an actual working link to the device running the vm.
> 
> It would also mean people could choose / configure the option much easier

I didn't have a custom field in mind.


> > I'm assuming you're talking about things like Nutanix CVMs on a Nutanix cluster, for which each CVM is pinned to "its" host Device.
> 
> In my experience, this feature request is quite common, wrt all kind of cluster people are running, regardless of the specific implementation: Ganeti, OpenStack, OpenNebubla, 'homegrown' stuff via corosync and pacemaker, 'the cloud', etc.
> 
> If I understand this feature request correctly, this is about specifying a 'preference' wrt on which physical machine a virtual one should be running, by default.
> 
> It might help in situations like rebalancing clusters, doing (live) migrations to keep virtual machines running while rebooting or powering of physical ones, but still being able, afterwards, to get the virtual machines 'back on track', ensuring these run (again) on their preferred physical hosts.
> 
> While implementing this, we could think about doing the opposite as well: having (an) 'exclusion link(s)' modelling relationship(s) which don't work, because, for example, the same service, hosted on two virtual machines, shouldn't / must not be running on the same physical host.

Not quite what I was thinking about. A Nutanix Controller VM (CVM) can *only* exist on the Device it's pinned to. If the Device goes down, that VM is downed as well, it isn't moved anywhere.

If you have a 4 node cluster, each node have a CVM running on it.

Another example is VMs that requires a specific Device because that Device have specific hardware attached to it, so that VM can't function on another Device.

This could be modeled fairly simple by adding a new field to the VirtualMachine model (pinned_to) whereas modelling preference and exclusion groups becomes a lot more complex.

**Comment by ITJamie** [comment]
Not stale

**Comment by emersonfelipesp** [comment]
On Proxmox clusters, even using High Availability with storage sharing or not, the Virtual Machine is always running at a specific Device.

This Issue will really help me to improve [Proxmox Plugin](https://github.com/netdevopsbr/netbox-proxbox) without having to create custom models or custom fields, as I currently do.
