### ISSUE TITLE
Disconnect of circuits not being logged

### ISSUE THREAD

**Issue by elpedriyo** [netbox-community/netbox#8251]
### NetBox version

3.1.4 Demo Version

### Python version

3.9

### Steps to Reproduce

1. Have a termination circuit to be disconnected
![image](https://user-images.githubusercontent.com/3207791/148306693-a025ecb0-aae0-4aa2-b7eb-f21966a4e6e0.png)
2. Proceed with the disconnect of it
![image](https://user-images.githubusercontent.com/3207791/148306721-8fe53aa9-c2d2-4c16-8e53-b8fa192aa81a.png)
3.The change log of the circuit is not logging the disconnection
![image](https://user-images.githubusercontent.com/3207791/148306757-ab3c69ee-ac37-49c3-afe6-fcf24dfc6b95.png)

### Expected Behavior

As well as the creation is being logged in the change log, disconnection also to be logged

### Observed Behavior

Nothing is being logged.

**Comment by jeremystretch** [comment]
This is expected behavior. You're deleting the cable, which is recorded in the change log appropriately. No other objects are updated as a result of this, the same as when deleting a cable connected between two device components.

If you believe there's a reason to reflect these changes on the connected objects as well, you're welcome to open a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) citing your proposed implementation and use case.
