### ISSUE TITLE
Return the "request ID" change number when we do an API call

### ISSUE THREAD

**Issue by apo51** [netbox-community/netbox#8422]
### NetBox version

v3.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Hello

When a change is done (PUT POST or DELETE) in Netbox via API, we would like to get the "request ID" change number in return.

Using it, it would be possible to do a rollback of a specific API call, especially when a change implies several changes logs :
![image](https://user-images.githubusercontent.com/31479564/150507313-5bc0718c-b698-4ca5-ba59-a5649a599f76.png)
![image](https://user-images.githubusercontent.com/31479564/150507564-c1d05356-d52b-4644-a744-45c9d0fa6355.png)

Today we didn't find a way to associate an API call with a specific request ID (we only have the "time" but if we have 2 API calls really close, we don't know which one to pick in our pipelines)
I didn't see any changes on this behavior in Netbox 3.1 in the datasheets (correct me if I'm wrong).

Thank you

### Use case

When we do a change using the API, it would be very simple to retrieve all the changes done via the "request ID" and rollback them if necessary.

**Comment by jeremystretch** [comment]
Disregarding for the moment the feasibility of securing the request ID for the response, how would you return the request ID? We probably want to avoid injecting into the actual API data to avoid a breaking change; would an HTTP header suffice?

**Comment by apo51** [comment]
Ideally, it would be better to retrieve it from the API datas.  But if it's an issue for you, we can extract it from the HTTP header.

Maybe it could be added in the API in the future.

**Comment by apo51** [comment]
Hello

I was wondering if you could at the feasibility of this?

Regards

**Comment by kerryb48** [comment]
I was just researching if it was possible to get the request ID via the API response when I stumbled on this issue.  We have interest in this, or similar feature as well, with the goal of being able to rollback/unwind requests associated with an overall user workflow/automation.  I think returning it via HTTP header would be fine.  

I thought of a potential alternate approach as well. Possibly slightly more complicated, but would serve my scenario well :)

Rather than returning the request ID via each individual API call - perhaps the API could be extended to allow the requestor to (optionally) include a unique ID in the X-Request-ID HTTP header when calling the Netbox API, and that X-Request-ID could then be associated/related to the netbox request ID.  (ideally - would allow 1-to-Many)

A new API endpoint could be added to allow querying for all netbox request IDs associated with said X-Request-ID.  This would give us a way to identify any/all changes made as part of a particular user request (even if that workflow invoked multiple CRUD actions on the netbox API).

I am pretty new to Netbox, so I wont pretend to know whether or not this would be more difficult than securing the request ID for the API response, but thought I'd at least throw it out there!

**Comment by jeremystretch** [comment]
I suppose it would be necessary to return the change record ID inline with the data to support multi-object operations (e.g. bulk creation).

However, I don't think this is feasible given that the creation of the change record is queued for processing _after_ the response has been generated.

**Comment by baldgeek** [comment]
Is there a way to get creative? Can it return a unique value for in the 
queue that a second API call could use to get the change record ID(or 
something along the lines it isn't processed yet)

**Comment by jeremystretch** [comment]
You're certainly welcome to experiment with potential solutions, but I'd expect that any such workarounds are going to be a bigger headache than simply querying for most recent change log for the object.
