### ISSUE TITLE
Display description of fhrp group on fhrp selection

### ISSUE THREAD

**Issue by jlebherz** [netbox-community/netbox#8439]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

display the description of a fhrp group on selection fields

### Use case

better identify fhrp groups instead of only ID

![image](https://user-images.githubusercontent.com/20497503/150698666-fe65f66c-c06c-43ed-8f0c-63aa1236775d.png)

**Comment by jeremystretch** [comment]
The selection list shows the value of each object's `display` attribute returned by the REST API. As it would be inappropriate to include the description field in this value, this would require substantially changing how the dynamic selection field population works, which doesn't seem like a good use of developer effort right now.

**Comment by nomad-cyanide** [comment]
I second this. We have many FHRP groups and need a more descriptive field when documenting through the GUI, because lets be realistic, not all work is done through the API.
A name field or as described above, the description to be shown when selecting from the list, when assigning a FHRP-group. Otherwise it is rather useless to us, since all our FHRP groups have ID = 1, one on each vlan-interface on the router and we have a lot of those.

**Comment by jcoeder** [comment]
Can this be reopened and assigned to myself.  It seem the original reporter and contributor lost interest or forgot about this.  I would like to implement and get a PR out for it.  Thanks!

**Comment by jeremystretch** [comment]
@jcoeder per my comment [above](https://github.com/netbox-community/netbox/issues/8439#issuecomment-1020509770), there doesn't seem to be a feasible way to implement this without undertaking a considerable amount of work on the UI. What did you have in mind?

**Comment by jcoeder** [comment]
Thanks!  Sorry I am a little ignorant when it comes to Django and the layout of this project but the commit that was originally proposed seems to work just fine.  Though I cannot say if this may cause issues somewhere else or if it would require additional code.  I deployed this locally on at 3.2.5 instance and haven't noticed any issues after a couple days of hard use.

https://github.com/netbox-community/netbox/pull/8440/commits/64dea8a780f96382ea2f19752df322c4b3de2e45

Instead of this.

![image](https://user-images.githubusercontent.com/18300326/178090705-0ecd679f-8f21-4fb4-b1dc-96de9319913c.png)

It ends up looking like this.

![image](https://user-images.githubusercontent.com/18300326/178090719-7ff7943d-a861-4a34-b725-3ec91a67a688.png)
