### ISSUE TITLE
Enforce Uniqueness of IP address in only one interface 

### ISSUE THREAD

**Issue by jk-onnet** [netbox-community/netbox#8475]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Prevent duplication of IP address on same network interface.
I'm not sure is this logically and intended function on same network interface?

### Use case

Currently, we can add same prefix number of IP address with identical prefix number of IP address into an interface.
For example, 
1) add 192.168.1.24/24 into same network interface e0/1 of same device A1
2) add 192.168.1.24/24 into same network interface e0/1 of same device A1
If the development may takes time or irrelevant to core proposal, it can be ignored.

**Comment by jeremystretch** [comment]
I think it makes sense to enforce the validation as proposed, though I'm not sure how much of an impact doing so would have on performance. AFAICT we would need to retrieve all IPs already assigned to the interface in order to validate the new one; this could be problematic for bulk operations. Still, it's worth looking into.
