### ISSUE TITLE
Update requirements.txt for social-auth-core to use 'all' extras

### ISSUE THREAD

**Issue by adamweiss** [netbox-community/netbox#8502]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

In order to support OIDC and SAML in social-auth-core, requirements.txt would just need to be updated with "all" extras:

social-auth-core[all]==4.1.0

This is in base_requirements.txt, but it didn't make its way over to requirements.txt.

### Use case

OIDC and SAML-based SSO

### Database changes

N/A

### External dependencies

Change social-auth-core to social-auth-core[all] in requirements

**Comment by jeremystretch** [comment]
I'm not sure we want to direct people to install these ancillary packages by default if they're not necessarily going to be used. Users always have the option of installing these in addition to the default packages.

**Comment by jeremystretch** [comment]
Per the discussion in #8503, we're just going to drop `[all]` from the base requirement listing for `social-auth-core` due to installation issues with a dependent system library. Users can of course install additional components manually, or override this requirement in `local_requirements.txt` within their own installation.
