### ISSUE TITLE
Improve ways to insert devices in rack positions

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8552]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Adding a device to a rack can only be done through the 'Edit' form of a device.
This is simply, but not very inuitive and user friendly.

It would benefit to change the way this is done in the GUI.
1. The edit form's Position field could get a 'Pick from rack' button. This would popup the rack and allow you to select the position visually.
2. From the rack point of view
When hovering over a free position, only 'Add Device' is shown. This links to the creation form of devices.
It would benefit of this give you the option to link an existing device the, rather than creating a new one. I got the feeling that this rarely done from that view.
Same goes for the 'Add non racked device' in this view.

### Use case

This will help to visualize the racks when inserting devices into them.
Sometimes you know it has to go 'below that switch', without knowing the exact location

### Database changes

None

### External dependencies

None

**Comment by thefreakquency** [comment]
For item #2, I see 2 approaches:
* instead of "Add Device", something like "new / assign" with different targets. Any non-racked devices at the site should be available for selection, not only the ones assigned to the rack but not racked. 
* Similar to what we have for assigning an IP address to an interface, when clicking on "Add Device", the page "Add a new device" could have a second tab to allow device assignation. 

That same logic could be useful if implemented in the "Non-Racked Devices" table located under the rack view. Currently there's a "Add a Non-Racked Device" button that allow you to create a new device, but there's no direct option to assign a previously created device to the rack
