### ISSUE TITLE
Constraints for which devices get Custom Fields

### ISSUE THREAD

**Issue by lamoni** [netbox-community/netbox#8560]
### NetBox version

v3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

I think taking the "constraints" functionality we have for Groups/permissions and applying it to Custom Fields (possibly other things) would be great. As an example, I'd like to be able to constrain which devices get certain custom fields: cable managers get created as "Devices" in netbox just the same as Network devices, so when one team might want a custom field for dcim->device that is applicable to "cable managers", but then network devices also have that custom field now. Multiply this by 10 teams using the same Netbox instance and you get a lot of custom fields where maybe 10% of them are actually applicable/sensical for the device you're looking at.

### Use case

This functionality would clean up Custom Fields for multi-team netbox instances. Our example is: we've got asset management, VM teams, netops, etc... all using netbox, and all teams have various requirements for custom fields. Unfortunately that means a Network device (e.g. Juniper) has custom field options like "K8s instance". Makes no sense and we don't seem to have a way to limit which devices get those custom fields applied to them.

### Database changes

I'm unsure of what changes need to happen for the DB.

**Comment by lamoni** [comment]
I should mention, even if the Constraints just hid those custom fields (i.e. the custom field still exists for that device in the backend, it just isn't visible on the frontend), that would be ideal. So even just a "viewable" constraint would be a big improvement.

**Comment by Bierfass** [comment]
I would need the feature too.

**Comment by thefreakquency** [comment]
This would be helpful! It could extend to other fields like described in https://github.com/netbox-community/netbox/issues/5777

**Comment by kkthxbye-code** [comment]
@jeremystretch - A different solution to the same problem, that I actually implemented but never got around to creating a FR for, is just adding a "Hide when empty" option to custom fields. If it is toggled, empty fields are hidden from display, but still visible when editing the object.

It's a lot simpler to implement at least (just add one field to the model and some if statements to the templates). Not sure it satisfies the original intent of the FR though. What do you think of that solution @lamoni?

**Comment by jeremystretch** [comment]
I think there's some overlap between @kkthxbye-code's idea above and what was proposed in #9166. It's probably best to continue discussion of the "hiding" approach under #9166.

**Comment by jeremystretch** [comment]
> I think taking the "constraints" functionality we have for Groups/permissions and applying it to Custom Fields (possibly other things) would be great. 

These do not work the same as what's being proposed here. With permissions, constraints are determined by the permissions assigned to the user (and/or its group) associated with the request, and applied to queries for objects. What you describe above is the inverse: Starting with an object and then determining which custom fields to display based on constraints applied to each custom field, rather than the object. This is not feasible using the approach we employ for permissions enforcement.

I'm going to close this issue for two reasons:

1. A detailed, feasible implementation has not been proposed.
2. Once implemented, #9166 should mostly obviate the need for any more complex logic to omit custom fields.

That said, if anyone would like to submit a new FR outlining a **detailed, workable implementation** for such functionality, please feel welcome to do so.
