### ISSUE TITLE
Ability to filter interfaces by 'mark_connected' or those with a connected cable

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8580]
### NetBox version

3.1.7

### Feature type

New functionality

### Proposed functionality

Add the ability to filter interfaces under /dcim/interfaces/ by those that are marked / not marked as 'mark_connected' 
Add the ability to filter interfaces under /dcim/interfaces/ by those that have / have not got a cable connected

### Use case

A large switch with multiple interfaces can be trick to sort/filter in the current GUI. E.g. I have a 9410 switch with 358 interfaces, the /dcim/devices/<device>/interfaces/ view allows me to fairly quickly see which are connected / not connected albeit with no way to filter.

However when looking at /dcim/interfaces/ I can add the Mark Connected and Cable columns but i'm unable to filter by interfaces that are marked connected or have a cable attached

**Comment by jeremystretch** [comment]
> Add the ability to filter interfaces under /dcim/interfaces/ by those that have / have not got a cable connected

This is already provided by the `cabled` boolean filter on relevant models.

**Comment by jeremystretch** [comment]
We currently have two relevent filters in place:

* `cabled` - Boolean filter returning only models which have a cable assigned
* `connected` - Boolean filter for path endpoints which returns only models with a complete end-to-end path assigned

Given that the current `connected` filter serves a different purpose than whats being proposed here, we have two choices:

1. Extend the `cabled` filter to include objects with `mark_connected` set to True
2. Introduce a new filter for objects which are cabled _or_ which have `mark_connected` set to True
3. Introduce a new filter which matches only on the `mark_connected` field (this could not be practically combined with the `cabled` filter as the two are mutually exclusive)

IMO the second option is preferable because it preserves the existing behavior of the `cabled` function and avoids potential confusion. However, I'm not sure what the new filter should be called.

**Comment by jeremystretch** [comment]
> 1. Extend the `cabled` filter to include objects with `mark_connected` set to True

This makes the most sense IMO, but this is still open to debate.

**Comment by DanSheps** [comment]
I know it is a bit of a change, but, would it make sense to have the following filters?

- is_cabled
- has_endpoint
- is_connected

`is_connected` would include both cabled and marked conections.

The `has_endpoint` would replace the current `connected` filter currently.

It would be a breaking change and perhaps we can deprecate it over the next couple of cycles but argueably has_endpoint makes more sense then "connected" in my own eye.  I also prefer the is_/has_ semantic and we have used it elsewhere where we have a Boolean (`is_private` in RIR model, `is_full_depth`, `is_pool`, `has_primary_ip`, etc).

**Comment by baldgeek** [comment]
I personally like this option, but I am not the one who would have to 
implement it. |is_connected| always drives me nuts when I check the box 
"mark connected" and this still comes back false.

**Comment by arthanson** [comment]
@jeremystretch per discussion, proposal is (does this sound correct):

Keep the current two filters as is:

**cabled** - Boolean filter returning only models which have a cable assigned
**connected** - Boolean filter for path endpoints which returns only models with a complete end-to-end path assigned

Add a new filter:

**is_occupied** - Boolean filter for objects which are cabled or which have mark_connected set to True

**Comment by jeremystretch** [comment]
@arthanson that sounds good to me!
