### ISSUE TITLE
First available IP address on the prefix should not be a network address

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#8712]
### NetBox version

v3.2.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Create a prefix with the following data
   - Prefix: `65.49.10.64/26`
   - Is pool: `true`
2. Go to the prefix page for `65.49.10.64/26` and notice the `First available IP`

### Expected Behavior

The first available IP is the network address ie `65.49.10.64/26`

### Observed Behavior

The first available IP is the network address should be `65.49.10.65/26`

**Comment by tovin07** [comment]
Hi @abhi1693,

I think this is not a bug at all. Because you set `is pool` flag to `true`, therefore, all IP in this range should be valid to be assigned.

You can check this in the documentation:

- https://netbox.readthedocs.io/en/stable/core-functionality/ipam/#prefixes
- https://netbox.readthedocs.io/en/stable/models/ipam/prefix/

And in source code:

- https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/models/ip.py#L343

**Comment by abhi1693** [comment]
@tovin07 Somehow I read the documentation wrong. I'll close this bug
