### ISSUE TITLE
IPAM - Custom "Roles" for IP addresses - similar to new custom status function in v3.2

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9000]
### NetBox version

3.1.10

### Feature type

Change to existing functionality

### Proposed functionality

Allow custom IP Roles for ip address. 
right now its limited to "loopback, secondary, anycast, vip, vrrp, hsrp, glbp, carp". 
being able to add custom roles would be useful for internal usecases.
other usecases:
 - ptp - point to point links
 - primary - wanting to mark the primary ip of a pair of fw's
 - management - marking ips as mgmt ips

### Use case

Other parts of netbox has customisable "role"types (racks,devices,contacts). ip-addresses does not. 
considering https://github.com/netbox-community/netbox/issues/8054 has allowed the overwriting of built in status's, I think we should offer the same functionality to ip-addresses roles. 

Having custom role functionality allows for clearer display of an ip's purpose. Otherwise this same data ends up in the large sea of custom fields.

**Comment by jeremystretch** [comment]
The role attribute choices aren't customizable because they're not arbitrary.

> ptp - point to point links

Whether an IP address is suitable for use on a point-to-point link is a function of its mask. You would not designate a /24 IPv4 address as point-to-point.

> primary - wanting to mark the primary ip of a pair of fw's

Primary for what? the designation of an IP as primary for anything depends on a context. If it's the primary IP for a device, then you designate it as such using the device's `primary_ip` attribute.

> management - marking ips as mgmt ips

NetBox tracks this via the interface model: Interfaces can be designated as management interfaces, and any IP addresses associated with those interfaces are thus considered management IPs.

**Comment by bwm-digitalc** [comment]
Jeremy, I'll provide an example that might help - I have a Nutanix cluster. They use a "floating" management IP for the cluster - it does **not** use HSRP or VRRP or CARP or any other listed methodology to handle the ownership of that IP, but it does dynamically move around between the cluster nodes.

It's not really a "secondary" IP, because it's intended as the main management interface for the cluster, although it is technically a "secondary" to the actual node's local IP. 

What "IP Role" is that sort of device supposed to have, or should it just be left blank? In my head, it behaves somewhat like a VRRP IP, so I feel like some sort of "Role" should be defined... but the system I'm working with doesn't actually *use* any of the listed methods.

I feel like people might be less inclined to ask for customization here if it had a different name, too. I see "IP Role" and my mind goes to, "what is this address doing / being used for." Obviously you should be able to derive that from knowing what it is attached/assigned to... but some of us don't necessarily have the luxury of defining all of the equipment in all cases. In those instances, a way to define the address's "intended usage" is desirable and helpful.

**Comment by jeremystretch** [comment]
> What "IP Role" is that sort of device supposed to have, or should it just be left blank?

This would be a virtual IP (VIP), which is one of the available role choices.

**Comment by jeremystretch** [comment]
I'm going to close this as the proposal conflicts with an intentional design choice.
