### ISSUE TITLE
Apply IPAM Role object to ASN

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#9044]
### NetBox version

v3.2.0

### Feature type

Data model extension

### Proposed functionality

Allow users to optionally associate the IPAM role model to ASNs.

### Use case

A common use case would be to assign an ASN for different uses like with peering to external internet (public ASN for a site or sites) vs internal peering using a private ASN.

### External dependencies

N/A

**Comment by ryanmerolle** [comment]
This does not seem to be a major ROI item.  Frankly, with custom field relationships to other objects, a user could either leverage a device role or IPAM role relationship to model the above.  Happy to close this out or wait for the bot to close it.

**Comment by ryanmerolle** [comment]
@jeremystretch if I took a stab at this, would you be cool with this added to the model?

It feels like low hanging fruit that I could apply what I learned from plugin development.

**Comment by jeremystretch** [comment]
I'm going to close this out as it has not garnered any interest. It also seems like a poor fit trying to tie prefix & VLAN roles to AS number. A custom field would probably work better, and since v3.2 you can use an [object-based custom field](https://docs.netbox.dev/en/stable/customization/custom-fields/#custom-object-fields) on the ASN model to achieve the same thing.
