### ISSUE TITLE
Prettify SSO login links

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9123]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

Display a proper name (and possibly logo?) for any configured remote authentication backend. These could be stored in a static mapping. For example:

```
AUTH_BACKENDS = {
    'azuread-oauth2': {
        'name': 'Microsoft Azure AD',
        'logo': 'path/to/logo.png',
    }
}
```

The login template would attempt to resolve these attributes for the configured backend and render accordingly.

### Use case

The current SSO login link, while functional, is rather spartan and conveys only the name of the configured backend. A proper name for the authentication service would be more user-friendly.

![netbox_sso_login](https://user-images.githubusercontent.com/13487278/163268859-d5164cab-6c41-4d5a-8ad7-8220b7a70c0b.png)

**Comment by jeremystretch** [comment]
Opened python-social-auth/social-core#680 to see if there's any interest in defining canonical user-friendly backend names upstream.

**Comment by oasys** [comment]
In my experience, many organizations will "brand" their SSO with a custom name, as something like "Company Foo OneLogin".   The result is that the application users may not even know what the backend actually is.   Because of this, I'd certainly prefer that the name is still customizable within NetBox, even if `python-social-auth` provides a friendly name.

**Comment by jeremystretch** [comment]
@oasys we could certainly look into that, however proposing a new configuration parameter(s) would need a separate FR. For now I'm just focused on improving the cosmetic appearance.
