### ISSUE TITLE
Cable to rack connection

### ISSUE THREAD

**Issue by AndMrzv** [netbox-community/netbox#9172]
### NetBox version

v3.1.10

### Feature type

Data model extension

### Proposed functionality

Allow whole Racks to be set as a connection point for Cables (instead of a specific Interface of a Device as it is now) as a connection point.

### Use case

Having rented out racks you don't manage devices in them (a client plugs cables himself), you may not even have access inside of it. But the cables (network, power) going from your equipment into such racks are your responsibility, need to be managed and show the connection side.
Also it is nice to have cables managed when they are laid to yet empty racks (waiting to be filled with devices) or are still in the rack when the devices it was previously connected is taken out (now you have to delete the cable without one side from Netbox).

**Comment by jeremystretch** [comment]
Sorry but I have to reject this FR, as it would violate one of our core design tenets: replicate the real world. You cannot connect a cable to a rack in NetBox because you cannot connect a cable to a rack in reality.

You have two options under the current model:

1. Create a dummy/unmanaged device in the rack that exists solely to terminate the far end of the cable.
2. Forego modeling the cable and set `mark_connected` on the local interface to true.

**Comment by AndMrzv** [comment]
> 1. Create a dummy/unmanaged device in the rack that exists solely to terminate the far end of the cable.
Yes, this is exactly how we work around it now.

Replicating real world by dummies seems a bit strange to me but thank you for providing the explanation.

**Comment by jeremystretch** [comment]
It's not strange at all. You know the cable connects to a device at the far end, you just don't know much about it, so you're limited in what you can model. Conversely, you know that the cable definitely _doesn't_ connect to the rack itself.
