### ISSUE TITLE
Multiple termination sides for Curcuits

### ISSUE THREAD

**Issue by AndMrzv** [netbox-community/netbox#9174]
### NetBox version

v3.1.10

### Feature type

Data model extension

### Proposed functionality

Allow Curcuits to have multiple termination sides (now they can have 0-2).

### Use case

Bus network.
Using Circuits in a meaning of a communication line between multiple objects (typically few Racks, provider side). Such a line may be complex but it is in fact a single unit in every regard, making it to be this way in Netbox would provide much cleaner experience than storing it as a bunch of Circuits all connected together.

**Comment by AndMrzv** [comment]
> Please provide a real-world example of your cited use case.
I thought in terms of BNC or CAN to support my cause but probably not many people use coaxial nowdays.
But we do have for example big comm lines that go across few of our data-centers stringing them all together. Said line or a channel (sorry, English is not my first, I hope you'll be able to understand) includes our own connections, external provider conenctions, maybe some other ifrastructural cable lines. And this is managed as a whole.

**Comment by thefreakquency** [comment]
A real world example would be a point-to-multipoint circuits. We have a few circuits that are provided to us that are, at a high level, an extended private VLAN over Metro-Ethernet. I currently model the site to provider "cable", and model a circuit in Netbox for every possibility (i.e.: Site A to B, Site A to C, Site B to C) as we don't have many of those circuit type (only two 3-ends circuits). I would see why somebody would like that type of model. 

Another real-world example would be a ISP-provided MPLS network which would also a point-to-multipoint circuit.

**Comment by jeremystretch** [comment]
> I thought in terms of BNC or CAN to support my cause but probably not many people use coaxial nowdays.

If anything, these would be modeled as cables rather than circuits, but I think it's fair to say that NetBox simply doesn't support them as they're no longer in common use in modern networks.

> But we do have for example big comm lines that go across few of our data-centers stringing them all together.

These would be modeled as individual circuits in NetBox.

> A real world example would be a point-to-multipoint circuits

This has been brought up numerous times. The summary is that each leg of a point-to-multipoint topology is its own circuit, with its own circuit ID, and should be modeled as such. (Consider the process for ordering and installing a new spoke circuit.) Mesh and point-to-multipoint topologies would be modeled as virtual circuits on top of the physical infrastructure; something we plan to implement eventually though to date no one has proposed a specific scheme.

I'm going to close this FR as it would not make sense to allow more than two terminations per circuit, but I encourage anyone interested to come up with a proposal for modeling virtual circuits. (If you choose to take this on, please be sure to include a detailed implementation plan including database changes with your future FR.)
