### ISSUE TITLE
Folder-like prefix type?

### ISSUE THREAD

**Issue by lamoni** [netbox-community/netbox#9188]
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

I think it would be useful if there were "folders" for prefixes for better top level organization or prefixes.

As an example, say our private space is 192.168.0.0/16, and then we have a lot of public /31s, and /30s that are given to us by a provider. When browsing to the prefix page, I would want to see just "Public" and "Private" folders, and within the Private folder is the 192.168.0.0/16 space and within the Public folder is the varying public IPs. Even if this was just for the top layer, it would be helpful.

As of right now, the varying public IPs we have muddies up the initial Prefixes page.

If anyone is familiar with Solarwinds IPAM, it would be the same thing as their "Group" or "Hierarchy Group" folders I think.

If there is interest in this, I wouldn't mind making an attempt at it.

### Use case

Better organization for public vs private prefixes. Possibly improve loading time of the initial prefix page?

### Database changes

Not sure

### External dependencies

None that I know of

**Comment by TheNetworkGuy** [comment]
We migrated from phpIpam (which has this feature) to Netbox and we don't mis these roles at all. Actually i prefer the way Netbox handles the layout rendering with the IP CIDR model instead of manually grouping prefixes in a group.

You can search for private address spaces using RIR's, Agregates or even roles. That's how we use some kind of filtering on our network space.
