### ISSUE TITLE
Add an option to adopt existing DeviceComponents when installing modules

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#9280]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

Add an option to adopt existing DeviceComponents when installing modules. The option would change the module of all DeviceComponents on the target device with the same name as the component being added by the module.

### Use case

Making it easier to migrate to using modules for devices with manually added DeviceComponents.

### Database changes

None.

### External dependencies

None.

**Comment by jeremystretch** [comment]
I like it. We should end up with four possible conditions depending on which boxes are checked:

| Replicate | Adopt | Result |
|---|---|---|
| - | - | No components get created or updated |
| x | - | New components get created but existing components are unmodified |
| - | x | Existing components with matching names are assigned to the module, but no new components are created |
| x | x | If a matching component exists, assign it to the module; otherwise create a new one |
