### ISSUE TITLE
Prefix export replacing subnets with â€¢

### ISSUE THREAD

**Issue by bakergt1** [netbox-community/netbox#9407]
### NetBox version

V3.2.2

### Python version

3.9

### Steps to Reproduce

1. Select selecting prefixes from site
2. export current view
3. Output is showing as

Prefix
10.51.16.0/20
"â€¢
        
10.51.16.0/24"
"â€¢
        
10.51.17.0/24"
"â€¢
        
10.51.18.0/24"
"â€¢
      
10.51.20.0/22"

### Expected Behavior

there should be no â€¢ and blank lines in the export

### Observed Behavior

nil

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by inigoleaga** [comment]
I have the same issue. Let me introduce some more info:

### Netbox version:
v3.2.2

### Python version:
v3.8.10

### Steps to Reproduce:

1. Go to IPAM -> Prefixes
2. Filter the prefixes you want to export
3. Select Export -> Current view
4. A .csv will be downloaded.
5. Open the .csv

### Expected behavior:
When you open the CSV file you can see all the prefixes you had in your filter.

### Observed behavior:
When you open the CSV file you can only see the parent networks. Any other prefix that is a child of another, will appear as "â€¢". Please, check the attached image:

![image](https://user-images.githubusercontent.com/43034818/169822680-913bfcf2-41db-460a-a0ba-b2b2942ed3ad.png)

Hope this clarifies the issue.

**Comment by jeremystretch** [comment]
The garbage characters result from improperly decoded Unicode, representing the hierarchical indentation of each prefix. You'll need to investigate your NetBox deployment and/or browser to determine why the fields are not being decoded properly. (You can confirm that this works as expected on the public demo instance.)

As for the content itself, it should be possible to implement a custom table column that omits the prepended characters from the output when rendering CSV data. Alternatively, you can work around this by swapping out the "Prefix" table column with the "Prefix (flat)" column before performing the export.

**Comment by bakergt1** [comment]
Thanks Jeremy, this is only a new problem we have come across, its something that I have been using often. But we will investigate locally and see if we can work out what is happening.
