### ISSUE TITLE
Collapsable DHCP IP ranges

### ISSUE THREAD

**Issue by inigoleaga** [netbox-community/netbox#9412]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

It would be nice if you could collapse (and uncollapse) a consecutive list of IPs which status is "DHCP".

### Use case

Sometimes, you can find a large DHCP IP pool that messes up the "IP Address" tab of a prefix:

![image](https://user-images.githubusercontent.com/43034818/170004334-905fafb0-d9bf-4347-bf0a-c5cd14773bcb.png)
 
It would be helpful to see a unique line that represents the hole DHCP IP pool. That way, the rest of the manually assigned IPs would be seen, removing some importance to the DHCP range, since in some cases it does not provide much valuable information.

### Database changes

-

### External dependencies

-

**Comment by jeremystretch** [comment]
The simple solution is to use the IP range model, which was introduced specifically for this purpose.

**Comment by inigoleaga** [comment]
I actually have the same "issue" if I create an IP range:
![image](https://user-images.githubusercontent.com/43034818/170060615-386ebe3e-2b85-4594-9a11-b9f3bb1e69ff.png)

If I check the IPs under the "IP range" I see the same:
![image](https://user-images.githubusercontent.com/43034818/170061659-e5775e44-ac7d-4a3d-be55-1cd61945f76e.png)

And If I remove the IPs they will be presented as "available" when they are not:
![image](https://user-images.githubusercontent.com/43034818/170061002-e8e0901b-a39a-4c36-b83c-902f9c0be486.png)

**Comment by nem1989** [comment]
I'm having the same issue here. When I define an IP range, DHCP for instance, all of it's IP addresses still count as available in prefix. 
For example let's say I have a subnet (192.168.1.0/24) with a gateway (192.168.1.1) and DHCP range 192.168.1.2 - 192.168.1.99.
Then in Netbox I define:

- a prefix 192.168.1.0/24
- an IP address 192.168.1.1
- an IP range 192.168.1.2 - 192.168.1.99 marked as reserved.

Then all IP addresses except 192.168.1.1 are listed as available in prefix 192.168.1.0/24 which is not what I expect to see.
Instead I expect available IP's to start from 192.168.1.100 since there is a reserved IP range in place.

To achieve what I want I have to bulk create individual IP addresses in mentioned range to fill it. Think of it: why do I need ranges if I have to create the whole set of IP's anyway?

Is this going to be fixed? Or is it by design? 
It would be great to have a checkbox for IP ranges to mark one as 100% utilized just like we can do with prefixes.
