### ISSUE TITLE
Option to attatch MAC Address to IP Addresses

### ISSUE THREAD

**Issue by Decafpancakes** [netbox-community/netbox#9422]
### NetBox version

v3.2.3

### Feature type

New functionality

### Proposed functionality

The ability to add an associated MAC to an IP under IPAM IP Addresses without creating Interfaces or Devices.  Would also like some sort of validation on the MAC so that they cant repeat. There is also no duplicate check for DNS name either, this would also be important to have. 

### Use case

This would help the transition from IPPlan to NetBox. Also useful for when exporting to a DHCP server.

**Comment by DanSheps** [comment]
The problem with this is that MAC addresses are almost never associated to IP addresses.  You get them associated to FHRP groups, interfaces, etc.  Your import script should take this into account.

**Comment by jeremystretch** [comment]
I'd argue that what you want to model is analogous to an ARP record; a binding between an IP address and a MAC address. NetBox doesn't model these natively (the relationship between IPs and MACs exists through interfaces) but you could easily do so in a plugin.

**Comment by sleepinggenius2** [comment]
We have something like this implemented today using a custom field to capture the MAC address for static DHCP reservations. This is absolutely critical for our use case to be able to create the reservations in IPAM and subsequently generate the corresponding DHCP server config. I think OP is talking about a similar use case and I suspect a number of other people are also using NetBox within a DDI solution. We have a simple regex validator in place today for the custom field to catch obviously malformed input, but it would be really nice to have the value standardized/normalized like the interface MAC addresses are today and not have to do that work after they are retrieved for an integration. We are not able to use the Interface model for this, as these are primarily customer devices that we do not have in our network inventory and it would not be practical to do so.

**Comment by Decafpancakes** [comment]
@sleepinggenius2 Would you be able to share how you got this setup? Would be a huge help, thanks!

**Comment by Decafpancakes** [comment]
@sleepinggenius2 Thank you for that, I did already have a very similar custom field set up but you filled in some details that I didn't have like the regex value. You had mentioned that you have a script that is exporting the reservations to a dhcp config, could you share this with me since I have to do the same thing? Feel free to msg me: decafpancakes@gmail.com

**Comment by DanSheps** [comment]
> This is absolutely critical for our use case to be able to create the reservations in IPAM and subsequently generate the corresponding DHCP server config

This would be something you would want to develop a plugin for then.  However, you could also obtain this information simply by querying the IP and getting the mac addresses of the interface that an IP is assigned to.

**Comment by sleepinggenius2** [comment]
> @sleepinggenius2 Thank you for that, I did already have a very similar custom field set up but you filled in some details that I didn't have like the regex value. You had mentioned that you have a script that is exporting the reservations to a dhcp config, could you share this with me since I have to do the same thing? Feel free to msg me: [decafpancakes@gmail.com](mailto:decafpancakes@gmail.com)

We are using a combination of Webhooks and a periodic batch audit process to keep the data synchronized with our DHCP server today. Unfortunately, I'm not going to be able to provide that code, as it's part of a larger custom provisioning platform and would vary depending on the specific type of DHCP server that you're using.

> > This is absolutely critical for our use case to be able to create the reservations in IPAM and subsequently generate the corresponding DHCP server config
> 
> This would be something you would want to develop a plugin for then. However, you could also obtain this information simply by querying the IP and getting the mac addresses of the interface that an IP is assigned to.

The issue for us is that we can't associate the IP with an interface, since the device that the IP is assigned to does not exist within our NetBox platform. It is typically CPE that belongs to a customer, and we have not found a practical, non-hacky way to maintain that data in the platform.

I agree wholeheartedly with associating an IP to an interface where possible, which is exactly why I made the field description say what it does. In fact, I would love to see this implemented as maybe another tab under the *Interface Assignment* section of the IP address form, so you have to explicitly choose to enter the MAC manually. I'm actually working on a custom validator to make sure that the *Status* is *DHCP*, has our *Static* tag set, and is not otherwise assigned to be able to populate our current custom field.

**Comment by DanSheps** [comment]
I think in the context of DHCP, you would be better of having a "DHCPScope" model and then having an association between IPAddress and the scope, with a field on the join table for "MacAddress"

Again, this would have to be done in a plugin as this is likely not to be included in Core.

**Comment by jeremystretch** [comment]
To summarize the discussion above, there are several options to address this use case:

* Map MAC addresses to IP addresses via interface assignment
* Add a custom MAC address field to the IP address model
* Introduce a new model via a plugin for tracking the specific data structure needed (e.g. ARP record or DHCP lease)
