### ISSUE TITLE
Rack Elevation Sorting Enhancement

### ISSUE THREAD

**Issue by NavyWings** [netbox-community/netbox#9665]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

Would be a helpful feature if we were able to sort the rack elevation by rack facility ID.

Currently, the rack elevation view sorts only on rack name. It can be sorted in "normal" (numerically ascending) or "reversed" (numerically descending.)"

### Use case

Rack naming conventions are dependent on organization, not all entities name or number racks in a contiguous linear fashion from left to right. In our case, our center racks are numbered racks one and two and numbering increases as you move further from the center racks. It would be a helpful feature to see the rack elevation ordered by facility ID from left to right while retaining a custom rack naming at the top.

### Database changes

Likely none, but unknown.

### External dependencies

None

**Comment by arthanson** [comment]
@jeremystretch The current sort is a button-toggle, which wouldn't work for adding any new sorting.  If we add this I see two potential solutions:

1. Add a "Sort By" dropdown in-place of the buttons, with options "Name (A-Z)", "Name (Z-A)", "Facility ID (A-Z)", "Facility ID (Z-A)" could also use (Ascending) / (Descending) instead of (A-Z).  
2. Move the button below the tabs and have a "Sort By: " and then the dropdown showing the current sorting. (see screenshot)

I looked around and all the other sorting is done by column headers, so this looks like a sort of one-off UI.

![sortby](https://user-images.githubusercontent.com/99642/186536188-47d35b2e-9d90-4bd4-b051-aa99741f02f1.png)

**Comment by jeremystretch** [comment]
I think a dropdown with all four combinations makes sense. A-Z and Z-A is fine.
