### ISSUE TITLE
VM device selection does not filter the list by the selected site

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9728]
### NetBox version

v3.3.0-beta1

### Python version

3.9

### Steps to Reproduce

1. Create a new VM named `vm1` and associate it to site `DM-Akron` and click Save
2. Edit the same VM and click on the Device drop-down and choose the 1st entry from the list and click save

### Expected Behavior

The device list should be pre-filtered by the already associated site

### Observed Behavior

An error is thrown (this is good to have as validation but not so user-friendly approach)

![image](https://user-images.githubusercontent.com/5083532/179052470-75127b6e-c6e4-41d5-ad91-0c4d9cf4f92e.png)

**Comment by jeremystretch** [comment]
> Edit the same VM and click on the Device drop-down and choose the 1st entry from the list and click save

The issue is that the devices is list is not being filtered by the assigned site; easy enough to fix.

However, there's a second issue, where even if a device within that site is selected, an `AttributeError` exception is raised because a device has been selected but no cluster is assigned. This is because we're missing a validation rule for the cluster.

I'm going to resolve both bugs under this issue as they're very closely related.
