### ISSUE TITLE
DeviceBay matching query does not exist.

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9729]
### NetBox version

v3.3.0-beta1

### Python version

3.9

### Steps to Reproduce

I wanted to see the changes for the cable tracing and clicked on a link from https://beta-demo.netbox.dev/dcim/interfaces/1018/ which redirected to https://beta-demo.netbox.dev/dcim/interfaces/1018/trace/

### Expected Behavior

Trace page should open up

### Observed Behavior

![image](https://user-images.githubusercontent.com/5083532/179052876-b5dd04be-63df-41f0-904f-4629b9384ad4.png)

**Comment by jeremystretch** [comment]
This looks like a data migration issue. Comparing the beta demo against my local instance, the interface's cable path is exactly the same, however the content type IDs in the two databasese differ. ContentType 32 locally is `dcim.interface`, but on the demo it's `dcim.devicebay`.

The root issue is that we're copying content type IDs blindly in the database migrations. This won't affect direct upgrades, but does obviously cause an issue for transplanted data. I'll need to tweak the migration to account for changing content type IDs.

**Comment by jeremystretch** [comment]
The root cause is the `0160_populate_cable_ends` migration within the `dcim` app, which is compelling the creation of content types for the nine models which support cable termination. (These are required to write generic foreign key values to the database.) This is throwing off the primary keys for these content types as compared to the static values captured in the demo data.

The ideal solution would be to return to the original order of creation for content types, though I'm not sure yet how feasible that is. The alternative approach is to alter the process for dumping the demo data to accommodate the change in content type IDs. (The simplest approach would be to switch to raw SQL dumps, although that introduces its own set of challenges.)

**Comment by jeremystretch** [comment]
Ended up just tweaking the migration to avoid retrieving not-yet-created content types during the cable termination updates. Content types are back to normal now, which ensures compatibility with the demo data.
