### ISSUE TITLE
Add Tags and links to global search

### ISSUE THREAD

**Issue by tokarenkos** [netbox-community/netbox#9852]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

Add global search support for the Tags and link models Other.

### Use case

Extends global search to include these objects. 
Example: search for something "Tags" devices one type

**Comment by jeremystretch** [comment]
Tags are intentionally excluded from global search because it would be extremely inefficient to include them in the current implementation. It's something we can consider once a more robust global search mechanism has been identified.

Assuming by "links" you mean custom links, it would not make sense to include in search results as the link values are rendered at read time (and unlikely to be of interest anyway).
