### ISSUE TITLE
Remove delete button from UI with tabs and subcomponents.

### ISSUE THREAD

**Issue by pdenessen** [netbox-community/netbox#9875]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

If you have a model like a device with a tab with several subcomponents, like bays or interfaces, and you select a nr of them, then you will see 2 delete buttons. One on the top right corner, for deleting the whole device and one at the bottom of the list for selecting just the selected items.
If this list is very long  and you select just a few entries on the top of this list then you even don't see the correct button on the bottom of the list but only the delete button for the device.
This is very confusing and especially new users can click the wrong button and then select the whole device. This happened to me twice, where after I had to add the whole device with its components again.

### Use case

Remove the delete button for the device in the upper right corner from the UI when one of the tabs is selected to avoid confusion.

### Database changes

No database changes are needed, just UI adaptations.

**Comment by jeremystretch** [comment]
I don't see how this is confusing. The object edit and delete buttons are always at the top right corner, and the bulk actions for list objects are always at the bottom left.

**Comment by pdenessen** [comment]
Hi Jeremy I have added 2 screenshots to visualize the problem. 
In screenshot 1 dont you see the correcte delete button on the bottom if you don't scroll down.
In screenshot 2 do you have 2 delete buttons.
![Screenshot_1](https://user-images.githubusercontent.com/11139454/181763676-1e273d1e-9e4a-434d-8c54-55eac8f46377.png)
![Screenshot_3](https://user-images.githubusercontent.com/11139454/181763763-ce6f56e5-f3df-4fde-9dd9-5d6c823d34b5.png)

**Comment by PieterL75** [comment]
I do follow this. We had several users clicking that 'delete' button on the top, if they selected items from a list.
I 'solved' that by removing the 'delete device/vm' rights from all users, except some admins

Or relabel that top right button to 'Delete Device' ?

**Comment by DanSheps** [comment]
I could get behind changing the button to be "Delete [object]" for the top one.

**Comment by jeremystretch** [comment]
> I could get behind changing the button to be "Delete [object]" for the top one.

The object buttons all used to have that format, however it wastes a lot of screen space, especially for models with longer names.

**Comment by PieterL75** [comment]
Or go for the same system as in an object list.
Only show the edit button, and place the delete in a drop-down

**Comment by pdenessen** [comment]
Hi Pieter, this works only if you have to delete a few items. This will be a lot of work if you have a whole list. Best would be to hide the delete button in the upper right when you see tabs listing items other then the device itself.  Just keep the the delete button with the main tab.

**Comment by PieterL75** [comment]
What I meant is, that the top right button could be hidden under the edit button, just like the edit/delete buttons on a table like.
Then the delete button of the object works not be directly visible, but the item delete buttons are still there

**Comment by pwrgfi** [comment]
Not too muddy the water too much with regards to this specific proposal "remove delete button" - but then I've also noticed this sentence in the op:

> If this list is very long and you select just a few entries on the top of this list then you even don't see the correct button on the bottom of the list but only the delete button for the device.

I agree and have been bitten by the same issue (once) and I found this Github issue just when I was about to open a new issue for UX enhancement that was more about "reduce amount of mouse scrolling", but might alleviate this issue as well:

At the moment, users need to scroll unnecessarily in many contexts - with tables, the bulk action buttons are shown on the bottom of the table only. My UX suggestion was to suggest to add it at the beginning of the table, too. Otherwise you spend 80% of your time scrolling if, for some reason, you've got many entries in the view and you just want to, say, delete, just a few of them.
- alternative suggestion: leave the buttons at the bottom only, but not at the bottom of the table, but as persistent, non-scrolling footer that is always visible. This way, even if your table is 1000 entries long and you want to delete items 490, 501 and 530 you don't need to scroll at all after selecting the last item.
- adding "... selected" to the item selection action buttons was another UX suggestion I'd wanted to log, precisely because at the moment there is a button at the top and one at the button that is labelled the same but does different things altogether. If the table-level buttons were displayed at the top or in a permanently visible footer it would be even more important to be able to differentiate the impact of the buttons.

**Comment by PieterL75** [comment]
I opened a similar 'lesd scrolling' idea here #9386.
But I think we need to get to a good compromise here. How to get rid of the confusion that can exists when 2 different objects (a device and device interfaces) are shown on one page

**Comment by pdenessen** [comment]
If you have a screen with the focus on the device (First tab: device) then the visible buttons should be for the device. If you have however a  tab wit a lot of components (interfaces, modules, devices etc) listed then the focus is on this list and the buttons should also be applicable for this list. 
So my proposal is to keep the "device"- buttons for the 1st device tab and replace these buttons on the tabs with lists to handle these listed elements.

**Comment by PieterL75** [comment]
Any other thoughts?
What I see is
- change the bottom 'delete' button to 'delete selected' (also for the edit one)
- change the ui to reduce the scrolling, and always show the bottom buttons
P
