### ISSUE TITLE
Can't add new device on 3.3-beta2

### ISSUE THREAD

**Issue by Miccia94** [netbox-community/netbox#9946]
### NetBox version

3.3-beta2

### Python version

3.9

### Steps to Reproduce

Creating a new device from gut or api

### Expected Behavior

Device should be added correctly

### Observed Behavior

<class 'django.db.utils.ProgrammingError'>

column dcim_interfacetemplate.poe_mode does not exist
LINE 1: ...te"."type", "dcim_interfacetemplate"."mgmt_only", "dcim_inte...

**Comment by jeremystretch** [comment]
This is not a bug. The error is occurring because your database was not properly migrated. Please try the installation again, following the documentation provided [here](https://docs.netbox.dev/en/stable/installation/). If you still require assistance, please open a [discussion](https://github.com/netbox-community/netbox/discussions/new).
