### ISSUE TITLE
reserve either 'front' or 'rear' of rack units

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#9975]
### NetBox version

v3.2.8

### Feature type

Change to existing functionality

### Proposed functionality

i would like to reopen issue #9090 which was marked as closed due to inactivity, but I find it very useful. 

"When adding device reservations for a rack there is no distinction between reserving the front U of the rack, or the rear U of the rack. Not all devices are full depth.

Modify existing reservation mechanism to have the 'Rack Face' and 'Full Depth' options to allow someone to reserve either the front or rear of the rack, and either the full depth or not."

### Use case

"If I were to have a cable manager on the front of a rack this device is not full depth. This would leave plenty of room in the rear of the rack to mount something else. Another cable manager perhaps, or a patch panel.

This feature would allow someone to have a non full-depth device occupying rack unit 40 in the front, while reserving rack unit 40 in the rear for another non full-depth device."

### Database changes

not sure

### External dependencies

not sure

**Comment by jeremystretch** [comment]
I'm closing this issue because you've intentionally created a duplicate issue, copying content verbatim from #9090.

The original FR was closed automatically after three months of inactivity because it did not find interest in the community. If you'd like to revisit the proposal, you'll need to bring something new to the table. You're welcome to do so in a new, original feature feature request.

**Comment by opericgithub** [comment]
Yes, I copied the issue because I didn't want to take credit for other's work.
